### ISSUE TITLE
优酷 下载随机 403

### ISSUE THREAD

**Issue by yibu10** [zhangn1985/ykdl#1]
extractor.py", line 145, in download_normal
    save_urls(urls, name, self.streams[stream_id]['container'])
  File "/Users/freestyler/git/bitbucket/d-service/lib/python2.7/site-packages/ykdl/util/download.py", line 57, in save_urls
    save_url(u, n)
  File "/Users/freestyler/git/bitbucket/d-service/lib/python2.7/site-packages/ykdl/util/download.py", line 28, in save_url
    response = urlopen(req, None)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 403: Forbidden

多试几次又好了

**Comment by yibu10** [comment]
应该是下完一段OK， 下一段就403了。。

**Comment by zhangn1985** [comment]
有测试URL吗？

**Comment by yibu10** [comment]
ykdl 'http://v.youku.com/v_show/id_XMTU5MTczMDkyOA==.html?from=y1.9-3.1'

**Comment by zhangn1985** [comment]
我知道youku 有一定概率404是因为转码还没完成。

**Comment by yaonizui** [comment]
虎牙直播提示、
site:                Huya Live (虎牙直播)
title:               你是我的小丫小苹果~
Traceback (most recent call last):
  File "E:\Python\Python35-32\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "E:\Python\Python35-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "G:\idm\ykdl-master_2\ykdl\__main__.py", line 6, in <module>
    main()
  File "G:\idm\ykdl-master_2\ykdl\__init__.py", line 47, in main
    m.download(u, args)
  File "G:\idm\ykdl-master_2\ykdl\extractor.py", line 94, in download
    self.download_normal()
  File "G:\idm\ykdl-master_2\ykdl\extractor.py", line 119, in download_normal
    self.print_info()
  File "G:\idm\ykdl-master_2\ykdl\extractor.py", line 66, in print_info
    print("artist:              %s" % self.artist)
UnicodeEncodeError: 'gbk' codec can't encode character '\u2764' in position 29:
illegal multibyte sequence

**Comment by zhangn1985** [comment]
please use `chcp 65001` to change current code page to unicode.
