### ISSUE TITLE
weibo.com/tv/v/无法下载，解析错误

### ISSUE THREAD

**Issue by demostars** [zhangn1985/ykdl#106]
您好~

```
C:\Users\Server>ykdl http://weibo.com/tv/v/d1af6916ed4b9ced3d1f9ae23ac27b81?fid=1034:d1af6916ed4b9ced3d1f9ae23ac27b81
Traceback (most recent call last):
  File "c:\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python36\Scripts\ykdl.exe\__main__.py", line 9, in <module>
  File "c:\python36\lib\site-packages\cykdl\__main__.py", line 139, in main
    info = parser(u)
  File "c:\python36\lib\site-packages\ykdl\extractor.py", line 21, in parser
    info = self.prepare()
  File "c:\python36\lib\site-packages\ykdl\simpleextractor.py", line 58, in prepare
    ext, size = self.get_info()
  File "c:\python36\lib\site-packages\ykdl\simpleextractor.py", line 44, in get_info
    _, ext, temp = url_info(u)
  File "c:\python36\lib\site-packages\ykdl\util\html.py", line 100, in url_info
    f = url.split('?')[0].split('/')[-1]
AttributeError: 'NoneType' object has no attribute 'split'
```

视频地址是 http://weibo.com/tv/v/d1af6916ed4b9ced3d1f9ae23ac27b81?fid=1034:d1af6916ed4b9ced3d1f9ae23ac27b81 

以及类似的视频，起实际下载地址在

https://github.com/soimort/you-get/issues/1789 

不过看这里报错似乎不是解析的问题而是网址本身不匹配~

**Comment by demostars** [comment]
![image 1](https://cloud.githubusercontent.com/assets/20697190/24835671/3430b0e6-1d3a-11e7-8d2a-5ea3cb2d64d1.png)

NOT FIXED

**Comment by demostars** [comment]
FIXED

Please close this issue
