### ISSUE TITLE
cannot http://v.youku.com/v_show/id_XMzEwNDE3Njg4.html?tpa=dW5pb25faWQ9MTAzNjY3XzEwMDAwMV8wMV8wMQ

### ISSUE THREAD

**Issue by redstoneleo** [zhangn1985/ykdl#110]
```
ykdl -i http://v.youku.com/v_show/id_XMzEwNDE3Njg4.html?tpa=dW5pb25faWQ9MTAzNjY3XzEwMDAwMV8wMV8wMQ
Traceback (most recent call last):
  File "/usr/local/bin/ykdl", line 11, in <module>
    load_entry_point('ykdl==1.4.7', 'console_scripts', 'ykdl')()
  File "/usr/local/lib/python3.5/dist-packages/cykdl/__main__.py", line 139, in main
    info = parser(u)
  File "/usr/local/lib/python3.5/dist-packages/ykdl/extractor.py", line 21, in parser
    info = self.prepare()
  File "/usr/local/lib/python3.5/dist-packages/ykdl/extractors/youkubase.py", line 26, in prepare
    'fileid': stream['stream_fileid'],
KeyError: 'stream_fileid'


```

a helpful insight here https://github.com/soimort/you-get/issues/1849#issuecomment-294159217

**Comment by rosynirvana** [comment]
这边大概会比较乐意换到新接口吧？

**Comment by zhangn1985** [comment]
duplicate to #90

**Comment by redstoneleo** [comment]
等API稳定不知要到何时，这里已经有修复了https://github.com/xuhaomin/you-get/blob/develop/src/you_get/extractors/youku.py

**Comment by zhangn1985** [comment]
真的很忙。

**Comment by redstoneleo** [comment]
@zhangn1985 老大辛苦啦！我这两天也是在修复我那个下载器的各种问题，搞软件的都一样——只要继续维护，bug总是层出不穷啊~~~

**Comment by zhangn1985** [comment]
@rosynirvana 倾向于切换到新接口。但需要花点时间。
