### ISSUE TITLE
在win10下无法调用播放器播放

### ISSUE THREAD

**Issue by Gokou-Ruri** [zhangn1985/ykdl#114]
视频可以用“ykdl [URL]”的方式下载，但添加“-p”参数以后却无法播放。
播放器为potplayer，路径已经添加为系统变量且进程名称没有错误，ykdl版本为1.4.8。
URL首尾添加半角双引号也无法播放。

当URL为爱奇艺视频链接时，播放器不会被启动(播放器未被运行)；
```
[ykdl -p potplayermini64 http://www.iqiyi.com/v_19rraw3ccs.html
site:                爱奇艺 (Iqiyi)
title:               博人传 火影忍者新时代第3集
artist:              None
streams:
    - format:        BD
      container:     flv
      video-profile: 1080p
    # download-with: ykdl --format=BD [URL]
Traceback (most recent call last):
  File "c:\python36-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python36-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python36-32\Scripts\ykdl.exe\__main__.py", line 9, in <module>
  File "c:\python36-32\lib\site-packages\cykdl\__main__.py", line 149, in main
    handle_videoinfo(info)
  File "c:\python36-32\lib\site-packages\cykdl\__main__.py", line 100, in handle_videoinfo
    launch_player(args.player, urls)
  File "c:\python36-32\lib\site-packages\ykdl\util\wrap.py", line 10, in launch_player
    subprocess.call(shlex.split(player) + list(urls))
  File "c:\python36-32\lib\subprocess.py", line 267, in call
    with Popen(*popenargs, **kwargs) as p:
  File "c:\python36-32\lib\subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "c:\python36-32\lib\subprocess.py", line 990, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] 系统找不到指定的文件。]
```

当URL为优酷视频链接时，播放器能够被打开，但播放器提示“无法播放，服务器已关闭或地址错误”。
```
[ykdl -p potplayermini64 http://v.youku.com/v_show/id_XMjcwMjQ2ODYzMg==.html?spm=a2h0j.8191423.item_XMjcwMjQ2ODYzMg==.A
site:                优酷 (Youku)
title:               第01话 月日食
artist:              None
streams:
    - format:        BD
      container:     flv
      video-profile: 1080p
      size:          536.9 MiB (563014249 bytes)
    # download-with: ykdl --format=BD [URL]
（之后播放器界面会提示“无法播放，服务器已关闭或地址错误”）
]
```

**Comment by zhangn1985** [comment]
区分大小写。PotplayerMini64.
至于为什么无法播放，可能是播放器UA，导致的。

**Comment by mengmo** [comment]
推荐使用 [mpv](https://mpv.io/)

**Comment by Gokou-Ruri** [comment]
补充一下：优酷视频无法调用potplayer播放已经发现原因了，似乎是因为优酷视频是分段的，而ykdl将分段视频地址转发给potplayer的时候是用空格分隔的。potplayer将分段地址识别成一整条了(没有对空格符做处理)，所以也就连接不上，提示无法播放。

**Comment by zhangn1985** [comment]
恩，感谢更新
