### ISSUE TITLE
下载合并解析存在问题

### ISSUE THREAD

**Issue by mengmo** [zhangn1985/ykdl#115]
在提交前，请确保您已经检查了以下内容!

- [x] 你确实可以在浏览器或移动端中观看视频，但不能使用`ykdl`下载。
- [x] 您的`ykdl`为最新版。
- [x] 您已经阅读并按 <https://github.com/zhangn1985/ykdl/wiki> 中的指引进行了操作。
- [x] 您的问题没有在 <https://github.com/zhangn1985/ykdl/issues> 报告，否则请在原有 issue 下报告。
- [x] 本问题确实关于`ykdl`，而不是其他项目。

请将错误输出粘贴在下面:

```
ykdl -O 奔跑吧20170421 -j 1 http://www.iqiyi.com/v_19rrav6eb0.html
site:                爱奇艺 (Iqiyi)
title:               奔跑吧_20170421期
artist:              None
streams:
    - format:        BD
      container:     flv
      video-profile: 1080p
    # download-with: ykdl --format=BD [URL]
Download: 奔跑吧20170421 part 0
 100%Download: 奔跑吧20170421 part 1
 100%Download: 奔跑吧20170421 part 2
 100%Download: 奔跑吧20170421 part 3
 100%Download: 奔跑吧20170421 part 4
 100%Download: 奔跑吧20170421 part 5
 100%Download: 奔跑吧20170421 part 6
 100%Download: 奔跑吧20170421 part 7
Download: 奔跑吧20170421 part 8
Download: 奔跑吧20170421 part 9
Download: 奔跑吧20170421 part 10
Download: 奔跑吧20170421 part 11
Download: 奔跑吧20170421 part 12
Download: 奔跑吧20170421 part 13
Download: 奔跑吧20170421 part 14
Download: 奔跑吧20170421 part 15
Download: 奔跑吧20170421 part 16
Download: 奔跑吧20170421 part 17
Download: 奔跑吧20170421 part 18
ykdl: Merging video 奔跑吧20170421 using ffmpeg:
[flv @ 00000000024d8440] Missing AMF_END_OF_OBJECT in AMF_DATA_TYPE_MIXEDARRAY, found 0
[flv @ 00000000024d8440] video stream discovered after head already parsed
[flv @ 00000000024d8440] audio stream discovered after head already parsed
[flv @ 00000000024d8440] Auto-inserting h264_mp4toannexb bitstream filter
Input #0, concat, from 'C:\Users\Administrator\tmpjqixcxx3.txt':
  Duration: N/A, start: 0.000000, bitrate: N/A
    Stream #0:0: Video: h264 (High), yuv420p(tv, bt709, progressive), 1920x1080, 25 fps, 25 tbr, 1k tbn, 50 tbc
    Stream #0:1: Audio: aac (HE-AAC), 44100 Hz, stereo, fltp
Output #0, flv, to '濂旇窇鍚?0170421.flv':
  Metadata:
    encoder         : Lavf57.56.101
    Stream #0:0: Video: h264 (High) ([7][0][0][0] / 0x0007), yuv420p(tv, bt709, progressive), 1920x1080, q=2-31, 25 fps, 25 tbr, 1k tbn, 1k tbc
    Stream #0:1: Audio: aac (HE-AAC) ([10][0][0][0] / 0x000A), 44100 Hz, stereo
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
[flv @ 00000000032f85a0] Missing AMF_END_OF_OBJECT in AMF_DATA_TYPE_MIXEDARRAY, found 0= 651x
[flv @ 00000000032f85a0] video stream discovered after head already parsed
[flv @ 00000000032f85a0] audio stream discovered after head already parsed
[aac @ 00000000032b7e00] element type mismatch 1 != 0
[flv @ 00000000032f85a0] Auto-inserting h264_mp4toannexb bitstream filter
[flv @ 00000000024e0640] Non-monotonous DTS in output stream 0:0; previous: 359920, current: 359913; changing to 359920. This may result in incorrect timestamps in the output file.
[flv @ 0000000003225fe0] Missing AMF_END_OF_OBJECT in AMF_DATA_TYPE_MIXEDARRAY, found 0d= 331x
[flv @ 0000000003225fe0] video stream discovered after head already parsed
[flv @ 0000000003225fe0] audio stream discovered after head already parsed
[aac @ 00000000032b82c0] element type mismatch 1 != 0
[flv @ 0000000003225fe0] Auto-inserting h264_mp4toannexb bitstream filter
[flv @ 0000000003225fe0] Missing AMF_END_OF_OBJECT in AMF_DATA_TYPE_MIXEDARRAY, found 0d= 256x
[flv @ 0000000003225fe0] video stream discovered after head already parsed
[flv @ 0000000003225fe0] audio stream discovered after head already parsed
[aac @ 00000000032b6ac0] element type mismatch 1 != 0
[flv @ 0000000003225fe0] Auto-inserting h264_mp4toannexb bitstream filter
[flv @ 00000000032f85a0] Missing AMF_END_OF_OBJECT in AMF_DATA_TYPE_MIXEDARRAY, found 0d= 242x
[flv @ 00000000032f85a0] video stream discovered after head already parsed
[flv @ 00000000032f85a0] audio stream discovered after head already parsed
[aac @ 00000000032b82c0] element type mismatch 1 != 0
[flv @ 00000000032f85a0] Auto-inserting h264_mp4toannexb bitstream filter
[flv @ 00000000032b4fa0] Missing AMF_END_OF_OBJECT in AMF_DATA_TYPE_MIXEDARRAY, found 0d= 223x
[flv @ 00000000032b4fa0] video stream discovered after head already parsed
[flv @ 00000000032b4fa0] audio stream discovered after head already parsed
[flv @ 00000000032b4fa0] Auto-inserting h264_mp4toannexb bitstream filter
[flv @ 00000000032f85a0] Missing AMF_END_OF_OBJECT in AMF_DATA_TYPE_MIXEDARRAY, found 0d= 225x
[flv @ 00000000032f85a0] video stream discovered after head already parsed
[flv @ 00000000032f85a0] audio stream discovered after head already parsed
[aac @ 00000000032b87a0] element type mismatch 1 != 0
[flv @ 00000000032f85a0] Auto-inserting h264_mp4toannexb bitstream filter
[concat @ 00000000024ccac0] Impossible to open '濂旇窇鍚?0170421_7_.flv'9.2kbits/s speed= 219x
C:\Users\Administrator\tmpjqixcxx3.txt: Invalid argument
frame=63009 fps=5471 q=-1.0 Lsize=  930582kB time=00:42:00.72 bitrate=3024.3kbits/s speed= 219x
video:909068kB audio:19381kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.229641%
Traceback (most recent call last):
  File "D:\PortableApps\Python\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\PortableApps\Python\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\PortableApps\Python\lib\site-packages\cykdl\__main__.py", line 161, in <module>
    main()
  File "D:\PortableApps\Python\lib\site-packages\cykdl\__main__.py", line 149, in main
    handle_videoinfo(info)
  File "D:\PortableApps\Python\lib\site-packages\cykdl\__main__.py", line 102, in handle_videoinfo
    download(urls, name, ext, live)
  File "D:\PortableApps\Python\lib\site-packages\cykdl\__main__.py", line 78, in download
    clean_slices(name, ext,lenth)
  File "D:\PortableApps\Python\lib\site-packages\cykdl\__main__.py", line 51, in clean_slices
    os.remove(file_name)
FileNotFoundError: [WinError 2] 系统找不到指定的文件。: '奔跑吧20170421_7_.flv'
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加:

> 因为现在网速不好，并行下载并不好使，所以只好挨个下载 segment
实际情况是只能下载到 part 6
估计是这儿 https://github.com/zhangn1985/ykdl/issues/69#issuecomment-285836232 没有完全弄好
我记得好像说过 https://github.com/zhangn1985/ykdl/issues/39#issuecomment-267856564
我看不如加入每下载 4 个 segments 就重新解析

**Comment by zhangn1985** [comment]
7之后都没下载下来。

**Comment by zhangn1985** [comment]
看出了一个问题，多线程任务提交后需要等待他们完成。

**Comment by zhangn1985** [comment]
现在就剩一个问题，FFMPEG合并失败，比如文件缺失，返回值仍然为0
