### ISSUE TITLE
iqiyi 不能解析

### ISSUE THREAD

**Issue by mengmo** [zhangn1985/ykdl#118]
在提交前，请确保您已经检查了以下内容!

- [x] 你确实可以在浏览器或移动端中观看视频，但不能使用`ykdl`下载。
- [x] 您的`ykdl`为最新版。
- [x] 您已经阅读并按 <https://github.com/zhangn1985/ykdl/wiki> 中的指引进行了操作。
- [x] 您的问题没有在 <https://github.com/zhangn1985/ykdl/issues> 报告，否则请在原有 issue 下报告。
- [x] 本问题确实关于`ykdl`，而不是其他项目。

请将错误输出粘贴在下面:

```
ykdl -i http://www.iqiyi.com/v_19rrb063r8.html
Traceback (most recent call last):
  File "D:\PortableApps\Python\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\PortableApps\Python\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\PortableApps\Python\lib\site-packages\cykdl\__main__.py", line 161, in <module>
    main()
  File "D:\PortableApps\Python\lib\site-packages\cykdl\__main__.py", line 139, in main
    info = parser(u)
  File "D:\PortableApps\Python\lib\site-packages\ykdl\extractor.py", line 21, in parser
    info = self.prepare()
  File "D:\PortableApps\Python\lib\site-packages\ykdl\extractors\iqiyi.py", line 75, in prepare
    stream = vps_data['data']['vp']['tkl'][0]
IndexError: string index out of range
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加:

> [您的内容]

**Comment by zhangn1985** [comment]
```
 ykdl -i http://www.iqiyi.com/v_19rrb063r8.html
site:                爱奇艺 (Iqiyi)
title:               奔跑吧_20170428期
artist:              None
streams:
    - format:        BD
      container:     flv
      video-profile: 1080p
    # download-with: ykdl --format=BD [URL]
Real urls:
http://122.72.121.207/videos/v0/20170429/1c/48/5cbd3f8318884e3ef590660123a7602b.f4v?key=04c18749f46fa6f2094495bf15c002fc4&dis_k=04467231ec69b0a02657cda05c231910b&dis_t=1493535851&dis_dz=CMNET-ShangHai&dis_st=42&src=iqiyi.com&uuid=b7c18bee-59058c6b-cd&qd_aid=668775400&qd_stert=0&qd_vipres=0&qd_vipdyn=0&qd_src=01012001010000000000&qd_ip=b7c18bee&qd_index=1&qd_vip=0&qd_k=1d6ec4f8cfc9d076b2df8e024764a060&qd_uid=0&qd_tm=1493535844818&qd_tvid=668775400
http://122.72.121.202/videos/v0/20170429/1c/48/604c1210b69515b2a278488a566da40c.f4v?key=0cf4a3fa33dd479d894495bf15c002fc4&dis_k=0e1b0cc82a0f00b2986836481a9c189da&dis_t=1493535851&dis_dz=CMNET-ShangHai&dis_st=42&src=iqiyi.com&uuid=b7c18bee-59058c6b-cd&qd_aid=668775400&qd_stert=190473&qd_vipres=0&qd_vipdyn=0&qd_src=01012001010000000000&qd_ip=b7c18bee&qd_index=2&qd_vip=0&qd_k=1d6ec4f8cfc9d076b2df8e024764a060&qd_uid=0&qd_tm=1493535844818&qd_tvid=668775400
```
works for me. please retry.

**Comment by mengmo** [comment]
嗯 确实

**Comment by mengmo** [comment]
情况好像是 Windows 10 Creator Update 后，命令提示符不需要再设置 http(s)_proxy，会直接调用 Windows 设置里的代理

**Comment by zhangn1985** [comment]
本来就不需要。
https://docs.python.org/3/library/urllib.request.html#urllib.request.ProxyHandler
`if no proxy environment variables are set, then in a Windows environment proxy settings are obtained from the registry’s Internet Settings section`

**Comment by mengmo** [comment]
但是之前不论使用 you-get 还是 youtube-dl 下载 youtube 的视频，只要不在命令提示符设置 http(s)_proxy，结果都是被重置

**Comment by mengmo** [comment]
即便 SS 设为全局代理

**Comment by mengmo** [comment]
要么是我记错了，不过现在手边也没法测试

**Comment by mengmo** [comment]
经测试，是我记错了
