### ISSUE TITLE
微博视频解析bug

### ISSUE THREAD

**Issue by demostars** [zhangn1985/ykdl#126]
最新版ykdl

http://weibo.com/tv/v/652abef3d8a43a5329fb304e9ab904ac?fid=1034:652abef3d8a43a5329fb304e9ab904ac 

```
site:                微博秒拍 (Weibo)
title:               视频集
artist:              None
streams:
    - format:        current
      container:     m3u8
    # download-with: ykdl --format=current [URL]
Download: 视频集 part 0
Download: 视频集 part 1
 100%Download: 视频集 part 2
 100%Download: 视频集 part 3
  34%Download: 视频集 part 4
 100%Download: 视频集 part 5
 100%Download: 视频集 part 6
  38%Download: 视频集 part 7
  54%Download: 视频集 part 8
  12%Download: 视频集 part 9
 100%Download: 视频集 part 10
  47%Download: 视频集 part 11
 100%Download: 视频集 part 12
 100%Download: 视频集 part 13
 100%Download: 视频集 part 14
  99%Download: 视频集 part 15
 100%Download: 视频集 part 16
 100%Download: 视频集 part 17
  14%Download: 视频集 part 18
 100%Download: 视频集 part 19
 100%Download: 视频集 part 20
  15%Download: 视频集 part 21
 100%Download: 视频集 part 22
 100%Download: 视频集 part 23
  35%Download: 视频集 part 24
 100%ykdl: Merging video 视频集 using ffmpeg:
Traceback (most recent call last):
  File "C:\Python36\lib\site-packages\bottle.py", line 862, in _handle
    return route.call(**args)
  File "C:\Python36\lib\site-packages\bottle.py", line 1740, in wrapper
    rv = callback(*a, **ka)
  File "videos.py", line 33, in hello
    wbd.main()
  File "D:\dev\Py\cykdl.py", line 158, in main
    handle_videoinfo(info)
  File "D:\dev\Py\cykdl.py", line 106, in handle_videoinfo
    download(urls, name, ext, live)
  File "D:\dev\Py\cykdl.py", line 80, in download
    ret = launch_ffmpeg(name, ext,lenth)
  File "C:\Python36\lib\site-packages\ykdl\util\wrap.py", line 27, in launch_ffmpeg
    return subprocess.call(cmd)
  File "C:\Python36\lib\subprocess.py", line 267, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Python36\lib\subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "C:\Python36\lib\subprocess.py", line 990, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] 系统找不到指定的文件。
C:\Python36\lib\re.py:301: DeprecationWarning: Flags not at the start of the expression ((?m)[urbURB]?(?:''( (truncated)
  p = sre_compile.compile(pattern, flags)
C:\Python36\lib\sre_parse.py:763: DeprecationWarning: Flags not at the start of the expression \{\{((?:((?m)[urbURB (truncated)
  p = _parse_sub(source, state, sub_verbose)
```

**Comment by rosynirvana** [comment]
这个要用ffmpeg，是不是没装

**Comment by demostars** [comment]
@rosynirvana 确实是，后来发现了。。然后装了。。确实没这个问题了。

不好意思。。
