### ISSUE TITLE
腾讯限速而且下载一点直接关连接

### ISSUE THREAD

**Issue by cok3307788** [zhangn1985/ykdl#134]
请将错误输出粘贴在下面:
C:\Users\pc>ykdl -o e:/1 https://v.qq.com/x/cover/iumrr9a9vl46vbl.html
site:                腾讯视频 (QQ)
title:               俄罗斯的火焰之心：堪察加半岛
artist:              None
streams:
    - format:        HD
      container:     mp4
      video-profile: 高清mp4
      size:          172.3 MiB (180639812 bytes)
    # download-with: ykdl --format=HD [URL]
Download: 俄罗斯的火焰之心：堪察加半岛_HD
  16%Traceback (most recent call last):
  File "d:\program files\python\python36\lib\runpy.py", line 193, in _run_module
_as_main
    "__main__", mod_spec)
  File "d:\program files\python\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Program Files\Python\Python36\Scripts\ykdl.exe\__main__.py", line 9,
in <module>
  File "d:\program files\python\python36\lib\site-packages\cykdl\__main__.py", l
ine 159, in main
    handle_videoinfo(info)
  File "d:\program files\python\python36\lib\site-packages\cykdl\__main__.py", l
ine 107, in handle_videoinfo
    download(urls, name, ext, live)
  File "d:\program files\python\python36\lib\site-packages\cykdl\__main__.py", l
ine 77, in download
    if save_urls(urls, name, ext, jobs = args.jobs):
  File "d:\program files\python\python36\lib\site-packages\ykdl\util\download.py
", line 81, in save_urls
    save_url(urls[0], name, ext, status)
  File "d:\program files\python\python36\lib\site-packages\ykdl\util\download.py
", line 66, in save_url
    block = response.read(bs)
  File "d:\program files\python\python36\lib\http\client.py", line 449, in read
    n = self.readinto(b)
  File "d:\program files\python\python36\lib\http\client.py", line 493, in readi
nto
    n = self.fp.readinto(b)
  File "d:\program files\python\python36\lib\socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。

--------------------------------------------------------------------------------

[在这里粘贴完整debug日志]
C:\Users\pc>ykdl --debug -o e:/1 https://v.qq.com/x/cover/iumrr9a9vl46vbl.html
DEBUG:common:video_host> v.qq.com
DEBUG:common:short_name> qq
DEBUG:html:get_content> URL: https://v.qq.com/x/cover/iumrr9a9vl46vbl.html
DEBUG:html:get_content> Charset: utf-8
DEBUG:html:get_content> URL: http://vv.video.qq.com/getinfo
DEBUG:html:get_content> URL: http://vv.video.qq.com/getkey
DEBUG:html:get_content> URL: http://vv.video.qq.com/getinfo
DEBUG:html:get_content> URL: http://vv.video.qq.com/getkey
DEBUG:html:get_content> URL: http://vv.video.qq.com/getinfo
DEBUG:html:get_content> URL: http://vv.video.qq.com/getkey
DEBUG:html:get_content> URL: http://vv.video.qq.com/getinfo
DEBUG:html:get_content> URL: http://vv.video.qq.com/getkey
site:                腾讯视频 (QQ)
title:               俄罗斯的火焰之心：堪察加半岛
artist:              None
streams:
    - format:        HD
      container:     mp4
      video-profile: 高清mp4
      size:          172.3 MiB (180639812 bytes)
    # download-with: ykdl --format=HD [URL]
Download: 俄罗斯的火焰之心：堪察加半岛_HD
  37%Traceback (most recent call last):
  File "d:\program files\python\python36\lib\runpy.py", line 193, in _run_module
_as_main
    "__main__", mod_spec)
  File "d:\program files\python\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Program Files\Python\Python36\Scripts\ykdl.exe\__main__.py", line 9,
in <module>
  File "d:\program files\python\python36\lib\site-packages\cykdl\__main__.py", l
ine 159, in main
    handle_videoinfo(info)
  File "d:\program files\python\python36\lib\site-packages\cykdl\__main__.py", l
ine 107, in handle_videoinfo
    download(urls, name, ext, live)
  File "d:\program files\python\python36\lib\site-packages\cykdl\__main__.py", l
ine 77, in download
    if save_urls(urls, name, ext, jobs = args.jobs):
  File "d:\program files\python\python36\lib\site-packages\ykdl\util\download.py
", line 81, in save_urls
    save_url(urls[0], name, ext, status)
  File "d:\program files\python\python36\lib\site-packages\ykdl\util\download.py
", line 66, in save_url
    block = response.read(bs)
  File "d:\program files\python\python36\lib\http\client.py", line 449, in read
    n = self.readinto(b)
  File "d:\program files\python\python36\lib\http\client.py", line 493, in readi
nto
    n = self.fp.readinto(b)
  File "d:\program files\python\python36\lib\socket.py", line 586, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

**Comment by zhangn1985** [comment]
这个链接我测试下来在300k～1.2M的速度，不错了，而且限速，无解。

**Comment by cok3307788** [comment]
好吧，其实最麻烦的还是端口超时，强行掐断下载

**Comment by rosynirvana** [comment]
试了一下10901的速度关键在于```_qv_rmt```和```_qv_rmt_2```上

**Comment by rosynirvana** [comment]
10901除了guid之外都扒出来了
guid确实是随机串，但是需要以某种方法注册
