### ISSUE TITLE
iqiyi某些视频无法解析

### ISSUE THREAD

**Issue by jyuan15** [zhangn1985/ykdl#150]
刚升级1.5.0版，发现某些iqiyi视频不能解析。

如果说是vip视频，但1.4.11版是可以解析vip视频的，而且会有“vip视频”警告信息，只是不能下载或只能下载前几分钟。

错误信息
C:\Users\Administrator>ykdl -i http://www.iqiyi.com/v_19rr79jq6c.html
Traceback (most recent call last):
  File "C:\Python34\Scripts\ykdl-script.py", line 9, in <module>
    load_entry_point('ykdl==1.5.0', 'console_scripts', 'ykdl')()
  File "C:\Python34\lib\site-packages\cykdl\__main__.py", line 149, in main
    info = parser(u)
  File "C:\Python34\lib\site-packages\ykdl\extractor.py", line 24, in parser
    info = self.prepare()
  File "C:\Python34\lib\site-packages\ykdl\extractors\iqiyi.py", line 83, in pre
pare
    json_data=json.loads(get_content(url))
  File "C:\Python34\lib\site-packages\ykdl\util\html.py", line 65, in get_conten
t
    response = urlopen(req)
  File "C:\Python34\lib\urllib\request.py", line 153, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Python34\lib\urllib\request.py", line 461, in open
    response = meth(req, response)
  File "C:\Python34\lib\urllib\request.py", line 574, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Python34\lib\urllib\request.py", line 499, in error
    return self._call_chain(*args)
  File "C:\Python34\lib\urllib\request.py", line 433, in _call_chain
    result = func(*args)
  File "C:\Python34\lib\urllib\request.py", line 582, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 405: Not Allowed

**Comment by mengmo** [comment]
应该不是 ykdl 版本的问题，ykdl 1.4.11 的输出
```
ykdl -i http://www.iqiyi.com/v_19rr79jq6c.html
Traceback (most recent call last):
  File "yk_dl.py", line 169, in <module>
  File "yk_dl.py", line 147, in main
  File "site-packages\ykdl\extractor.py", line 24, in parser
  File "site-packages\ykdl\extractors\iqiyi.py", line 83, in prepare
  File "site-packages\ykdl\util\html.py", line 65, in get_content
  File "urllib\request.py", line 223, in urlopen
  File "urllib\request.py", line 532, in open
  File "urllib\request.py", line 642, in http_response
  File "urllib\request.py", line 570, in error
  File "urllib\request.py", line 504, in _call_chain
  File "urllib\request.py", line 650, in http_error_default
urllib.error.HTTPError: HTTP Error 405: Not Allowed
Failed to execute script yk_dl
```

**Comment by jyuan15** [comment]
> mengmo commented 7 minutes ago
> 
> 应该不是 ykdl 版本的问题，ykdl 1.4.11 的输出

you-get又可以解析出来，所以觉得也不是网站原因

**Comment by rosynirvana** [comment]
用的不是一个接口

**Comment by zhangn1985** [comment]
关掉的原因是 vip 视频
