### ISSUE TITLE
爱奇艺个别地址利用1.1.3.5版本可以解析，但利用最新版本1.5.0解析不了

### ISSUE THREAD

**Issue by snoopytl** [zhangn1985/ykdl#154]
爱奇艺的这个地址http://www.iqiyi.com/v_19rr7hbk08.html?list=19rrl76ejy

利用1.5.0解析不出来，但用1.1.3.5可以解析出来
C:\Users\tian>ykdl -i http://www.iqiyi.com/v_19rr7hbk08.html?list=19rrl76ejy
Traceback (most recent call last):
  File "C:\python3.6.1\Scripts\ykdl-script.py", line 11, in <module>
    load_entry_point('ykdl==1.5.0', 'console_scripts', 'ykdl')()
  File "C:\python3.6.1\lib\site-packages\ykdl-1.5.0-py3.6.egg\cykdl\__main__.py", line 149, in main
  File "C:\python3.6.1\lib\site-packages\ykdl-1.5.0-py3.6.egg\ykdl\extractor.py", line 24, in parser
  File "C:\python3.6.1\lib\site-packages\ykdl-1.5.0-py3.6.egg\ykdl\extractors\iqiyi.py", line 83, in prepare
  File "C:\python3.6.1\lib\site-packages\ykdl-1.5.0-py3.6.egg\ykdl\util\html.py", line 65, in get_content
  File "C:\python3.6.1\lib\urllib\request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "C:\python3.6.1\lib\urllib\request.py", line 532, in open
    response = meth(req, response)
  File "C:\python3.6.1\lib\urllib\request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\python3.6.1\lib\urllib\request.py", line 570, in error
    return self._call_chain(*args)
  File "C:\python3.6.1\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "C:\python3.6.1\lib\urllib\request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 405: Not Allowed

最新版本是不是有什么问题，而且降一个版本也同样无法解析，我利用1.1.3.5版本解析后，下载到一半被强制关闭了，日志如下，请问该怎么解决？
Traceback (most recent call last):
  File "yk_dl.py", line 148, in <module>
  File "yk_dl.py", line 136, in main
  File "yk_dl.py", line 90, in handle_videoinfo
  File "yk_dl.py", line 69, in download
  File "site-packages\ykdl\util\download.py", line 61, in save_urls
  File "site-packages\ykdl\util\download.py", line 28, in save_url
  File "urllib\request.py", line 161, in urlopen
  File "urllib\request.py", line 464, in open
  File "urllib\request.py", line 482, in _open
  File "urllib\request.py", line 442, in _call_chain
  File "urllib\request.py", line 1211, in http_open
  File "urllib\request.py", line 1186, in do_open
  File "http\client.py", line 1227, in getresponse
  File "http\client.py", line 386, in begin
  File "http\client.py", line 348, in _read_status
  File "socket.py", line 378, in readinto
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。
Failed to execute script yk_dl

**Comment by rosynirvana** [comment]
#150
