### ISSUE TITLE
MAC OS X ykdk youku 下使用 -l 出错

### ISSUE THREAD

**Issue by flfq** [zhangn1985/ykdl#158]
```
ykdl -l http://v.youku.com/v_show/id_XMjg4MDAyNDczMg==.html?from=y1.2-2.2
Traceback (most recent call last):
  File "/usr/local/bin/ykdl", line 11, in <module>
    load_entry_point('ykdl==1.5.0', 'console_scripts', 'ykdl')()
  File "/Library/Python/2.7/site-packages/cykdl/__main__.py", line 152, in main
    for i in info:
  File "/Library/Python/2.7/site-packages/ykdl/extractor.py", line 31, in parser_list
    raise NotImplementedError('playlist not support for {} with url: {}'.format(self.name, self.url))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-1: ordinal not in range(128)

```
有字符串解码的问题

**Comment by flfq** [comment]
extractor.py
增加
'''
import sys
try:
    reload(sys)
    sys.setdefaultencoding("utf-8")
except:
    pass
'''
就可以了

**Comment by zhangn1985** [comment]
OSX无人权。自己改控制台的默认编码。setdefaultencoding不同用。

**Comment by zhangn1985** [comment]
不支持优酷播放列表。

**Comment by zhangn1985** [comment]
```
Python 3.5.3 (default, Jan 19 2017, 14:11:04) 
[GCC 6.3.0 20170118] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> reload(sys)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'reload' is not defined
```

**Comment by rosynirvana** [comment]
字符串前面加个u

```diff
diff --git a/ykdl/extractor.py b/ykdl/extractor.py
index b4ebd5f..38e6bb1 100644
--- a/ykdl/extractor.py
+++ b/ykdl/extractor.py
@@ -28,7 +28,7 @@ class VideoExtractor():
         self.url = url
         video_list = self.prepare_list()
         if not video_list:
-            raise NotImplementedError('playlist not support for {} with url: {}'.format(self.name, self.url))
+            raise NotImplementedError(u'playlist not support for {} with url: {}'.format(self.name, self.url))
         for video in video_list:
             yield self.parser(video)
```

```
$ python cykdl/__main__.py -l http://v.youku.com/v_show/id_XMjg4MDAyNDczMg==.html?from=y1.2-2.2
WARNING:downloader:failed to import ThreadPoolExecutor!
WARNING:downloader:multithread download disabled!
WARNING:downloader:please install concurrent.futures from https://github.com/agronholm/pythonfutures !
ERROR:YKDL:playlist not support for 优酷 (Youku) with url: http://v.youku.com/v_show/id_XMjg4MDAyNDczMg==.html?from=y1.2-2.2
```

```
$ python3 cykdl/__main__.py -l http://v.youku.com/v_show/id_XMjg4MDAyNDczMg==.html?from=y1.2-2.2
ERROR:YKDL:playlist not support for 优酷 (Youku) with url: http://v.youku.com/v_show/id_XMjg4MDAyNDczMg==.html?from=y1.2-2.2
```
