### ISSUE TITLE
iqiyi下载出错

### ISSUE THREAD

**Issue by damoguyanzero** [zhangn1985/ykdl#16]
这两天下载iqiyi视频时会报错。
输入：ykdl http://www.iqiyi.com/v_19rrlyanb8.html
返回的是：
Traceback (most recent call last):
  File "c:\program files (x86)\python35\lib\runpy.py", line 184, in _run_module_
as_main
    "__main__", mod_spec)
  File "c:\program files (x86)\python35\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Program Files (x86)\Python35\Scripts\ykdl.exe\__main__.py", line 9, i
n <module>
  File "c:\program files (x86)\python35\lib\site-packages\ykdl\__main__.py", lin
e 119, in main
    info = parser(u)
  File "c:\program files (x86)\python35\lib\site-packages\ykdl\extractor.py", li
ne 19, in parser
    info = self.prepare()
  File "c:\program files (x86)\python35\lib\site-packages\ykdl\extractors\iqiyi.
py", line 78, in prepare
    assert data['bossStatus'] == 0, "%s: can't download VIP videos!" % self.name

KeyError: 'bossStatus'

**Comment by zhangn1985** [comment]
@damoguyanzero 请更新到最新
