### ISSUE TITLE
douyu失效

### ISSUE THREAD

**Issue by jyuan15** [zhangn1985/ykdl#162]
上午都还能下载，现在就不行了

C:\Users\Administrator>ykdl --debug https://www.douyu.com/431565
DEBUG:common:video_host> www.douyu.com
DEBUG:common:short_name> douyu
DEBUG:html:get_content> URL: https://www.douyu.com/431565
DEBUG:html:get_content> Charset: UTF-8
DEBUG:html:get_content> URL: https://www.douyu.com/lapi/live/getPlay/431565
Traceback (most recent call last):
  File "C:\Python34\Scripts\ykdl-script.py", line 9, in <module>
    load_entry_point('ykdl==1.5.0', 'console_scripts', 'ykdl')()
  File "C:\Python34\lib\site-packages\cykdl\__main__.py", line 149, in main
    info = parser(u)
  File "C:\Python34\lib\site-packages\ykdl\extractor.py", line 24, in parser
    info = self.prepare()
  File "C:\Python34\lib\site-packages\ykdl\extractors\douyu\live.py", line 52, i
n prepare
    html_content = get_content(api_url, data=compact_bytes(form, 'utf-8'))
  File "C:\Python34\lib\site-packages\ykdl\util\html.py", line 65, in get_conten
t
    response = urlopen(req)
  File "C:\Python34\lib\urllib\request.py", line 153, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Python34\lib\urllib\request.py", line 461, in open
    response = meth(req, response)
  File "C:\Python34\lib\urllib\request.py", line 574, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Python34\lib\urllib\request.py", line 499, in error
    return self._call_chain(*args)
  File "C:\Python34\lib\urllib\request.py", line 433, in _call_chain
    result = func(*args)
  File "C:\Python34\lib\urllib\request.py", line 582, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 500: Internal Server Error

**Comment by lki2019** [comment]
@jyuan15 你之前是用什么命令下载的啊

**Comment by jyuan15** [comment]
@lki2019 和下载其他视频的一样

**Comment by zhangn1985** [comment]
的确失效了

**Comment by jindaxia** [comment]
失效了 斗鱼的HTML5播放器也不能用了

**Comment by rosynirvana** [comment]
从静态分析的结果来看是做2次dy_block，1次AES，1次patched_md5，每个block的结果都要。过一次dy_block。然后根据rid做一个```EncodeFlashMain::EncodeDataC(unsigned char, unsigned char*, unsigned short)```，这个class要先计算出80bytes的bss segment，然后选择其中4bytes来用另一组函数做encode，这组函数一共50个，最后拿到的数据hexlify。

除非能找出这个encode_datac是什么公版的加密 or 混淆算法，不然现在这种重新实现一遍的想法大概不会好使

当然，最好是我搞错了

**Comment by zhangn1985** [comment]
听起来就不是那么容易的事情。

**Comment by rosynirvana** [comment]
后来的挑战者建议从```libdanmu.so```下手，安卓平台上的分析手段发展了好几年可能要容易点，缺点就是函数名strip掉了

**Comment by jindaxia** [comment]
https://gist.github.com/ERioK/d73f76dbb0334618ff905f1bf3363401
