### ISSUE TITLE
优酷 解析出现问题

### ISSUE THREAD

**Issue by mengmo** [zhangn1985/ykdl#17]
```
python -m ykdl -i http://v.youku.com/v_show/id_XMTQwNzg2NTQ1Mg==.html
Traceback (most recent call last):
  File "D:\PortableApps\Python\lib\site-packages\ykdl\extractors\youku.py", line 42, in setup
    meta = json.loads(get_content(api_url))
  File "D:\PortableApps\Python\lib\site-packages\ykdl\util\html.py", line 62, in get_content
    response = urlopen(req)
  File "D:\PortableApps\Python\lib\urllib\request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "D:\PortableApps\Python\lib\urllib\request.py", line 472, in open
    response = meth(req, response)
  File "D:\PortableApps\Python\lib\urllib\request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "D:\PortableApps\Python\lib\urllib\request.py", line 510, in error
    return self._call_chain(*args)
  File "D:\PortableApps\Python\lib\urllib\request.py", line 444, in _call_chain
    result = func(*args)
  File "D:\PortableApps\Python\lib\urllib\request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 500: Internal Privoxy Error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\PortableApps\Python\lib\runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\PortableApps\Python\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\PortableApps\Python\lib\site-packages\ykdl\__main__.py", line 140, in <module>
    main()
  File "D:\PortableApps\Python\lib\site-packages\ykdl\__main__.py", line 119, in main
    info = parser(u)
  File "D:\PortableApps\Python\lib\site-packages\ykdl\extractor.py", line 19, in parser
    info = self.prepare()
  File "D:\PortableApps\Python\lib\site-packages\ykdl\extractors\youkubase.py", line 32, in prepare
    self.setup(info)
  File "D:\PortableApps\Python\lib\site-packages\ykdl\extractors\youku.py", line 48, in setup
    if 'error' in data1:
UnboundLocalError: local variable 'data1' referenced before assignment
```

**Comment by zhangn1985** [comment]
```
 ykdl -i http://v.youku.com/v_show/id_XMTQwNzg2NTQ1Mg==.html
site:                优酷 (Youku)
title:               兜教授 数码宝贝 网络侦探 实况攻略 第二集 灵魂出窍.mp4
artist:              None
streams:
    - format:        BD
      container:     flv
      video-profile: 1080p
      size:          701.7 MiB (735788474 bytes)
    # download-with: ykdl --format=BD [URL]
Real urls:
http://223.111.10.13/youku/69731DB8DFC4D822D1B317581F/030080130056675246294519640221220BB9ED-BAC3-6B4D-499B-713D9088F837.flv
http://183.213.28.142/youku/6571F2936084A83E8D1E983B65/030080130156675246294519640221220BB9ED-BAC3-6B4D-499B-713D9088F837.flv
http://112.25.50.41/youku/67731DB877146787982FB25A3/030080130256675246294519640221220BB9ED-BAC3-6B4D-499B-713D9088F837.flv
http://112.25.51.139/youku/6773816FCE64277FC180E660C/030080130356675246294519640221220BB9ED-BAC3-6B4D-499B-713D9088F837.flv
http://112.25.51.112/youku/6974AC945E83C773F62524226/030080130456675246294519640221220BB9ED-BAC3-6B4D-499B-713D9088F837.flv
http://223.111.10.109/youku/6573816F6FC33816E8596A6DFD/030080130556675246294519640221220BB9ED-BAC3-6B4D-499B-713D9088F837.flv
http://223.113.15.42/youku/6975740295038819A1CD5C5104/030080130656675246294519640221220BB9ED-BAC3-6B4D-499B-713D9088F837.flv
http://223.113.15.109/youku/6775104B9C8338174D536A5180/030080130756675246294519640221220BB9ED-BAC3-6B4D-499B-713D9088F837.flv
http://112.25.51.175/youku/677574029904B791729BB5F27/030080130856675246294519640221220BB9ED-BAC3-6B4D-499B-713D9088F837.flv
http://112.25.50.45/youku/6775D7B97654C79362B5F2BCC/030080130956675246294519640221220BB9ED-BAC3-6B4D-499B-713D9088F837.flv
http://223.113.15.115/youku/67763B70E354882116C4E93D33/030080130A56675246294519640221220BB9ED-BAC3-6B4D-499B-713D9088F837.flv
http://183.213.29.105/youku/67769F2777640835FBC08449C1/030080130B56675246294519640221220BB9ED-BAC3-6B4D-499B-713D9088F837.flv
http://183.213.28.140/youku/65763B70D003582C8E9AA52999/030080130C56675246294519640221220BB9ED-BAC3-6B4D-499B-713D9088F837.flv
http://183.213.28.103/youku/677766957DC41836D6DC78453E/030080130D56675246294519640221220BB9ED-BAC3-6B4D-499B-713D9088F837.flv
http://112.25.37.54/youku/657702DE87936767FC16E6C75/030080130E56675246294519640221220BB9ED-BAC3-6B4D-499B-713D9088F837.flv
http://183.213.29.106/youku/6978F571CC832829FCB25F273D/030080130F56675246294519640221220BB9ED-BAC3-6B4D-499B-713D9088F837.flv
http://112.25.37.45/youku/69795928AA03075C366425F9A/030080131056675246294519640221220BB9ED-BAC3-6B4D-499B-713D9088F837.flv
http://183.213.28.131/youku/6778F571D5B3682D69F45F314B/030080131156675246294519640221220BB9ED-BAC3-6B4D-499B-713D9088F837.flv
http://183.213.29.108/youku/697A2096D2A4983DB2016F49D9/030080131256675246294519640221220BB9ED-BAC3-6B4D-499B-713D9088F837.flv
    - format:        TD
      container:     flv
      video-profile: 超清
      size:          361.0 MiB (378552431 bytes)
    # download-with: ykdl --format=TD [URL]
Real urls:
http://183.213.29.24/youku/65718EE0E853F8352050722BE0/0300010D00566749F0294519640221220BB9ED-BAC3-6B4D-499B-713D9088F837.flv
http://183.213.28.212/youku/69738178B1F4C84043EA4C2AA0/0300010D01566749F0294519640221220BB9ED-BAC3-6B4D-499B-713D9088F837.flv
http://183.213.29.19/youku/67731DC0596438388DBFB42917/0300010D02566749F0294519640221220BB9ED-BAC3-6B4D-499B-713D9088F837.flv
http://183.213.28.105/youku/6572BA0890A4C84043CAF34C95/0300010D03566749F0294519640221220BB9ED-BAC3-6B4D-499B-713D9088F837.flv
http://183.213.28.109/youku/6773E530B1D4483968F0603335/0300010D04566749F0294519640221220BB9ED-BAC3-6B4D-499B-713D9088F837.flv
http://112.25.51.115/youku/677448E8EB73776A2268D5828/0300010D05566749F0294519640221220BB9ED-BAC3-6B4D-499B-713D9088F837.flv
http://223.113.15.76/youku/6573E530A793B81B07BFAF3819/0300010D06566749F0294519640221220BB9ED-BAC3-6B4D-499B-713D9088F837.flv
http://112.25.37.42/youku/657448E8A13477895667569D0/0300010D07566749F0294519640221220BB9ED-BAC3-6B4D-499B-713D9088F837.flv
http://183.213.29.73/youku/69763B80B0E4983DB1F79726F4/0300010D08566749F0294519640221220BB9ED-BAC3-6B4D-499B-713D9088F837.flv
http://183.213.28.211/youku/69769F38D9232829FC95783715/0300010D09566749F0294519640221220BB9ED-BAC3-6B4D-499B-713D9088F837.flv
http://183.213.28.11/youku/67763B807C741836D6C5783078/0300010D0A566749F0294519640221220BB9ED-BAC3-6B4D-499B-713D9088F837.flv
http://183.213.29.72/youku/6575D7C85713982FFC322161E8/0300010D0B566749F0294519640221220BB9ED-BAC3-6B4D-499B-713D9088F837.flv
http://223.113.15.25/youku/677702F05773B81B07B421232F/0300010D0C566749F0294519640221220BB9ED-BAC3-6B4D-499B-713D9088F837.flv
    - format:        HD
      container:     mp4
      video-profile: 高清
      size:          165.3 MiB (173357969 bytes)
    # download-with: ykdl --format=HD [URL]
Real urls:
http://183.213.29.202/youku/67725650DAC438388DEEE2675D/030008070056674691294519640221220BB9ED-BAC3-6B4D-499B-713D9088F837.mp4
http://183.213.28.79/youku/697381788063882F20A04F4EAC/030008070156674691294519640221220BB9ED-BAC3-6B4D-499B-713D9088F837.mp4
http://183.213.29.53/youku/67731DC0DF03382AD8047A6C54/030008070256674691294519640221220BB9ED-BAC3-6B4D-499B-713D9088F837.mp4
http://223.113.15.18/youku/697448E84BA3A81A90646E2A41/030008070356674691294519640221220BB9ED-BAC3-6B4D-499B-713D9088F837.mp4
http://223.113.15.115/youku/65731DC0D763981A192B892FD8/030008070456674691294519640221220BB9ED-BAC3-6B4D-499B-713D9088F837.mp4
http://183.213.28.136/youku/657381787803682D69F5685D2A/030008070556674691294519640221220BB9ED-BAC3-6B4D-499B-713D9088F837.mp4
http://223.113.15.24/youku/69757410D3B498218DF9CF45CB/030008070656674691294519640221220BB9ED-BAC3-6B4D-499B-713D9088F837.mp4
    - format:        SD
      container:     flv
      video-profile: 标清
      size:          86.3 MiB (90444023 bytes)
    # download-with: ykdl --format=SD [URL]
Real urls:
http://112.25.51.176/youku/69731DC0D443976E118E13311/0300020700566747B7294519640221220BB9ED-BAC3-6B4D-499B-713D9088F837.flv
http://112.25.50.15/youku/697381784BF3075C5C3C03E26/0300020701566747B7294519640221220BB9ED-BAC3-6B4D-499B-713D9088F837.flv
http://183.213.29.101/youku/657256509D93382AD80DDA34BA/0300020702566747B7294519640221220BB9ED-BAC3-6B4D-499B-713D9088F837.flv
http://183.213.29.51/youku/677381786C23782E45750D63F7/0300020703566747B7294519640221220BB9ED-BAC3-6B4D-499B-713D9088F837.flv
http://223.111.10.55/youku/6974ACA08183F81C67BDF4394D/0300020704566747B7294519640221220BB9ED-BAC3-6B4D-499B-713D9088F837.flv
http://223.113.15.109/youku/657381787D33A81A9078B13F39/0300020705566747B7294519640221220BB9ED-BAC3-6B4D-499B-713D9088F837.flv
http://112.25.51.131/youku/6573E53075A4C79368F914749/0300020706566747B7294519640221220BB9ED-BAC3-6B4D-499B-713D9088F837.flv

```

**Comment by mengmo** [comment]
今天试了下，又能用了。怪哉！
估计`youku`抽风了

**Comment by zhangn1985** [comment]
有这个可能～～
