### ISSUE TITLE
B站，部分视频无法解析

### ISSUE THREAD

**Issue by mengmo** [zhangn1985/ykdl#186]
在提交前，请确保您已经检查了以下内容!

- [x] 你确实可以在浏览器或移动端中观看视频，但不能使用`ykdl`下载。
- [x] 您的`ykdl`为最新版。
- [x] 您已经阅读并按 <https://github.com/zhangn1985/ykdl/wiki> 中的指引进行了操作。
- [x] 您的问题没有在 <https://github.com/zhangn1985/ykdl/issues> 报告，否则请在原有 issue 下报告。
- [x] 本问题确实关于`ykdl`，而不是其他项目。

请将错误输出粘贴在下面:

```
ykdl -i http://bangumi.bilibili.com/anime/6314/play#113335
Traceback (most recent call last):
  File "D:\PortableApps\Python\lib\runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\PortableApps\Python\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\PortableApps\Python\lib\site-packages\cykdl\__main__.py", line 183, in <module>
    main()
  File "D:\PortableApps\Python\lib\site-packages\cykdl\__main__.py", line 161, in main
    info = parser(u)
  File "D:\PortableApps\Python\lib\site-packages\ykdl\extractor.py", line 24, in parser
    info = self.prepare()
  File "D:\PortableApps\Python\lib\site-packages\ykdl\extractors\bilibili\video.py", line 61, in prepare
    urls, size, ext = parse_cid_playurl(html)
  File "D:\PortableApps\Python\lib\site-packages\ykdl\extractors\bilibili\video.py", line 22, in parse_cid_playurl
    ext = doc.getElementsByTagName('format')[0].firstChild.nodeValue
IndexError: list index out of range
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加:

> 试了好几个，只发现这一个有问题

**Comment by mengmo** [comment]
又发现几个有问题的
```
ykdl -i http://bangumi.bilibili.com/anime/6345/play#114047
Traceback (most recent call last):
  File "D:\PortableApps\Python\lib\runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\PortableApps\Python\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\PortableApps\Python\lib\site-packages\cykdl\__main__.py", line 183, in <module>
    main()
  File "D:\PortableApps\Python\lib\site-packages\cykdl\__main__.py", line 161, in main
    info = parser(u)
  File "D:\PortableApps\Python\lib\site-packages\ykdl\extractor.py", line 24, in parser
    info = self.prepare()
  File "D:\PortableApps\Python\lib\site-packages\ykdl\extractors\bilibili\video.py", line 61, in prepare
    urls, size, ext = parse_cid_playurl(html)
  File "D:\PortableApps\Python\lib\site-packages\ykdl\extractors\bilibili\video.py", line 22, in parse_cid_playurl
    ext = doc.getElementsByTagName('format')[0].firstChild.nodeValue
IndexError: list index out of range
```
```
ykdl -i http://bangumi.bilibili.com/anime/6345/play#114055
Traceback (most recent call last):
  File "D:\PortableApps\Python\lib\runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\PortableApps\Python\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\PortableApps\Python\lib\site-packages\cykdl\__main__.py", line 183, in <module>
    main()
  File "D:\PortableApps\Python\lib\site-packages\cykdl\__main__.py", line 161, in main
    info = parser(u)
  File "D:\PortableApps\Python\lib\site-packages\ykdl\extractor.py", line 24, in parser
    info = self.prepare()
  File "D:\PortableApps\Python\lib\site-packages\ykdl\extractors\bilibili\video.py", line 61, in prepare
    urls, size, ext = parse_cid_playurl(html)
  File "D:\PortableApps\Python\lib\site-packages\ykdl\extractors\bilibili\video.py", line 22, in parse_cid_playurl
    ext = doc.getElementsByTagName('format')[0].firstChild.nodeValue
IndexError: list index out of range
```
```
ykdl -i http://bangumi.bilibili.com/anime/6345/play#114056
Traceback (most recent call last):
  File "D:\PortableApps\Python\lib\runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\PortableApps\Python\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\PortableApps\Python\lib\site-packages\cykdl\__main__.py", line 183, in <module>
    main()
  File "D:\PortableApps\Python\lib\site-packages\cykdl\__main__.py", line 161, in main
    info = parser(u)
  File "D:\PortableApps\Python\lib\site-packages\ykdl\extractor.py", line 24, in parser
    info = self.prepare()
  File "D:\PortableApps\Python\lib\site-packages\ykdl\extractors\bilibili\video.py", line 61, in prepare
    urls, size, ext = parse_cid_playurl(html)
  File "D:\PortableApps\Python\lib\site-packages\ykdl\extractors\bilibili\video.py", line 22, in parse_cid_playurl
    ext = doc.getElementsByTagName('format')[0].firstChild.nodeValue
IndexError: list index out of range
```

**Comment by rosynirvana** [comment]
可以考虑给bangumi另写一个extractor了

**Comment by redstoneleo** [comment]
```
C:\Users\i>ykdl -i https://www.bilibili.com/watchlater/#/av2679094/p1
Traceback (most recent call last):
  File "C:\Users\i\AppData\Local\Programs\Python\Python35-32\Scripts\ykdl-script
.py", line 11, in <module>
    load_entry_point('ykdl==1.5.2', 'console_scripts', 'ykdl')()
  File "c:\users\i\appdata\local\programs\python\python35-32\lib\site-packages\c
ykdl\__main__.py", line 163, in main
    info = parser(u)
  File "c:\users\i\appdata\local\programs\python\python35-32\lib\site-packages\y
kdl\extractor.py", line 24, in parser
    info = self.prepare()
  File "c:\users\i\appdata\local\programs\python\python35-32\lib\site-packages\y
kdl\extractors\bilibili\video.py", line 44, in prepare
    info.title = match1(html, '<h1 title="([^"]+)').strip()
AttributeError: 'NoneType' object has no attribute 'strip'

C:\Users\i>
```

**Comment by zhangn1985** [comment]
这个是用户的播放列表没法搞。

**Comment by redstoneleo** [comment]
可以的，你看url里av号，`https://www.bilibili.com/watchlater/#/av2679094/p1`
得到的视频网址就是`http://www.bilibili.com/video/av2679094/`
