### ISSUE TITLE
下载的视频是分段的，如何能下载整段的视频啊

### ISSUE THREAD

**Issue by ZMLoveLH** [zhangn1985/ykdl#187]
拜托懂得的大哥告诉我，小弟拜谢了

**Comment by lki2019** [comment]
你这说的什么啊，地址贴一个啊

**Comment by ZMLoveLH** [comment]
地址是这个：  http://v.youku.com/v_show/id_XMTQ3MjQyNDM4OA==.html

**Comment by lki2019** [comment]
C:\Users\Administrator>ykdl http://v.youku.com/v_show/id_XMTQ3MjQyNDM4OA==.html
site:                优酷 (Youku)
title:               【霹雳布袋戏MV】如是我闻·天之佛楼至韦驮
artist:              None
streams:
    - format:        BD
      container:     flv
      video-profile: 1080p
      size:          74.3 MiB (77877905 bytes)
    # download-with: ykdl --format=BD [URL]
Download: 【霹雳布袋戏MV】如是我闻·天之佛楼至韦驮_BD part 0
Download: 【霹雳布袋戏MV】如是我闻·天之佛楼至韦驮_BD part 1
 100%Merging video 【霹雳布袋戏MV】如是我闻·天之佛楼至韦驮_BD using ffmpeg:
[flv @ 033a04e0] Auto-inserting h264_mp4toannexb bitstream filter
Input #0, concat, from 'C:\Users\Administrator\tmptsl24fle.txt':
  Duration: N/A, start: 0.000000, bitrate: 2178 kb/s
    Stream #0:0: Video: h264 (High), yuv420p(progressive), 1904x824 [SAR 3787:37
60 DAR 450653:193640], 2049 kb/s, 25.03 fps, 25 tbr, 1k tbn, 50 tbc
    Stream #0:1: Audio: aac (HE-AAC), 44100 Hz, stereo, fltp, 128 kb/s
Output #0, flv, to '銆愰湽闆冲竷琚嬫垙MV銆戝鏄垜闂宦峰ぉ涔嬩經妤艰嚦闊﹂┊_B
D.flv':
  Metadata:
    encoder         : Lavf57.75.100
    Stream #0:0: Video: h264 (High) ([7][0][0][0] / 0x0007), yuv420p(progressive
), 1904x824 [SAR 3787:3760 DAR 450653:193640], q=2-31, 2049 kb/s, 25.03 fps, 25
tbr, 1k tbn, 1k tbc
    Stream #0:1: Audio: aac (HE-AAC) ([10][0][0][0] / 0x000A), 44100 Hz, stereo,
 fltp, 128 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
frame=    2 fps=0.0 q=-1.0 size=       0kB time=00:00:00.00 bitrate=N/A speed=
[flv @ 04f241c0] Auto-inserting h264_mp4toannexb bitstream filter
frame= 3185 fps=1709 q=-1.0 size=   33792kB time=00:02:07.32 bitrate=2174.2kbits
frame= 6505 fps=2931 q=-1.0 Lsize=   76053kB time=00:04:20.28 bitrate=2393.7kbit
s/s speed= 117x
video:71765kB audio:4067kB subtitle:0kB other streams:0kB global headers:0kB mux
ing overhead: 0.290807%



并没有你说的情况，【霹雳布袋戏MV】如是我闻·天之佛楼至韦驮_BD.flv


PS：你装ffmpeg.exe了么？http://www.ffmpeg.org/download.html

**Comment by ZMLoveLH** [comment]
我还没装ffmpeg，可能是这个原因吧，多谢指教

**Comment by ZMLoveLH** [comment]
我下载了 ffmpeg-3.3.3-win64-static.zip ，应该如何安装啊

**Comment by ZMLoveLH** [comment]
我运行 ykdl 显示如下

G:\>ykdl http://v.youku.com/v_show/id_XMTQ3MjQyNDM4OA==.html
site:                优酷 (Youku)
title:               【霹雳布袋戏MV】如是我闻·天之佛楼至韦驮
artist:              None
streams:
    - format:        BD
      container:     flv
      video-profile: 1080p
      size:          74.3 MiB (77877905 bytes)
    # download-with: ykdl --format=BD [URL]
Download: 【霹雳布袋戏MV】如是我闻·天之佛楼至韦驮_BD part 0
Download: 【霹雳布袋戏MV】如是我闻·天之佛楼至韦驮_BD part 1
 100%Merging video 【霹雳布袋戏MV】如是我闻·天之佛楼至韦驮_BD using ffmpeg:
Traceback (most recent call last):
  File "yk_dl.py", line 183, in <module>
  File "yk_dl.py", line 171, in main
  File "yk_dl.py", line 117, in handle_videoinfo
  File "yk_dl.py", line 78, in download
  File "site-packages\ykdl\util\wrap.py", line 41, in launch_ffmpeg
  File "subprocess.py", line 267, in call
  File "subprocess.py", line 707, in __init__
  File "subprocess.py", line 990, in _execute_child
FileNotFoundError: [WinError 2] 系统找不到指定的文件。
Failed to execute script yk_dl

到底怎么回事啊。。。

**Comment by lki2019** [comment]
我觉得你可能先百度一下之后，在继续追问比较好
你说对吧 这样记得牢点·

**Comment by zhangn1985** [comment]
安装到c:\windows\system32
或加入到PATH。

**Comment by ZMLoveLH** [comment]
多谢大哥们的指点，已经可以用了
