### ISSUE TITLE
能否支持huya视频

### ISSUE THREAD

**Issue by yibu10** [zhangn1985/ykdl#2]
http://v.huya.com/

例如：
http://v.huya.com/play/2011013.html  
移动端 http://m.v.huya.com/play/2011013.html

**Comment by zhangn1985** [comment]
请下载最新版本，看看是不是能用了。

**Comment by yibu10** [comment]
有的可以，有点不行

$ ykdl http://v.huya.com/play/2150954-328700492923.html
Traceback (most recent call last):
  File "/usr/local/bin/ykdl", line 14, in <module>
    ykdl.main()
  File "/Library/Python/2.7/site-packages/ykdl/__init__.py", line 10, in main
    main()
  File "/Library/Python/2.7/site-packages/ykdl/common.py", line 87, in main
    m.download(u, args)
  File "/Library/Python/2.7/site-packages/ykdl/extractor.py", line 98, in download
    self.prepare()
  File "/Library/Python/2.7/site-packages/ykdl/extractors/huya/video.py", line 24, in prepare
    data = json.loads(get_content(api_url))['result']['items']
KeyError: 'result'

**Comment by yibu10** [comment]
好了 👍
