### ISSUE TITLE
爱奇艺无法下载

### ISSUE THREAD

**Issue by ztytian** [zhangn1985/ykdl#211]
在提交前，请确保您已经检查了以下内容!

- [x] 你确实可以在浏览器或移动端中观看视频，但不能使用`ykdl`下载。
- [x] 您的`ykdl`为最新版。
- [x] 您已经阅读并按 <https://github.com/zhangn1985/ykdl/wiki> 中的指引进行了操作。
- [x] 您的问题没有在 <https://github.com/zhangn1985/ykdl/issues> 报告，否则请在原有 issue 下报告。
- [x] 本问题确实关于`ykdl`，而不是其他项目。

请将错误输出粘贴在下面:

$ ykdl http://www.iqiyi.com/v_19rr7yrgro.html --debug
DEBUG:common:video_host> www.iqiyi.com
DEBUG:common:short_name> iqiyi
DEBUG:html:get_content> URL: http://www.iqiyi.com/v_19rr7yrgro.html
DEBUG:html:get_content> Charset: utf-8
DEBUG:html:get_content> URL: http://cache.video.qiyi.com/vps?tvid=717798600&vid=cf4d1708a8be69aecc52b180778bbd35&v=0&qypid=717798600_12&src=01012001010000000000&t=1508016886216&k_tag=1&k_uid=cmbtnbs2xb8omy2au8uoy5vgjpozzl6i&rs=1&vf=f439348513d2cc85c702525ef0ad8ce9
DEBUG:html:get_content> Charset: utf-8
DEBUG:html:get_content> URL: http://data.video.qiyi.com/videos/v0/20170706/5f/ff/e7e1b004938fee5092843826f4bcd0f5.f4v?qd_tvid=717798600&qd_vipres=2&qd_index=1&qd_aid=208265001&qd_stert=0&qd_scc=0d89a956d381962d96494ffe4ff4f5ab&qd_sc=f62002c6d013a3c28061b2594cbd120d&qd_p=751cffcc&qd_ip=751cffcc&qd_k=f439348513d2cc85c702525ef0ad8ce9&qd_src=01012001010000000000&qd_vipdyn=2&qd_uid=0&qd_tm=1508016887112&qd_vip=0
Traceback (most recent call last):
  File "/usr/local/bin/ykdl", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/cykdl/__main__.py", line 163, in main
    info = parser(u)
  File "/usr/local/lib/python3.6/site-packages/ykdl/extractor.py", line 24, in parser
    info = self.prepare()
  File "/usr/local/lib/python3.6/site-packages/ykdl/extractors/iqiyi.py", line 83, in prepare
    json_data=json.loads(get_content(url))
  File "/usr/local/lib/python3.6/site-packages/ykdl/util/html.py", line 65, in get_content
    response = urlopen(req)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 405: Not Allowed

405 not allowed

**Comment by jxon** [comment]
是VIP视频，不能下载。
