### ISSUE TITLE
安装依赖库pycrypto失败。

### ISSUE THREAD

**Issue by Gokou-Ruri** [zhangn1985/ykdl#213]
安装环境是Android端的termux(AArch64)，py版本是3.6.3，pip版本是9.0.1(没有安装py2)。
（补充：youtube-dl和you-get已安装，但是搞不懂为啥安装ykdl的时候这个pycrypto会装不上。）
日志如下：
``` 
Collecting ykdl
  Downloading ykdl-1.5.2.tar.gz (48kB)
Collecting m3u8 (from ykdl)
  Downloading m3u8-0.3.4.tar.gz
Collecting pycrypto (from ykdl)
  Downloading pycrypto-2.6.1.tar.gz (446kB)
Collecting iso8601 (from m3u8->ykdl)
  Downloading iso8601-0.1.12-py3-none-any.whl
Installing collected packages: iso8601, m3u8, pycrypto, ykdl
  Running setup.py install for m3u8: started
    Running setup.py install for m3u8: finished with status 'done'
  Running setup.py install for pycrypto: started
    Running setup.py install for pycrypto: still running...
    Running setup.py install for pycrypto: finished with status 'error'
    Complete output from command /data/data/com.termux/files/usr/bin/python -u -c "import setuptools, tokenize;__file__='/data/data/com.termux/files/usr/tmp/pip-build-koj6pto4/pycrypto/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /data/data/com.termux/files/usr/tmp/pip-6rjdk4p9-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-aarch64-3.6
    creating build/lib.linux-aarch64-3.6/Crypto
    copying lib/Crypto/__init__.py -> build/lib.linux-aarch64-3.6/Crypto
    copying lib/Crypto/pct_warnings.py -> build/lib.linux-aarch64-3.6/Crypto
    creating build/lib.linux-aarch64-3.6/Crypto/Hash
    copying lib/Crypto/Hash/__init__.py -> build/lib.linux-aarch64-3.6/Crypto/Hash
    copying lib/Crypto/Hash/SHA224.py -> build/lib.linux-aarch64-3.6/Crypto/Hash
    copying lib/Crypto/Hash/SHA384.py -> build/lib.linux-aarch64-3.6/Crypto/Hash
    copying lib/Crypto/Hash/SHA.py -> build/lib.linux-aarch64-3.6/Crypto/Hash
    copying lib/Crypto/Hash/MD4.py -> build/lib.linux-aarch64-3.6/Crypto/Hash
    copying lib/Crypto/Hash/RIPEMD.py -> build/lib.linux-aarch64-3.6/Crypto/Hash
    copying lib/Crypto/Hash/MD2.py -> build/lib.linux-aarch64-3.6/Crypto/Hash
    copying lib/Crypto/Hash/HMAC.py -> build/lib.linux-aarch64-3.6/Crypto/Hash
    copying lib/Crypto/Hash/SHA512.py -> build/lib.linux-aarch64-3.6/Crypto/Hash
    copying lib/Crypto/Hash/hashalgo.py -> build/lib.linux-aarch64-3.6/Crypto/Hash
    copying lib/Crypto/Hash/SHA256.py -> build/lib.linux-aarch64-3.6/Crypto/Hash
    copying lib/Crypto/Hash/MD5.py -> build/lib.linux-aarch64-3.6/Crypto/Hash
    creating build/lib.linux-aarch64-3.6/Crypto/Cipher
    copying lib/Crypto/Cipher/PKCS1_OAEP.py -> build/lib.linux-aarch64-3.6/Crypto/Cipher
    copying lib/Crypto/Cipher/__init__.py -> build/lib.linux-aarch64-3.6/Crypto/Cipher
    copying lib/Crypto/Cipher/DES.py -> build/lib.linux-aarch64-3.6/Crypto/Cipher
    copying lib/Crypto/Cipher/ARC4.py -> build/lib.linux-aarch64-3.6/Crypto/Cipher
    copying lib/Crypto/Cipher/XOR.py -> build/lib.linux-aarch64-3.6/Crypto/Cipher
    copying lib/Crypto/Cipher/CAST.py -> build/lib.linux-aarch64-3.6/Crypto/Cipher
    copying lib/Crypto/Cipher/PKCS1_v1_5.py -> build/lib.linux-aarch64-3.6/Crypto/Cipher
    copying lib/Crypto/Cipher/blockalgo.py -> build/lib.linux-aarch64-3.6/Crypto/Cipher
    copying lib/Crypto/Cipher/AES.py -> build/lib.linux-aarch64-3.6/Crypto/Cipher
    copying lib/Crypto/Cipher/ARC2.py -> build/lib.linux-aarch64-3.6/Crypto/Cipher
    copying lib/Crypto/Cipher/DES3.py -> build/lib.linux-aarch64-3.6/Crypto/Cipher
    copying lib/Crypto/Cipher/Blowfish.py -> build/lib.linux-aarch64-3.6/Crypto/Cipher
    creating build/lib.linux-aarch64-3.6/Crypto/Util
    copying lib/Crypto/Util/asn1.py -> build/lib.linux-aarch64-3.6/Crypto/Util
    copying lib/Crypto/Util/__init__.py -> build/lib.linux-aarch64-3.6/Crypto/Util
    copying lib/Crypto/Util/_number_new.py -> build/lib.linux-aarch64-3.6/Crypto/Util
    copying lib/Crypto/Util/winrandom.py -> build/lib.linux-aarch64-3.6/Crypto/Util
    copying lib/Crypto/Util/Counter.py -> build/lib.linux-aarch64-3.6/Crypto/Util
    copying lib/Crypto/Util/RFC1751.py -> build/lib.linux-aarch64-3.6/Crypto/Util
    copying lib/Crypto/Util/randpool.py -> build/lib.linux-aarch64-3.6/Crypto/Util
    copying lib/Crypto/Util/py3compat.py -> build/lib.linux-aarch64-3.6/Crypto/Util
    copying lib/Crypto/Util/number.py -> build/lib.linux-aarch64-3.6/Crypto/Util
    creating build/lib.linux-aarch64-3.6/Crypto/Random
    copying lib/Crypto/Random/__init__.py -> build/lib.linux-aarch64-3.6/Crypto/Random
    copying lib/Crypto/Random/_UserFriendlyRNG.py -> build/lib.linux-aarch64-3.6/Crypto/Random
    copying lib/Crypto/Random/random.py -> build/lib.linux-aarch64-3.6/Crypto/Random
    creating build/lib.linux-aarch64-3.6/Crypto/Random/Fortuna
    copying lib/Crypto/Random/Fortuna/__init__.py -> build/lib.linux-aarch64-3.6/Crypto/Random/Fortuna
    copying lib/Crypto/Random/Fortuna/SHAd256.py -> build/lib.linux-aarch64-3.6/Crypto/Random/Fortuna
    copying lib/Crypto/Random/Fortuna/FortunaGenerator.py -> build/lib.linux-aarch64-3.6/Crypto/Random/Fortuna
    copying lib/Crypto/Random/Fortuna/FortunaAccumulator.py -> build/lib.linux-aarch64-3.6/Crypto/Random/Fortuna
    creating build/lib.linux-aarch64-3.6/Crypto/Random/OSRNG
    copying lib/Crypto/Random/OSRNG/posix.py -> build/lib.linux-aarch64-3.6/Crypto/Random/OSRNG
    copying lib/Crypto/Random/OSRNG/__init__.py -> build/lib.linux-aarch64-3.6/Crypto/Random/OSRNG
    copying lib/Crypto/Random/OSRNG/fallback.py -> build/lib.linux-aarch64-3.6/Crypto/Random/OSRNG
    copying lib/Crypto/Random/OSRNG/rng_base.py -> build/lib.linux-aarch64-3.6/Crypto/Random/OSRNG
    creating build/lib.linux-aarch64-3.6/Crypto/SelfTest
    copying lib/Crypto/SelfTest/st_common.py -> build/lib.linux-aarch64-3.6/Crypto/SelfTest
    copying lib/Crypto/SelfTest/__init__.py -> build/lib.linux-aarch64-3.6/Crypto/SelfTest
    creating build/lib.linux-aarch64-3.6/Crypto/SelfTest/Cipher
    copying lib/Crypto/SelfTest/Cipher/__init__.py -> build/lib.linux-aarch64-3.6/Crypto/SelfTest/Cipher
    copying lib/Crypto/SelfTest/Cipher/test_pkcs1_15.py -> build/lib.linux-aarch64-3.6/Crypto/SelfTest/Cipher
    copying lib/Crypto/SelfTest/Cipher/test_ARC4.py -> build/lib.linux-aarch64-3.6/Crypto/SelfTest/Cipher
    copying lib/Crypto/SelfTest/Cipher/test_AES.py -> build/lib.linux-aarch64-3.6/Crypto/SelfTest/Cipher
    copying lib/Crypto/SelfTest/Cipher/test_ARC2.py -> build/lib.linux-aarch64-3.6/Crypto/SelfTest/Cipher
    copying lib/Crypto/SelfTest/Cipher/test_Blowfish.py -> build/lib.linux-aarch64-3.6/Crypto/SelfTest/Cipher
    copying lib/Crypto/SelfTest/Cipher/test_XOR.py -> build/lib.linux-aarch64-3.6/Crypto/SelfTest/Cipher
    copying lib/Crypto/SelfTest/Cipher/test_DES.py -> build/lib.linux-aarch64-3.6/Crypto/SelfTest/Cipher
    copying lib/Crypto/SelfTest/Cipher/common.py -> build/lib.linux-aarch64-3.6/Crypto/SelfTest/Cipher
    copying lib/Crypto/SelfTest/Cipher/test_pkcs1_oaep.py -> build/lib.linux-aarch64-3.6/Crypto/SelfTest/Cipher
    copying lib/Crypto/SelfTest/Cipher/test_CAST.py -> build/lib.linux-aarch64-3.6/Crypto/SelfTest/Cipher
    copying lib/Crypto/SelfTest/Cipher/test_DES3.py -> build/lib.linux-aarch64-3.6/Crypto/SelfTest/Cipher
    creating build/lib.linux-aarch64-3.6/Crypto/SelfTest/Hash
    copying lib/Crypto/SelfTest/Hash/test_SHA256.py -> build/lib.linux-aarch64-3.6/Crypto/SelfTest/Hash
    copying lib/Crypto/SelfTest/Hash/__init__.py -> build/lib.linux-aarch64-3.6/Crypto/SelfTest/Hash
    copying lib/Crypto/SelfTest/Hash/test_MD2.py -> build/lib.linux-aarch64-3.6/Crypto/SelfTest/Hash
    copying lib/Crypto/SelfTest/Hash/test_HMAC.py -> build/lib.linux-aarch64-3.6/Crypto/SelfTest/Hash
    copying lib/Crypto/SelfTest/Hash/test_SHA384.py -> build/lib.linux-aarch64-3.6/Crypto/SelfTest/Hash
    copying lib/Crypto/SelfTest/Hash/test_RIPEMD.py -> build/lib.linux-aarch64-3.6/Crypto/SelfTest/Hash
    copying lib/Crypto/SelfTest/Hash/test_MD5.py -> build/lib.linux-aarch64-3.6/Crypto/SelfTest/Hash
    copying lib/Crypto/SelfTest/Hash/test_SHA.py -> build/lib.linux-aarch64-3.6/Crypto/SelfTest/Hash
    copying lib/Crypto/SelfTest/Hash/common.py -> build/lib.linux-aarch64-3.6/Crypto/SelfTest/Hash
    copying lib/Crypto/SelfTest/Hash/test_MD4.py -> build/lib.linux-aarch64-3.6/Crypto/SelfTest/Hash
    copying lib/Crypto/SelfTest/Hash/test_SHA224.py -> build/lib.linux-aarch64-3.6/Crypto/SelfTest/Hash
    copying lib/Crypto/SelfTest/Hash/test_SHA512.py -> build/lib.linux-aarch64-3.6/Crypto/SelfTest/Hash
    creating build/lib.linux-aarch64-3.6/Crypto/SelfTest/Protocol
    copying lib/Crypto/SelfTest/Protocol/__init__.py -> build/lib.linux-aarch64-3.6/Crypto/SelfTest/Protocol
    copying lib/Crypto/SelfTest/Protocol/test_rfc1751.py -> build/lib.linux-aarch64-3.6/Crypto/SelfTest/Protocol
    copying lib/Crypto/SelfTest/Protocol/test_chaffing.py -> build/lib.linux-aarch64-3.6/Crypto/SelfTest/Protocol
    copying lib/Crypto/SelfTest/Protocol/test_KDF.py -> build/lib.linux-aarch64-3.6/Crypto/SelfTest/Protocol
    copying lib/Crypto/SelfTest/Protocol/test_AllOrNothing.py -> build/lib.linux-aarch64-3.6/Crypto/SelfTest/Protocol
    creating build/lib.linux-aarch64-3.6/Crypto/SelfTest/PublicKey
    copying lib/Crypto/SelfTest/PublicKey/test_ElGamal.py -> build/lib.linux-aarch64-3.6/Crypto/SelfTest/PublicKey
    copying lib/Crypto/SelfTest/PublicKey/__init__.py -> build/lib.linux-aarch64-3.6/Crypto/SelfTest/PublicKey
    copying lib/Crypto/SelfTest/PublicKey/test_DSA.py -> build/lib.linux-aarch64-3.6/Crypto/SelfTest/PublicKey
    copying lib/Crypto/SelfTest/PublicKey/test_RSA.py -> build/lib.linux-aarch64-3.6/Crypto/SelfTest/PublicKey
    copying lib/Crypto/SelfTest/PublicKey/test_importKey.py -> build/lib.linux-aarch64-3.6/Crypto/SelfTest/PublicKey
    creating build/lib.linux-aarch64-3.6/Crypto/SelfTest/Random
    copying lib/Crypto/SelfTest/Random/__init__.py -> build/lib.linux-aarch64-3.6/Crypto/SelfTest/Random
    copying lib/Crypto/SelfTest/Random/test_random.py -> build/lib.linux-aarch64-3.6/Crypto/SelfTest/Random
    copying lib/Crypto/SelfTest/Random/test_rpoolcompat.py -> build/lib.linux-aarch64-3.6/Crypto/SelfTest/Random
    copying lib/Crypto/SelfTest/Random/test__UserFriendlyRNG.py -> build/lib.linux-aarch64-3.6/Crypto/SelfTest/Random
    creating build/lib.linux-aarch64-3.6/Crypto/SelfTest/Random/Fortuna
    copying lib/Crypto/SelfTest/Random/Fortuna/__init__.py -> build/lib.linux-aarch64-3.6/Crypto/SelfTest/Random/Fortuna
    copying lib/Crypto/SelfTest/Random/Fortuna/test_FortunaAccumulator.py -> build/lib.linux-aarch64-3.6/Crypto/SelfTest/Random/Fortuna
    copying lib/Crypto/SelfTest/Random/Fortuna/test_FortunaGenerator.py -> build/lib.linux-aarch64-3.6/Crypto/SelfTest/Random/Fortuna
    copying lib/Crypto/SelfTest/Random/Fortuna/test_SHAd256.py -> build/lib.linux-aarch64-3.6/Crypto/SelfTest/Random/Fortuna
    creating build/lib.linux-aarch64-3.6/Crypto/SelfTest/Random/OSRNG
    copying lib/Crypto/SelfTest/Random/OSRNG/__init__.py -> build/lib.linux-aarch64-3.6/Crypto/SelfTest/Random/OSRNG
    copying lib/Crypto/SelfTest/Random/OSRNG/test_generic.py -> build/lib.linux-aarch64-3.6/Crypto/SelfTest/Random/OSRNG
    copying lib/Crypto/SelfTest/Random/OSRNG/test_nt.py -> build/lib.linux-aarch64-3.6/Crypto/SelfTest/Random/OSRNG
    copying lib/Crypto/SelfTest/Random/OSRNG/test_fallback.py -> build/lib.linux-aarch64-3.6/Crypto/SelfTest/Random/OSRNG
    copying lib/Crypto/SelfTest/Random/OSRNG/test_winrandom.py -> build/lib.linux-aarch64-3.6/Crypto/SelfTest/Random/OSRNG
    copying lib/Crypto/SelfTest/Random/OSRNG/test_posix.py -> build/lib.linux-aarch64-3.6/Crypto/SelfTest/Random/OSRNG
    creating build/lib.linux-aarch64-3.6/Crypto/SelfTest/Util
    copying lib/Crypto/SelfTest/Util/__init__.py -> build/lib.linux-aarch64-3.6/Crypto/SelfTest/Util
    copying lib/Crypto/SelfTest/Util/test_asn1.py -> build/lib.linux-aarch64-3.6/Crypto/SelfTest/Util
    copying lib/Crypto/SelfTest/Util/test_number.py -> build/lib.linux-aarch64-3.6/Crypto/SelfTest/Util
    copying lib/Crypto/SelfTest/Util/test_winrandom.py -> build/lib.linux-aarch64-3.6/Crypto/SelfTest/Util
    copying lib/Crypto/SelfTest/Util/test_Counter.py -> build/lib.linux-aarch64-3.6/Crypto/SelfTest/Util
    creating build/lib.linux-aarch64-3.6/Crypto/SelfTest/Signature
    copying lib/Crypto/SelfTest/Signature/__init__.py -> build/lib.linux-aarch64-3.6/Crypto/SelfTest/Signature
    copying lib/Crypto/SelfTest/Signature/test_pkcs1_15.py -> build/lib.linux-aarch64-3.6/Crypto/SelfTest/Signature
    copying lib/Crypto/SelfTest/Signature/test_pkcs1_pss.py -> build/lib.linux-aarch64-3.6/Crypto/SelfTest/Signature
    creating build/lib.linux-aarch64-3.6/Crypto/Protocol
    copying lib/Crypto/Protocol/__init__.py -> build/lib.linux-aarch64-3.6/Crypto/Protocol
    copying lib/Crypto/Protocol/KDF.py -> build/lib.linux-aarch64-3.6/Crypto/Protocol
    copying lib/Crypto/Protocol/Chaffing.py -> build/lib.linux-aarch64-3.6/Crypto/Protocol
    copying lib/Crypto/Protocol/AllOrNothing.py -> build/lib.linux-aarch64-3.6/Crypto/Protocol
    creating build/lib.linux-aarch64-3.6/Crypto/PublicKey
    copying lib/Crypto/PublicKey/__init__.py -> build/lib.linux-aarch64-3.6/Crypto/PublicKey
    copying lib/Crypto/PublicKey/_RSA.py -> build/lib.linux-aarch64-3.6/Crypto/PublicKey
    copying lib/Crypto/PublicKey/ElGamal.py -> build/lib.linux-aarch64-3.6/Crypto/PublicKey
    copying lib/Crypto/PublicKey/_DSA.py -> build/lib.linux-aarch64-3.6/Crypto/PublicKey
    copying lib/Crypto/PublicKey/DSA.py -> build/lib.linux-aarch64-3.6/Crypto/PublicKey
    copying lib/Crypto/PublicKey/RSA.py -> build/lib.linux-aarch64-3.6/Crypto/PublicKey
    copying lib/Crypto/PublicKey/pubkey.py -> build/lib.linux-aarch64-3.6/Crypto/PublicKey
    copying lib/Crypto/PublicKey/_slowmath.py -> build/lib.linux-aarch64-3.6/Crypto/PublicKey
    creating build/lib.linux-aarch64-3.6/Crypto/Signature
    copying lib/Crypto/Signature/__init__.py -> build/lib.linux-aarch64-3.6/Crypto/Signature
    copying lib/Crypto/Signature/PKCS1_v1_5.py -> build/lib.linux-aarch64-3.6/Crypto/Signature
    copying lib/Crypto/Signature/PKCS1_PSS.py -> build/lib.linux-aarch64-3.6/Crypto/Signature
    Skipping optional fixer: buffer
    Skipping optional fixer: idioms
    Skipping optional fixer: set_literal
    Skipping optional fixer: ws_comma
    running build_ext
    running build_configure
    checking for gcc... no
    checking for cc... no
    checking for cl.exe... no
    configure: error: in `/data/data/com.termux/files/usr/tmp/pip-build-koj6pto4/pycrypto':
    configure: error: no acceptable C compiler found in $PATH
    See `config.log' for more details
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/data/data/com.termux/files/usr/tmp/pip-build-koj6pto4/pycrypto/setup.py", line 456, in <module>
        core.setup(**kw)
      File "/data/data/com.termux/files/usr/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/data/data/com.termux/files/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/data/data/com.termux/files/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/data/data/com.termux/files/usr/lib/python3.6/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/data/data/com.termux/files/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/data/data/com.termux/files/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/data/data/com.termux/files/usr/lib/python3.6/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/data/data/com.termux/files/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/data/data/com.termux/files/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/data/data/com.termux/files/usr/tmp/pip-build-koj6pto4/pycrypto/setup.py", line 251, in run
        self.run_command(cmd_name)
      File "/data/data/com.termux/files/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/data/data/com.termux/files/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/data/data/com.termux/files/usr/tmp/pip-build-koj6pto4/pycrypto/setup.py", line 278, in run
        raise RuntimeError("autoconf error")
    RuntimeError: autoconf error
    
    ----------------------------------------

```

**Comment by mengmo** [comment]
https://github.com/zhangn1985/ykdl/issues/131#issuecomment-304812766
> 对于想装在android或是路由器上的大概只能手写AES-128-CBC

**Comment by zhangn1985** [comment]
确实如此，pycryptodome也没有提供ARM的预编译版本。

由于ykdl发布到Pip的是源码，你可以自行修改，把pycrypto的依赖去掉，这样网易云音乐就不能下载了。

除此之外，没有别的影响。

https://github.com/zhangn1985/ykdl/blob/7c952b00ca7879e226f7d9c4c820e226278b9165/setup.py#L28

**Comment by cok3307788** [comment]
建议在Wiki里面添加Android User Guide，避免萌新折腾一天Termux差点恢复出厂设置

**Comment by mengmo** [comment]
@cok3307788 已添加

**Comment by zhangn1985** [comment]
@mengmo 谢谢
