### ISSUE TITLE
tw.iqiyi not work

### ISSUE THREAD

**Issue by goodneo** [zhangn1985/ykdl#246]
在提交前，请确保您已经检查了以下内容!

- [x] 你确实可以在浏览器或移动端中观看视频，但不能使用`ykdl`下载。
- [x] 您的`ykdl`为最新版。
- [x] 您已经阅读并按 <https://github.com/zhangn1985/ykdl/wiki> 中的指引进行了操作。
- [x] 您的问题没有在 <https://github.com/zhangn1985/ykdl/issues> 报告，否则请在原有 issue 下报告。
- [x] 本问题确实关于`ykdl`，而不是其他项目。

请将错误输出粘贴在下面:

```
Traceback (most recent call last):
  File "d:\Python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\Python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\neo\Desktop\ykdl-master\cykdl\__main__.py", line 185, in <module>
    main()
  File "C:\Users\neo\Desktop\ykdl-master\cykdl\__main__.py", line 163, in main
    info = parser(u)
  File "C:\Users\neo\Desktop\ykdl-master\ykdl\extractor.py", line 24, in parser
    info = self.prepare()
  File "C:\Users\neo\Desktop\ykdl-master\ykdl\extractors\iqiyi.py", line 77, in prepare
    vps_data = getvps(tvid, vid)
  File "C:\Users\neo\Desktop\ykdl-master\ykdl\extractors\iqiyi.py", line 46, in getvps
    html = get_content(req_url)
  File "C:\Users\neo\Desktop\ykdl-master\ykdl\util\html.py", line 65, in get_content
    response = urlopen(req)
  File "d:\Python36\lib\urllib\request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "d:\Python36\lib\urllib\request.py", line 526, in open
    response = self._open(req, data)
  File "d:\Python36\lib\urllib\request.py", line 544, in _open
    '_open', req)
  File "d:\Python36\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "d:\Python36\lib\urllib\request.py", line 1346, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "d:\Python36\lib\urllib\request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "d:\Python36\lib\http\client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "d:\Python36\lib\http\client.py", line 1250, in _send_request
    self.putrequest(method, url, **skips)
  File "d:\Python36\lib\http\client.py", line 1117, in putrequest
    self._output(request.encode('ascii'))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 761-762: ordinal not in range(128)
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加:

> 本來都正常 突然跳這個錯誤不知道怎麼處理 是要從哪邊去修改嗎?
感覺跟愛奇藝 網站改變格式有關?

**Comment by goodneo** [comment]
Traceback (most recent call last):
  File "d:\Python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\Python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\neo\Desktop\ykdl-master\cykdl\__main__.py", line 185, in <module>
    main()
  File "C:\Users\neo\Desktop\ykdl-master\cykdl\__main__.py", line 163, in main
    info = parser(u)
  File "C:\Users\neo\Desktop\ykdl-master\ykdl\extractor.py", line 24, in parser
    info = self.prepare()
  File "C:\Users\neo\Desktop\ykdl-master\ykdl\extractors\iqiyi.py", line 77, in prepare
    vps_data = getvps(tvid, vid)
  File "C:\Users\neo\Desktop\ykdl-master\ykdl\extractors\iqiyi.py", line 46, in getvps
    html = get_content(req_url)
  File "C:\Users\neo\Desktop\ykdl-master\ykdl\util\html.py", line 65, in get_content
    response = urlopen(req)
  File "d:\Python36\lib\urllib\request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "d:\Python36\lib\urllib\request.py", line 526, in open
    response = self._open(req, data)
  File "d:\Python36\lib\urllib\request.py", line 544, in _open
    '_open', req)
  File "d:\Python36\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "d:\Python36\lib\urllib\request.py", line 1346, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "d:\Python36\lib\urllib\request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "d:\Python36\lib\http\client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "d:\Python36\lib\http\client.py", line 1250, in _send_request
    self.putrequest(method, url, **skips)
  File "d:\Python36\lib\http\client.py", line 1117, in putrequest
    self._output(request.encode('ascii'))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 149-153: ordinal not in range(128)

**Comment by huzy0909** [comment]
我试了下爱奇艺的视频，可以下载，如果方便，最好把视频网址也发出来，方便别人重现错误

**Comment by goodneo** [comment]
http://tw.iqiyi.com/v_19rrft5tlg.html

**Comment by zhangn1985** [comment]
这个就麻烦了，tw我们大陆这边上不去。vpn也不好用。

**Comment by zhangn1985** [comment]
看了一下是

```
            tvid = match1(html, 'data-player-tvid="([^"]+)"', 'tvid=([^&]+)' , 'tvId:([^,]+)')
            videoid = match1(html, 'data-player-videoid="([^"]+)"', 'vid=([^&]+)', 'vid:"([^"]+)')
```
这两行出错了。

但是仔细看了网页的源码，没有类似的东西，又不能访问，所以没法直接debug。

只有等台湾的朋友贡献了。

**Comment by lamlam123tld3** [comment]
<script type="text/javascript">
--
  | window.uniqy = window.uniqy \|\| {};
  | uniqy.pageAdParam = {"type":"playPage","cpnc":"e9d08348b4c76a668b62f3f22d927e28","ccid":"qc_100001_100015","cpnv":"1.0"};
  | uniqy.playList = [];
  | uniqy.curVideoInfo = {"tvid":"858269800","vid":"8da6f231d1fe35084c1f63e872cac14f","albumid":"218055601","channelId":"2","isMember":"false","isProduced":"0","isExclusive":"0","vu":"http://tw.iqiyi.com/v_19rre8qi9w.html","componentsId":"feffffe6e","openSound":"1"};
  | uniqy.albumPurType = "0";
  | </script>

**Comment by zhangn1985** [comment]
```diff
--             videoid = match1(html, 'data-player-videoid="([^"]+)"', 'vid=([^&]+)', 'vid:"([^"]+)')
+++            videoid = match1(html, 'data-player-videoid="([^"]+)"', 'vid:"([^"]+)', 'vid=([^&]+)')
```
看来只需要这么改咯。

**Comment by zhangn1985** [comment]
tw.iqiyi比较复杂，不是那么简单，除非有人提交patch，我没有办法fix这个问题。

**Comment by rasso1** [comment]
1.原播放视频网址：http://tw.iqiyi.com/v_19rrfp732g.html  
使用debug，解析出类似一大串网页的错误网址： http://cache.video.qiyi.com/vps?tvid="921220900" movie-id="0" cur-page-no="1" page-mode="laiyuan" video-type="video" v-bind:total-page="1" v-bind:total-video="1" album-title="綜藝大熱門：怎麼可以忘了我？通告優先爭奪戰" first-order="1" cur-pd="1">.....

2.使用www替代掉tw，视频网址变为：http://www.iqiyi.com/v_19rrfp732g.html
可正确解析出关键地址：http://cache.video.qiyi.com/vps?tvid=921220900&vid=c7222dfbe95ebf1c4a94410bbe8f658a&v=0&qypid=921220900_12&src=01012001010000000000&t=1517577274823&k_tag=1&k_uid=jmw2kmkr4a2pqw6fm7l84phpzafowzju&rs=1&vf=be1d4c1d2ccf4b5b3ce88b80f43c78de
而且响应内容也都是正确的，包括大量视频地址，内容很长，如需要再贴出
----------------
所以能否还是利用大陆的www网页那套老的js，正确解析地址后，然后再调用代理发送http://cache.video.qiyi.com/vps?tvid......命令，以得出正确视频地址

P.S.
如果一开始就挂台-湾代理，那使用www替代也无效，还是会调用tw的js，这样无法得出正确地址。
而台-湾站判断IP是否属于台-湾地区，只要发送这个地址时的IP是台-湾的即可：http://cache.video.qiyi.com/vps?tvid....
其他任何iqiyi网址都没关系（获取mp4时除外：http://cache.m.iqiyi.com/）

**Comment by goodneo** [comment]
要提供那些資訊 來方便你們patch呢?

**Comment by airdge** [comment]
爱奇艺台湾 和国内的算法完全一样   挂台湾vpn就可以解析

**Comment by rasso1** [comment]
@zhangn1985 光换www还不够吧，挂台湾VPN后一样出错。

如果检测到台湾IP，会自动跳回tw。
所以需要访问http://www.iqiyi.com/v_19rre8qi9w.html时，非台湾IP。台湾朋友要代理这个网址。其他地区不需。

而关键的cache.video.qiyi.com需要台湾IP，不然就ban。所以台湾朋友不需代理这个网址，其他地区需要台湾代理。

如果ykdl能设置针对个别网址的代理就最方便，不然就用SSR类代理软件里设置-代理规则-自定义

**Comment by airdge** [comment]
这个很简单吧  判断返回json->ctl->area是否赋值   然后循环 用vpn代理获取

**Comment by zhangn1985** [comment]
目前ykdl在解析tw.iqiyi的问题是vid/tvid获取失败，正则表达式不好用。

**Comment by airdge** [comment]
源代码形式确实有几种   多弄几次匹配就好了 
```
var http = require('http');
var url = 'http://tw.iqiyi.com/v_19rrff9ddc.html';
// url = 'http://www.iqiyi.com/v_19rre04t8s.html';
// url = 'http://www.iqiyi.com/v_19rr8bq6zo.html';
// url = 'http://tw.iqiyi.com/v_19rr7pcby8.html';
// url = 'http://www.iqiyi.com/v_19rrak6dyo.html';
http.get(url, function(res) {
    data = "";
    res.on("data", function(html) {
        data += html
    })
    res.on('end', function() {
        var tvid, vid, a, b, x;
        a = /"tvid":"(\d+)","vid":"(\w+)"/g;
        x = a.exec(data);
        if (x != null) {
            tvid = x[1];
            vid = x[2];
        }
        if (!vid) {
            a = /data-player-videoid="(\w+)"/g;
            x = a.exec(data);
            if (x != null) {
                vid = x[1];
                b = /data-player-tvid="(\w+)"/g;
                x = b.exec(data);
                tvid = x[1];
            }
        };
        console.log(vid);
        console.log(tvid);
    })
});
```

**Comment by steven7851** [comment]
https://github.com/iawia002/annie/blob/49d3844b4a42586e24e7129dcce7d4c004c4b373/extractors/iqiyi.go#L66
这里有大陆版与台湾版皆可用的方案，但是用Golang写的，Python有解决方案吗？

**Comment by airdge** [comment]
@steven7851 台湾iqiyi和大陆版的算法完全一致    必须要台湾ip才能解析  如果想要解析  还得弄个台湾的空间做代理

**Comment by jindaxia** [comment]
https://github.com/zhangn1985/ykdl/tree/test_for_tw  
@goodneo  Please test

**Comment by steven7851** [comment]
@airdge 我知道算法是一样的，但原始档里的ID格式不同，目前正则无法适配所有格式

**Comment by steven7851** [comment]
@jindaxia 我改了一下台湾版目前可行了，但不确定大陆版的能不能正常。。。。
https://github.com/zhangn1985/ykdl/pull/306/files
