### ISSUE TITLE
bilibili 又出问题了

### ISSUE THREAD

**Issue by mengmo** [zhangn1985/ykdl#25]
```
ykdl http://www.bilibili.com/video/av6429835/
site:                哔哩哔哩 (Bilibili)
title:               路人超能100(灵能百分百) : 第12集 龙套与灵幻 ～巨大土龙出现 之篇～
artist:              None
streams:
    - format:        TD
      container:     flv
      video-profile: 超清
      size:          0.0 MiB (0 bytes)
    # download-with: ykdl --format=TD [URL]
Traceback (most recent call last):
  File "yk_dl.py", line 148, in <module>
  File "yk_dl.py", line 136, in main
  File "yk_dl.py", line 90, in handle_videoinfo
  File "yk_dl.py", line 53, in download
IndexError: list index out of range
Failed to execute script yk_dl
```
```
ykdl http://bangumi.bilibili.com/anime/v/92403
site:                哔哩哔哩 (Bilibili)
title:               路人超能100(灵能百分百) : 第12集 龙套与灵幻 ～巨大土龙出现 之篇～
artist:              None
streams:
    - format:        TD
      container:     flv
      video-profile: 超清
      size:          0.0 MiB (0 bytes)
    # download-with: ykdl --format=TD [URL]
Traceback (most recent call last):
  File "yk_dl.py", line 148, in <module>
  File "yk_dl.py", line 136, in main
  File "yk_dl.py", line 90, in handle_videoinfo
  File "yk_dl.py", line 53, in download
IndexError: list index out of range
Failed to execute script yk_dl
```
另外，上一版本的解析番剧页还能用
```
ykdl -i http://bangumi.bilibili.com/anime/v/92403
site:                哔哩哔哩 (Bilibili)
title:               路人超能100(灵能百分百) : 第12集 龙套与灵幻 ～巨大土龙出现 之篇～ 番剧 bilibili 哔哩哔哩弹幕视频网
artist:              None
streams:
    - format:        TD
      container:     flv
      video-profile: 超清
      size:          305.2 MiB (320000538 bytes)
    # download-with: ykdl --format=TD [URL]
Real urls:
```

**Comment by zhangn1985** [comment]
应该是bilibili本身暂时性的问题。目前测试是可以正常工作的。

是不是要加入一些debug开关呢？

**Comment by mengmo** [comment]
确实，刚试了可以正常解析。貌似 `B站`最近一直在调整啊。
至于`debug`开关，有必要的话就加呗
