### ISSUE TITLE
B站视频下载错误HTTP Error 466

### ISSUE THREAD

**Issue by sanyle** [zhangn1985/ykdl#258]
在提交前，请确保您已经检查了以下内容!

- [ ] 你确实可以在浏览器或移动端中观看视频，但不能使用`ykdl`下载。
- [ ] 您的`ykdl`为最新版。
- [ ] 您已经阅读并按 <https://github.com/zhangn1985/ykdl/wiki> 中的指引进行了操作。
- [ ] 您的问题没有在 <https://github.com/zhangn1985/ykdl/issues> 报告，否则请在原有 issue 下报告。
- [ ] 本问题确实关于`ykdl`，而不是其他项目。

请将错误输出粘贴在下面:

```
C:\Users\Administrator>ykdl https://www.bilibili.com/video/av20962940/
site:                哔哩哔哩 (Bilibili)
title:               【这就是街舞】街舞圈大神如何评价罗志祥合集
artist:              None
streams:
    - format:        BD
      container:     flv
      video-profile: 蓝光
      size:          44.5 MiB (46687016 bytes)
    # download-with: ykdl --format=BD [URL]
Download: 【这就是街舞】街舞圈大神如何评价罗志祥合集_BD
Traceback (most recent call last):
  File "C:\python36\Scripts\ykdl-script.py", line 11, in <module>
    load_entry_point('ykdl==1.5.5', 'console_scripts', 'ykdl')()
  File "c:\python36\lib\site-packages\cykdl\__main__.py", line 173, in main
    handle_videoinfo(info)
  File "c:\python36\lib\site-packages\cykdl\__main__.py", line 119, in handle_videoinfo
    download(urls, name, ext, live)
  File "c:\python36\lib\site-packages\cykdl\__main__.py", line 77, in download
    if save_urls(urls, name, ext, jobs = args.jobs):
  File "c:\python36\lib\site-packages\ykdl\util\download.py", line 82, in save_urls
    save_url(urls[0], name, ext, status)
  File "c:\python36\lib\site-packages\ykdl\util\download.py", line 47, in save_url
    response = urlopen(req, None)
  File "c:\python36\lib\urllib\request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "c:\python36\lib\urllib\request.py", line 532, in open
    response = meth(req, response)
  File "c:\python36\lib\urllib\request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "c:\python36\lib\urllib\request.py", line 570, in error
    return self._call_chain(*args)
  File "c:\python36\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "c:\python36\lib\urllib\request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 466:
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加:

>[B站的试了好几个都不行]

**Comment by zhangn1985** [comment]
因为B站代码更新了太多，所以请先根据wiki指引更新到最新开发板，再尝试，并请加上--debug，附上log。
