### ISSUE TITLE
iqiyi無法下載

### ISSUE THREAD

**Issue by Andy8r0X** [zhangn1985/ykdl#279]
在提交前，请确保您已经检查了以下内容!

- [v] 你确实可以在浏览器或移动端中观看视频，但不能使用`ykdl`下载。
- [v] 您的`ykdl`为最新版。
- [v] 您已经阅读并按 <https://github.com/zhangn1985/ykdl/wiki> 中的指引进行了操作。
- [v] 您的问题没有在 <https://github.com/zhangn1985/ykdl/issues> 报告，否则请在原有 issue 下报告。
- [v] 本问题确实关于`ykdl`，而不是其他项目。

请将错误输出粘贴在下面:

```
C:\>ykdl http://www.iqiyi.com/v_19rrd29axg.html
Traceback (most recent call last):
  File "c:\python34\lib\runpy.py", line 171, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python34\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Python34\Scripts\ykdl.exe\__main__.py", line 9, in <module>
  File "c:\python34\lib\site-packages\cykdl\__main__.py", line 171, in main
    info = parser(u)
  File "c:\python34\lib\site-packages\ykdl\extractor.py", line 24, in parser
    info = self.prepare()
  File "c:\python34\lib\site-packages\ykdl\extractors\iqiyi.py", line 77, in pre
pare
    vps_data = getvps(tvid, vid)
  File "c:\python34\lib\site-packages\ykdl\extractors\iqiyi.py", line 46, in get
vps
    html = get_content(req_url)
  File "c:\python34\lib\site-packages\ykdl\util\html.py", line 65, in get_conten
t
    response = urlopen(req)
  File "c:\python34\lib\urllib\request.py", line 153, in urlopen
    return opener.open(url, data, timeout)
  File "c:\python34\lib\urllib\request.py", line 453, in open
    req = meth(req)
  File "c:\python34\lib\urllib\request.py", line 1159, in do_request_
    raise URLError('no host given')
urllib.error.URLError: <urlopen error no host given>
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加:

> 希望能得到幫助，謝謝

**Comment by SeaHOH** [comment]
无法复现，请重新确定，或增加更多信息。
