### ISSUE TITLE
xingyan.panda 部分地址异常

### ISSUE THREAD

**Issue by a67878813** [zhangn1985/ykdl#292]
ykdl   'http://xingyan.panda.tv/145919'

Traceback (most recent call last):
  File "/usr/local/bin/ykdl", line 9, in <module>
    load_entry_point('ykdl==1.6.0', 'console_scripts', 'ykdl')()
  File "/usr/local/lib/python3.5/dist-packages/ykdl-1.6.0-py3.5.egg/cykdl/__main__.py", line 171, in main
  File "/usr/local/lib/python3.5/dist-packages/ykdl-1.6.0-py3.5.egg/ykdl/extractor.py", line 24, in parser
  File "/usr/local/lib/python3.5/dist-packages/ykdl-1.6.0-py3.5.egg/ykdl/extractors/panda/xingyan.py", line 23, in prepare
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Unterminated string starting at: line 1 column 3249 (char 3248)

===================================

**Comment by mengmo** [comment]
请更新至最新版再次尝试
```
ykdl -i http://xingyan.panda.tv/145919
site:                熊猫星颜 (Panda Xingyan)
title:               熊猫最强音质百万录音棚千万调音师
artist:              Biu钟亚男
streams:
    - format:        current
      container:     flv
      video-profile: current
    # download-with: ykdl --format=current [URL]
Real urls:
http://flv-live-qn.xingxiu.panda.tv/panda-xingxiu/4853b2fbba708ca8716675419bf662e2.flv
```

**Comment by a67878813** [comment]
已成功，多谢提醒。因更新记录未显示panta修正，欠考虑了。

**Comment by mengmo** [comment]
问题解决了的话，就请把这个 issue 关了吧。
