### ISSUE TITLE
bilibili部分视频不能播放

### ISSUE THREAD

**Issue by karma-sun** [zhangn1985/ykdl#297]
在提交前，请确保您已经检查了以下内容!

- [ ] 你确实可以在浏览器或移动端中观看视频，但不能使用`ykdl`下载。
- [ ] 您的`ykdl`为最新版。
- [ ] 您已经阅读并按 <https://github.com/zhangn1985/ykdl/wiki> 中的指引进行了操作。
- [ ] 您的问题没有在 <https://github.com/zhangn1985/ykdl/issues> 报告，否则请在原有 issue 下报告。
- [ ] 本问题确实关于`ykdl`，而不是其他项目。

请将错误输出粘贴在下面:

```
ykdl -i https://www.bilibili.com/video/av10615671/
CRITICAL:YKDL:can't play this video!!
```

在网页上是可以播放的

**Comment by airdge** [comment]
应该有错,看了下结果 匹配的cid结果是7
`<script>window.__playinfo__={"from":"local","result":"suee","quality":15,"format":"flv360","timelength":1735150,"accept_format":"flv,flv720,flv360","accept_description":["高清 1080P","高清 720P","流畅 360P"],"accept_quality":[80,64,15],"video_codecid":7,"video_project":true,"se`

这样子应该可以用
```
            vid = match1(html, 'cid(?==|")=?"?:?(\d+)')
            if len(vid)<5:
                vid=match1(html,'cid=(\d+)&')
```

**Comment by SeaHOH** [comment]
是的，是我搞错顺序逻辑了，已经在几天前更新修复。

**Comment by karma-sun** [comment]
更新代码后报错
ykdl -i https://www.bilibili.com/video/av10615671/

Traceback (most recent call last):
  File "C:\Python35\Scripts\ykdl-script.py", line 9, in <module>
    load_entry_point('ykdl==1.6.1', 'console_scripts', 'ykdl')()
  File "C:\Python35\lib\site-packages\ykdl-1.6.1-py3.5.egg\cykdl\__main__.py", line 174, in main
  File "C:\Python35\lib\site-packages\ykdl-1.6.1-py3.5.egg\ykdl\extractor.py", line 24, in parser
  File "C:\Python35\lib\site-packages\ykdl-1.6.1-py3.5.egg\ykdl\extractors\bilibili\bilibase.py", line 49, in prepare
  File "C:\Python35\lib\site-packages\ykdl-1.6.1-py3.5.egg\ykdl\extractors\bilibili\video.py", line 39, in get_vid_title
UnboundLocalError: local variable 'vid' referenced before assignment

**Comment by SeaHOH** [comment]
已修复。
没咋使用，之前修复列表的时候没匹配好名称。
