### ISSUE TITLE
xingyan.py HOSTINFO 正则需要修改

### ISSUE THREAD

**Issue by gitterliu** [zhangn1985/ykdl#299]
https://github.com/zhangn1985/ykdl/blob/9c09cd626fe0bd470eda0c5bf1bd3a6ab00be4e5/ykdl/extractors/panda/xingyan.py#L22
改为: `page_meta = match1(page, r'window\.HOSTINFO=({.+?});')`

**Comment by mengmo** [comment]
```
ykdl -i https://xingyan.panda.tv/554211
Traceback (most recent call last):
  File "D:\PortableApps\Python\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\PortableApps\Python\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\PortableApps\Python\lib\site-packages\cykdl\__main__.py", line 195, in <module>
    main()
  File "D:\PortableApps\Python\lib\site-packages\cykdl\__main__.py", line 173, in main
    info = parser(u)
  File "D:\PortableApps\Python\lib\site-packages\ykdl\extractor.py", line 24, in parser
    info = self.prepare()
  File "D:\PortableApps\Python\lib\site-packages\ykdl\extractors\panda\xingyan.py", line 23, in prepare
    page_meta = json.loads(page_meta)
  File "D:\PortableApps\Python\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "D:\PortableApps\Python\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\PortableApps\Python\lib\json\decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Unterminated string starting at: line 1 column 485 (char 484)
```
