### ISSUE TITLE
出现错误

### ISSUE THREAD

**Issue by dazhuangge** [zhangn1985/ykdl#316]
在提交前，请确保您已经检查了以下内容!

- [x] 你确实可以在浏览器或移动端中观看视频，但不能使用`ykdl`下载。
- [x] 您的`ykdl`为最新版。
- [x] 您已经阅读并按 <https://github.com/zhangn1985/ykdl/wiki> 中的指引进行了操作。
- [x] 您的问题没有在 <https://github.com/zhangn1985/ykdl/issues> 报告，否则请在原有 issue 下报告。
- [x] 本问题确实关于`ykdl`，而不是其他项目。

请将错误输出粘贴在下面:
C:\Users\guoce>ykdl http://vo.youku.com/v_show/id_XMTkwNDgzNjY0.html
Traceback (most recent call last):
  File "C:\Users\guoce\AppData\Local\Programs\Python\Python36-32\Scripts\ykdl-script.py", line 11, in <module>
    load_entry_point('ykdl==1.6.2', 'console_scripts', 'ykdl')()
  File "C:\Users\guoce\AppData\Local\Programs\Python\Python36-32\lib\site-packages\cykdl\__main__.py", line 173, in main
    info = parser(u)
  File "C:\Users\guoce\AppData\Local\Programs\Python\Python36-32\lib\site-packages\ykdl\extractor.py", line 24, in parser
    info = self.prepare()
  File "C:\Users\guoce\AppData\Local\Programs\Python\Python36-32\lib\site-packages\ykdl\extractors\youku.py", line 54, in prepare
    if self.vid.isdigit():
AttributeError: 'NoneType' object has no attribute 'isdigit'
```
[在这里粘贴完整日志]
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加:

> [您的内容]

**Comment by SeaHOH** [comment]
3be416a683b712d776ea285b7ed6f376bea134c7
