### ISSUE TITLE
kankanews 的解析挂了

### ISSUE THREAD

**Issue by mengmo** [zhangn1985/ykdl#337]
在提交前，请确保您已经检查了以下内容!

- [x] 你确实可以在浏览器或移动端中观看视频，但不能使用`ykdl`下载。
- [x] 您的`ykdl`为最新版。
- [x] 您已经阅读并按 <https://github.com/zhangn1985/ykdl/wiki> 中的指引进行了操作。
- [x] 您的问题没有在 <https://github.com/zhangn1985/ykdl/issues> 报告，否则请在原有 issue 下报告。
- [x] 本问题确实关于`ykdl`，而不是其他项目。

请将错误输出粘贴在下面:

```
ykdl --debug -i http://www.kankanews.com/a/2018-10-14/0018619539.shtml
DEBUG:common:video_host> www.kankanews.com
DEBUG:common:short_name> kankanews
DEBUG:html:get_content> URL: http://www.kankanews.com/vxml/2018-10-14/0018619539.xml
DEBUG:html:get_content> Charset: utf-8
DEBUG:html:get_content> URL: http://v.kankanews.com/index.php?app=api&mod=public&act=getvideo&id=3224713
Traceback (most recent call last):
  File "D:\PortableApps\Python\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\PortableApps\Python\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\PortableApps\Python\lib\site-packages\cykdl\__main__.py", line 195, in <module>
    main()
  File "D:\PortableApps\Python\lib\site-packages\cykdl\__main__.py", line 173, in main
    info = parser(u)
  File "D:\PortableApps\Python\lib\site-packages\ykdl\extractor.py", line 24, in parser
    info = self.prepare()
  File "D:\PortableApps\Python\lib\site-packages\ykdl\extractors\kankanews.py", line 26, in prepare
    video_data2 = get_content(api2)
  File "D:\PortableApps\Python\lib\site-packages\ykdl\util\html.py", line 67, in get_content
    response = urlopen(req)
  File "D:\PortableApps\Python\lib\urllib\request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "D:\PortableApps\Python\lib\urllib\request.py", line 532, in open
    response = meth(req, response)
  File "D:\PortableApps\Python\lib\urllib\request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "D:\PortableApps\Python\lib\urllib\request.py", line 570, in error
    return self._call_chain(*args)
  File "D:\PortableApps\Python\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "D:\PortableApps\Python\lib\urllib\request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加:

> https://github.com/zhangn1985/ykdl/blob/master/ykdl/extractors/kankanews.py#L25
`http://v.kankanews.com`改成`http://vapi.kankanews.com`即可

**Comment by jindaxia** [comment]
你可以发个pull request?

**Comment by mengmo** [comment]
@jindaxia 不好意思，我这儿实在发不了。
说实话，我要是能发的话，commits 里肯定也不会没我的影儿。
