### ISSUE TITLE
On Python2 HTTPMessage instance has no attribute 'get_payload'

### ISSUE THREAD

**Issue by coslyk** [zhangn1985/ykdl#339]
On Python2 HTTPMessage is based on mimetools.Message, and on Python3 it is based on email.message.Message, so they have different methods.

```
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/liuyikun/Library/Application Support/MoonPlayer/ykdl/cykdl/__main__.py", line 195, in <module>
    main()
  File "/Users/liuyikun/Library/Application Support/MoonPlayer/ykdl/cykdl/__main__.py", line 173, in main
    info = parser(u)
  File "/Users/liuyikun/Library/Application Support/MoonPlayer/ykdl/ykdl/extractor.py", line 24, in parser
    info = self.prepare()
  File "/Users/liuyikun/Library/Application Support/MoonPlayer/ykdl/ykdl/extractors/sohu/sohubase.py", line 90, in prepare
    info = json.loads(get_content(self.apiurl % self.vid))
  File "/Users/liuyikun/Library/Application Support/MoonPlayer/ykdl/ykdl/util/html.py", line 75, in get_content
    payload = resheader.get_payload()
AttributeError: HTTPMessage instance has no attribute 'get_payload'
```

**Comment by SeaHOH** [comment]
91154dfa4a4febb55e8792c675b1831a53636689
