### ISSUE TITLE
虎牙live部分主播无法解析地址

### ISSUE THREAD

**Issue by jn32707** [zhangn1985/ykdl#342]
你好,上个月中开始就出现部分主播在直播,但是下载解析是离线状态,提示live video is offline
比如 www.huya.com/longdd
www.huya.com/931827
www.huya.com/523980
www.huya.com/765262
ykdl已是最新版本,请帮忙检查 谢谢

**Comment by SeaHOH** [comment]
确定不是在回放？

**Comment by jn32707** [comment]
是的,主播在直播中,但是软件里获取状态离线,有一半的主播出现这种状况,比如目前正在直播的http://www.huya.com/lafeng 这个就不行
http://www.huya.com/qiguaijun 这个主播可以识别 但是下载时候报错403

WARNING:common:> url not starts with http(s) www.huya.com/qiguaijun
WARNING:common:> assume http connection!
site:                Huya Live (虎牙直播)
title:               None
artist:              None
streams:
    - format:        current
      container:     mp4
      video-profile: current
    # download-with: ykdl --format=current [URL]
Download: Huya Live (虎牙直播)1208
Traceback (most recent call last):
  File "H:\Python36\Scripts\ykdl-script.py", line 11, in <module>
    load_entry_point('ykdl==1.6.2', 'console_scripts', 'ykdl')()
  File "h:\python36\lib\site-packages\cykdl\__main__.py", line 183, in main
    handle_videoinfo(info)
  File "h:\python36\lib\site-packages\cykdl\__main__.py", line 127, in handle_vi
deoinfo
    download(urls, name, ext, live)
  File "h:\python36\lib\site-packages\cykdl\__main__.py", line 78, in download
    if save_urls(urls, name, ext, jobs = args.jobs):
  File "h:\python36\lib\site-packages\ykdl\util\download.py", line 82, in save_u
rls
    save_url(urls[0], name, ext, status)
  File "h:\python36\lib\site-packages\ykdl\util\download.py", line 47, in save_u
rl
    response = urlopen(req, None)
  File "h:\python36\lib\urllib\request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "h:\python36\lib\urllib\request.py", line 532, in open
    response = meth(req, response)
  File "h:\python36\lib\urllib\request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "h:\python36\lib\urllib\request.py", line 570, in error
    return self._call_chain(*args)
  File "h:\python36\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "h:\python36\lib\urllib\request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

**Comment by SeaHOH** [comment]
可能 API 更新了，我试试看能搞懂不。

**Comment by jn32707** [comment]
好的 谢谢

**Comment by airdge** [comment]
`https://m.huya.com/mgxiaodi`
可以临时用下H5的,抓取M3U8
`  <video id="html5player-video" src="//ws.streamhls.huya.com/hqlive/90000-2635054836-11317474343786643456-1987092182-10057-A-0-1_1200/playlist.m3u8" data-setup='{}'  webkit-playsinline playsinline preload="auto"  width="100%" height="100%" poster="//live-cover.msstatic.com/huyalive/90000-2635054836-11317474343786643456-1987092182-10057-A-0-1/20181021165244.jpg?x-oss-process=image/resize,limit_0,m_fill,w_870,h_448/sharpen,80/format,jpg/interlace,1/quality,q_90">`

PC好像是post
`https://statwup.huya.com/`

**Comment by SeaHOH** [comment]
才发现所有信息都在页面中，可以直接使用。。。

**Comment by jn32707** [comment]
更新live.py后,完美,感谢大佬
