### ISSUE TITLE
site:douyu is failure

### ISSUE THREAD

**Issue by a67878813** [zhangn1985/ykdl#343]
在提交前，请确保您已经检查了以下内容!

- [ ] 你确实可以在浏览器或移动端中观看视频，但不能使用`ykdl`下载。
- [ ] 您的`ykdl`为最新版。
- [ ] 您已经阅读并按 <https://github.com/zhangn1985/ykdl/wiki> 中的指引进行了操作。
- [ ] 您的问题没有在 <https://github.com/zhangn1985/ykdl/issues> 报告，否则请在原有 issue 下报告。
- [ ] 本问题确实关于`ykdl`，而不是其他项目。

u18desk@ubuntu:~$ ykdl -o '/mnt/a' 'https://www.douyu.com/156277'  

Traceback (most recent call last):
  File "/home/u18desk/.local/bin/ykdl", line 11, in <module>
    sys.exit(main())
  File "/home/u18desk/.local/lib/python3.6/site-packages/cykdl/__main__.py", line 173, in main
    info = parser(u)
  File "/home/u18desk/.local/lib/python3.6/site-packages/ykdl/extractor.py", line 24, in parser
    info = self.prepare()
  File "/home/u18desk/.local/lib/python3.6/site-packages/ykdl/extractors/douyu/live.py", line 39, in prepare
    html_content = get_content(api_url)
  File "/home/u18desk/.local/lib/python3.6/site-packages/ykdl/util/html.py", line 67, in get_content
    response = urlopen(req)
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

**Comment by a67878813** [comment]
lacking recognition of  unbroadcast state

**Comment by SeaHOH** [comment]
> lacking recognition of unbroadcast state

I can not understand wath you mean.

**Comment by Erk-** [comment]
I think they mean that it does not detect if the stream is offline.
