### ISSUE TITLE
虎牙某些直播无法观看，Bilibili无法看直播

### ISSUE THREAD

**Issue by YogiLiu** [zhangn1985/ykdl#350]
在提交前，请确保您已经检查了以下内容!

- [OK] 你确实可以在浏览器或移动端中观看视频，但不能使用`ykdl`下载。
- [OK] 您的`ykdl`为最新版。
- [OK] 您已经阅读并按 <https://github.com/zhangn1985/ykdl/wiki> 中的指引进行了操作。
- [OK] 您的问题没有在 <https://github.com/zhangn1985/ykdl/issues> 报告，否则请在原有 issue 下报告。
- [OK] 本问题确实关于`ykdl`，而不是其他项目。

请将错误输出粘贴在下面:
虎牙：
```bash
Failed to recognize file format.
```
Bilibili：
```bash
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
以下是详细日志
虎牙：
```bash
$ ykdl -p mpv --debug https://www.huya.com/660004      
DEBUG:common:video_host> www.huya.com
DEBUG:common:short_name> huya
DEBUG:html:get_content> URL: https://www.huya.com/660004
DEBUG:html:get_content> Charset: utf-8
DEBUG:html:get_content> URL: http://cdn.wup.huya.com/
site:                Huya Live (虎牙直播)
title:               None
artist:              None
streams:
    - format:        current
      container:     mp4
      video-profile: current
    # download-with: ykdl --format=current [URL]
Playing: http://ws4.stream.huya.com/hqlive/78941969-2639420976-11336226772296400896-3120488530-10057-A-0-1.flv?wsSecret=3942840e3748d41d6b59363826d8603f&wsTime=5bf91035
[ffmpeg] NULL: missing picture in access unit with size 248528
[ffmpeg] AVBSFContext: No start code is found.
[lavf] av_find_stream_info() failed
[ffmpeg] NULL: missing picture in access unit with size 248528
[ffmpeg] AVBSFContext: No start code is found.
[lavf] av_find_stream_info() failed
[ytdl_hook] youtube-dl failed: not found or not enough permissions 
Failed to recognize file format.
```
Bilibili：
```bash
$ ykdl -p mpv --debug https://live.bilibili.com/388
DEBUG:common:video_host> live.bilibili.com
DEBUG:common:short_name> bilibili
DEBUG:html:get_content> URL: https://api.live.bilibili.com/room/v1/Room/room_init?id=388
DEBUG:html:get_content> Charset: utf-8
DEBUG:html:get_content> URL: https://api.live.bilibili.com/room/v1/Room/get_info?room_id=5096&from=room
DEBUG:html:get_content> Charset: utf-8
DEBUG:html:get_content> URL: https://api.live.bilibili.com/api/playurl?player=1&cid=5096&quality=0&otype=json
DEBUG:html:get_content> Charset: utf-8
Traceback (most recent call last):
  File "/home/yogiliu/.local/bin/ykdl", line 11, in <module>
    load_entry_point('ykdl==1.6.2', 'console_scripts', 'ykdl')()
  File "/home/yogiliu/.local/lib/python3.7/site-packages/cykdl/__main__.py", line 173, in main
    info = parser(u)
  File "/home/yogiliu/.local/lib/python3.7/site-packages/ykdl/extractor.py", line 24, in parser
    info = self.prepare()
  File "/home/yogiliu/.local/lib/python3.7/site-packages/ykdl/extractors/bilibili/live.py", line 48, in prepare
    get_live_info()
  File "/home/yogiliu/.local/lib/python3.7/site-packages/ykdl/extractors/bilibili/live.py", line 31, in get_live_info
    data = json.loads(get_content("{}?player=1&cid={}&quality={}&otype=json".format(api_url, self.vid, q)))
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加:

> 目前虎牙只是在[PCPI S2](https://www.huya.com/pcpis2)的比赛直播无法查看，其他直播间正常

**Comment by zhangn1985** [comment]
bilibili看上去是坏了，似乎改成了websocket，虎牙可能要升级播放器。

**Comment by SeaHOH** [comment]
#342 #344
之前就修复了，编译个新版本发布即可。

**Comment by YogiLiu** [comment]
成功解决
```bash
pip install --user -U git+https://github.com/zhangn1985/ykdl.git
```
