### ISSUE TITLE
当前master版本无法执行 cannot import name 'encode_for_wrap'

### ISSUE THREAD

**Issue by scegg** [zhangn1985/ykdl#354]
当前master获得的代码，执行py setup.py install后，执行ykdl会报错

Traceback (most recent call last):
  File "C:\Program Files\Python36\Scripts\ykdl-script.py", line 11, in <module>
    load_entry_point('ykdl==1.6.2', 'console_scripts', 'ykdl')()
  File "C:\Program Files\Python36\lib\site-packages\pkg_resources\__init__.py", line 565, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "C:\Program Files\Python36\lib\site-packages\pkg_resources\__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "C:\Program Files\Python36\lib\site-packages\pkg_resources\__init__.py", line 2291, in load
    return self.resolve()
  File "C:\Program Files\Python36\lib\site-packages\pkg_resources\__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "C:\Program Files\Python36\lib\site-packages\ykdl-1.6.2-py3.6.egg\cykdl\__main__.py", line 30, in <module>
  File "C:\Program Files\Python36\lib\site-packages\ykdl-1.6.2-py3.6.egg\ykdl\util\download.py", line 10, in <module>
ImportError: cannot import name 'encode_for_wrap'

**Comment by SeaHOH** [comment]
这是还没有 merge 的代码。。。

**Comment by scegg** [comment]
嗯，下载到的文件一次就只有917504字节。。。每个分段都是。
我也是在下风味人间6
