### ISSUE TITLE
火猫解析失效

### ISSUE THREAD

**Issue by TaoziDB** [zhangn1985/ykdl#358]
在提交前，请确保您已经检查了以下内容!

- [x] 你确实可以在浏览器或移动端中观看视频，但不能使用`ykdl`下载。
- [x] 您的`ykdl`为最新版。
- [x] 您已经阅读并按 <https://github.com/zhangn1985/ykdl/wiki> 中的指引进行了操作。
- [x] 您的问题没有在 <https://github.com/zhangn1985/ykdl/issues> 报告，否则请在原有 issue 下报告。
- [x] 本问题确实关于`ykdl`，而不是其他项目。

请将错误输出粘贴在下面:

```
c:\temp>ykdl -i --debug http://www.huomao.com/587556
DEBUG:common:video_host> www.huomao.com
DEBUG:common:short_name> huomao
DEBUG:html:get_content> URL: http://www.huomao.com/587556
DEBUG:html:get_content> Charset: UTF-8
DEBUG:html:get_content> URL: https://www.huomao.com/swf/live_data
DEBUG:html:get_content> Charset: utf-8
Traceback (most recent call last):
  File "c:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\Scripts\ykdl-script.py", line 11, in <module>
    load_entry_point('ykdl==1.6.2', 'console_scripts', 'ykdl')()
  File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\site-packages\cykdl\__main__.py", line 173, in main
    info = parser(u)
  File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\site-packages\ykdl\extractor.py", line 24, in parser
    info = self.prepare()
  File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\site-packages\ykdl\extractors\huomao.py", line 36, in prepare
    assert stream_data["roomStatus"] == "1", "The live stream is not online! "
KeyError: 'roomStatus'
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加:

> [您的内容]

**Comment by SeaHOH** [comment]
增加了 aes 验证，看起来不像标准方法，所以虽然混淆的力度很轻，但是改起来好麻烦。
有人愿意修复的话，可以 RP。

**Comment by airdge** [comment]
url:
`https://www.huomao.com/swf/live_data`

post表单
```
cdns: 1
streamtype: live
VideoIDS: WI6BG4SclbCdPB1rN1uKXDN3kw
from: huomaoh5room
time: 1544708036
token: f85f2ff2c1e46ef3f8a9f74381214913
```
相关js函数
```
            init: function(b, a, c) {
                var d = md5(b[encry[10]] + encry[11] + a + v());
                $[encry[20]]({
                    type: encry[9],
                    data: {
                        cdns: 1,
                        streamtype: encry[21],
                        cid: b[encry[22]],
                        VideoIDS: b[encry[10]],
                        district: b[encry[23]],
                        country: b[encry[24]],
                        from: encry[11],
                        time: a,
                        token: d
                    },
                    url: encry[25],
                    success: function(a) {
                        c(a)
                    }
                })
            }
```
token计算方式
`md5(b[encry[10]] + encry[11] + a + v());`

其中b为window对象
`var encry = ["length", "AES_ExpandKey: Only key lengths of 16, 24 or 32 bytes allowed!", "slice", "concat", "", "fromCharCode", "hmh5", "initdata", "encode", "POST", "stream", "huomaoh5room", "/CdnVerification/stream_refresh", "parse", "status", "success", "time", "data", "getTime", "url", "ajax", "live", "cid", "province", "country", "/swf/live_data"];`

v()好像是固定值:
`6FE26D855E1AEAE090E243EB1AF73685`

VideoIDS=stream 

所以salt应该为
`stream+'huomaoh5room' + time+'6FE26D855E1AEAE090E243EB1AF73685'`

验证
```
md5('WI6BG4SclbCdPB1rN1uKXDN3kw' + 'huomaoh5room' + '1544708036' + '6FE26D855E1AEAE090E243EB1AF73685'
)


f85f2ff2c1e46ef3f8a9f74381214913
```
