### ISSUE TITLE
ValueError: invalid literal for int() with base 10: ''

### ISSUE THREAD

**Issue by mengmo** [zhangn1985/ykdl#366]
```
ykdl -h
/data/data/com.termux/files/usr/bin/sh: 1: getconf: not found
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/ykdl", line 11, in <module>
    load_entry_point('ykdl==1.6.3', 'console_scripts', 'ykdl')()
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/cykdl/__main__.py", line 28, in <module>
    from ykdl.util.wrap import launch_player, launch_ffmpeg, launch_ffmpeg_download
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/ykdl/util/wrap.py", line 20, in <module>
    ARG_MAX = int(os.popen('getconf ARG_MAX').read())
ValueError: invalid literal for int() with base 10: ''
```
```
env
LD_LIBRARY_PATH=/data/data/com.termux/files/usr/lib
LANG=en_US.UTF-8
PREFIX=/data/data/com.termux/files/usr
PWD=/data/data/com.termux/files/home
HOME=/data/data/com.termux/files/home
TMPDIR=/data/data/com.termux/files/usr/tmp
SHELL=/data/data/com.termux/files/usr/bin/bash
TERM=xterm-256color
SHLVL=1
ANDROID_ROOT=/system
ANDROID_DATA=/data
EXTERNAL_STORAGE=/sdcard
PATH=/data/data/com.termux/files/usr/bin:/data/data/com.termux/files/usr/bin/applets
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
_=/data/data/com.termux/files/usr/bin/env
```

**Comment by SeaHOH** [comment]
`getconf ARG_MAX` 是什么结果？

**Comment by mengmo** [comment]
好吧，我傻了
这玩意儿居然默认没装`getconf` ……
