### ISSUE TITLE
youku 下载有问题

### ISSUE THREAD

**Issue by mengmo** [zhangn1985/ykdl#37]
```
ykdl http://v.youku.com/v_show/id_XMTYzMDc4NTg3Ng==.html
site:                优酷 (Youku)
title:               数码宝贝失落的进化，EP1一本正经乱翻译
artist:              None
streams:
    - format:        TD
      container:     flv
      video-profile: 超清
      size:          370.7 MiB (388679322 bytes)
    # download-with: ykdl --format=TD [URL]
Download: 数码宝贝失落的进化，EP1一本正经乱翻译_TD part 0
 100%
Download: 数码宝贝失落的进化，EP1一本正经乱翻译_TD part 1
Traceback (most recent call last):
  File "yk_dl.py", line 148, in <module>
  File "yk_dl.py", line 136, in main
  File "yk_dl.py", line 90, in handle_videoinfo
  File "yk_dl.py", line 69, in download
  File "site-packages\ykdl\util\download.py", line 61, in save_urls
  File "site-packages\ykdl\util\download.py", line 28, in save_url
  File "urllib\request.py", line 161, in urlopen
  File "urllib\request.py", line 470, in open
  File "urllib\request.py", line 580, in http_response
  File "urllib\request.py", line 508, in error
  File "urllib\request.py", line 442, in _call_chain
  File "urllib\request.py", line 588, in http_error_default
urllib.error.HTTPError: HTTP Error 403: Forbidden
Failed to execute script yk_dl
```
另外，我这里`you-get`正常

**Comment by mengmo** [comment]
```
ykdl http://v.youku.com/v_show/id_XMTYzMDc4NTg3Ng==.html
site:                优酷 (Youku)
title:               数码宝贝失落的进化，EP1一本正经乱翻译
artist:              None
streams:
    - format:        TD
      container:     flv
      video-profile: 超清
      size:          370.7 MiB (388679322 bytes)
    # download-with: ykdl --format=TD [URL]
Download: 数码宝贝失落的进化，EP1一本正经乱翻译_TD part 0
 100%
Download: 数码宝贝失落的进化，EP1一本正经乱翻译_TD part 1
 100%
Download: 数码宝贝失落的进化，EP1一本正经乱翻译_TD part 2
Traceback (most recent call last):
  File "yk_dl.py", line 148, in <module>
  File "yk_dl.py", line 136, in main
  File "yk_dl.py", line 90, in handle_videoinfo
  File "yk_dl.py", line 69, in download
  File "site-packages\ykdl\util\download.py", line 61, in save_urls
  File "site-packages\ykdl\util\download.py", line 28, in save_url
  File "urllib\request.py", line 161, in urlopen
  File "urllib\request.py", line 470, in open
  File "urllib\request.py", line 580, in http_response
  File "urllib\request.py", line 508, in error
  File "urllib\request.py", line 442, in _call_chain
  File "urllib\request.py", line 588, in http_error_default
urllib.error.HTTPError: HTTP Error 403: Forbidden
Failed to execute script yk_dl
```
说实话，我是不能理解到底是哪儿的原因才会出现这种情况

**Comment by mengmo** [comment]
之前说过用`you-get`正常，看了一下解析出来的URL，会不会是这个原因呢？
```
ykdl -i http://v.youku.com/v_show/id_XMTYzMDc4NTg3Ng==.html
site:                优酷 (Youku)
title:               数码宝贝失落的进化，EP1一本正经乱翻译
artist:              None
streams:
    - format:        TD
      container:     flv
      video-profile: 超清
      size:          370.7 MiB (388679322 bytes)
    # download-with: ykdl --format=TD [URL]
Real urls:
http://42.236.62.183/youku/6572A90C4814D84800363F33E4/0300010A005779D92821042BDEA8B6B3140A48-458E-EACE-99FB-CEB7FB93E8F7.flv
http://123.6.0.182/youku/6975FC5BCC54C739984815A41/0300010A015779D92821042BDEA8B6B3140A48-458E-EACE-99FB-CEB7FB93E8F7.flv
http://42.236.62.113/youku/677552187CD3C837E52774627F/0300010A025779D92821042BDEA8B6B3140A48-458E-EACE-99FB-CEB7FB93E8F7.flv
http://42.236.62.72/youku/6775FC5B6454784250EB314133/0300010A035779D92821042BDEA8B6B3140A48-458E-EACE-99FB-CEB7FB93E8F7.flv
http://42.236.62.175/youku/65755218C5C3C837E535BE6EFA/0300010A045779D92821042BDEA8B6B3140A48-458E-EACE-99FB-CEB7FB93E8F7.flv
http://42.236.62.112/youku/6978A56799D3B836F2A00C3600/0300010A055779D92821042BDEA8B6B3140A48-458E-EACE-99FB-CEB7FB93E8F7.flv
http://123.6.0.174/youku/69794FAA6C43B72C8A2186C7B/0300010A065779D92821042BDEA8B6B3140A48-458E-EACE-99FB-CEB7FB93E8F7.flv
http://42.236.62.171/youku/6778A567D324E848F2BA163AB8/0300010A075779D92821042BDEA8B6B3140A48-458E-EACE-99FB-CEB7FB93E8F7.flv
http://42.236.62.141/youku/67794FAADB44E848F2B110484B/0300010A085779D92821042BDEA8B6B3140A48-458E-EACE-99FB-CEB7FB93E8F7.flv
http://42.236.62.174/youku/697B4E734B63382F5E72C6317A/0300010A095779D92821042BDEA8B6B3140A48-458E-EACE-99FB-CEB7FB93E8F7.flv
```
```
you-get -u http://v.youku.com/v_show/id_XMTYzMDc4NTg3Ng==.html
site:                优酷 (Youku)
title:               数码宝贝失落的进化，EP1一本正经乱翻译
stream:
    - format:        hd2
      container:     flv
      video-profile: 超清
      size:          370.7 MiB (388679322 bytes)
    # download-with: you-get --format=hd2 [URL]

Real URLs:
http://123.6.0.109/youku/6773FD927593D72E125B15E9E/0300010A005779D92821042BDEA8B6B3140A48-458E-EACE-99FB-CEB7FB93E8F7.flv
http://27.221.23.185/youku/6975FC5BD7F40837F4BCE13842/0300010A015779D92821042BDEA8B6B3140A48-458E-EACE-99FB-CEB7FB93E8F7.flv
http://27.221.99.111/youku/6573FD927DA4A840EC185D5D05/0300010A025779D92821042BDEA8B6B3140A48-458E-EACE-99FB-CEB7FB93E8F7.flv
http://27.221.23.140/youku/6574A7D5D0C3582E2F8EB261CE/0300010A035779D92821042BDEA8B6B3140A48-458E-EACE-99FB-CEB7FB93E8F7.flv
http://27.221.48.173/youku/657552184714D843880B47416B/0300010A045779D92821042BDEA8B6B3140A48-458E-EACE-99FB-CEB7FB93E8F7.flv
http://27.221.98.173/youku/677750E1B264C842B337DD4910/0300010A055779D92821042BDEA8B6B3140A48-458E-EACE-99FB-CEB7FB93E8F7.flv
http://27.221.23.176/youku/6576A69E4284B841B9DF522277/0300010A065779D92821042BDEA8B6B3140A48-458E-EACE-99FB-CEB7FB93E8F7.flv
http://27.221.99.236/youku/6778A5676683D8355C77753ACD/0300010A075779D92821042BDEA8B6B3140A48-458E-EACE-99FB-CEB7FB93E8F7.flv
http://27.221.48.178/youku/6577FB24EF24483B88C7E16165/0300010A085779D92821042BDEA8B6B3140A48-458E-EACE-99FB-CEB7FB93E8F7.flv
http://27.221.23.143/youku/6578A567FC442839BB73226D95/0300010A095779D92821042BDEA8B6B3140A48-458E-EACE-99FB-CEB7FB93E8F7.flv
```

**Comment by zhangn1985** [comment]
你是在哪个地方？国内还是国外？

**Comment by zhangn1985** [comment]
ykdl 和 you-get在 Youku的算法上基本相同，只是在最后链接拼接上略有不同。刚看了一下IP，解析出来的IP都是联通的。

**Comment by mengmo** [comment]
我仔细想了想，很可能是优酷的`CDN`的锅

**Comment by zhangn1985** [comment]
油库CDN会经常返回404，但403还真少见。那我关了哦。
