### ISSUE TITLE
斗鱼 返回 401 Unauthorized

### ISSUE THREAD

**Issue by a67878813** [zhangn1985/ykdl#374]
在提交前，请确保您已经检查了以下内容!

- [x] 你确实可以在浏览器或移动端中观看视频，但不能使用`ykdl`下载。
- [x] 您的`ykdl`为最新版。
- [x] 您已经阅读并按 <https://github.com/zhangn1985/ykdl/wiki> 中的指引进行了操作。
- [x] 您的问题没有在 <https://github.com/zhangn1985/ykdl/issues> 报告，否则请在原有 issue 下报告。
- [x] 本问题确实关于`ykdl`，而不是其他项目。

请将错误输出粘贴在下面:

```
[在这里粘贴完整日志]
```

Traceback (most recent call last):
  File "/usr/local/bin/ykdl", line 9, in <module>
    load_entry_point('ykdl==1.6.2', 'console_scripts', 'ykdl')()
  File "/usr/local/lib/python3.5/dist-packages/ykdl-1.6.2-py3.5.egg/cykdl/__main__.py", line 173, in main
  File "/usr/local/lib/python3.5/dist-packages/ykdl-1.6.2-py3.5.egg/ykdl/extractor.py", line 24, in parser
  File "/usr/local/lib/python3.5/dist-packages/ykdl-1.6.2-py3.5.egg/ykdl/extractors/douyu/live.py", line 39, in prepare
  File "/usr/local/lib/python3.5/dist-packages/ykdl-1.6.2-py3.5.egg/ykdl/util/html.py", line 67, in get_content
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 510, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 401: Unauthorized

> [您的内容]

**Comment by guest6379** [comment]
please refer to https://github.com/streamlink/streamlink/issues/2328
