### ISSUE TITLE
这是什么情况？是我的python安装有问题吗？

### ISSUE THREAD

**Issue by jiangcm** [zhangn1985/ykdl#388]
ubuntu16.04 arm 

jiang@localhost:~$ ykdl https://www.douyu.com/156277
Traceback (most recent call last):
  File "/home/jiang/.local/bin/ykdl", line 10, in <module>
    sys.exit(main())
  File "/home/jiang/.local/lib/python3.5/site-packages/cykdl/__main__.py", line    173, in main
    info = parser(u)
  File "/home/jiang/.local/lib/python3.5/site-packages/ykdl/extractor.py", line    24, in parser
    info = self.prepare()
  File "/home/jiang/.local/lib/python3.5/site-packages/ykdl/extractors/douyu/liv   e.py", line 39, in prepare
    html_content = get_content(api_url)
  File "/home/jiang/.local/lib/python3.5/site-packages/ykdl/util/html.py", line    67, in get_content
    response = urlopen(req)
  File "/usr/lib/python3.5/urllib/request.py", line 162, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 471, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 581, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 509, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 443, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 589, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

**Comment by SeaHOH** [comment]
更新版本至 master。

**Comment by yoyosnart** [comment]
> 更新版本至 master。

您好 , 我有台电脑 更新至master后正常使用中
但另一台更新至master后 出现此迅息

C:\Users\Egg>ykdl https://www.douyu.com/138243
Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\runpy.py", line 193, in _run_module_as_main

    "__main__", mod_spec)
  File "c:\programdata\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\Scripts\ykdl.exe\__main__.py", line 5, in <modu
le>
  File "c:\programdata\anaconda3\lib\site-packages\cykdl\__main__.py", line 24,
in <module>
    from ykdl.common import url_to_module
  File "c:\programdata\anaconda3\lib\site-packages\ykdl\common.py", line 7, in <
module>
    from .util.html import get_location
  File "c:\programdata\anaconda3\lib\site-packages\ykdl\util\html.py", line 6, i
n <module>
    from ykdl.compact import Request, urlopen
  File "c:\programdata\anaconda3\lib\site-packages\ykdl\compact.py", line 9, in
<module>
    from urllib.request import Request, urlopen, HTTPSHandler, build_opener, HTT
PCookieProcessor, install_opener, ProxyHandler
ImportError: cannot import name 'HTTPSHandler' from 'urllib.request' (c:\program
data\anaconda3\lib\urllib\request.py)

连单纯输入 ykdl 都会报错

**Comment by SeaHOH** [comment]
请检查你的 python 是否正确安装，是否能正常运行以下代码？
```py
import ssl
```

**Comment by yoyosnart** [comment]
> 请检查你的 python 是否正确安装，是否能正常运行以下代码？
> 
> ```python
> import ssl
> ```

解决了 果然是 pip ssl 问题 谢谢楼主
