### ISSUE TITLE
已经更新到 master 但 ykdl 整个无法使用

### ISSUE THREAD

**Issue by yoyosnart** [zhangn1985/ykdl#389]
如题 , 麻烦大佬帮忙看看 是哪边出问题了

C:\Users\Egg>ykdl https://www.douyu.com/138243
Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\runpy.py", line 193, in _run_module_as_main

    "__main__", mod_spec)
  File "c:\programdata\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\Scripts\ykdl.exe\__main__.py", line 5, in <modu
le>
  File "c:\programdata\anaconda3\lib\site-packages\cykdl\__main__.py", line 24,
in <module>
    from ykdl.common import url_to_module
  File "c:\programdata\anaconda3\lib\site-packages\ykdl\common.py", line 7, in <
module>
    from .util.html import get_location
  File "c:\programdata\anaconda3\lib\site-packages\ykdl\util\html.py", line 6, i
n <module>
    from ykdl.compact import Request, urlopen
  File "c:\programdata\anaconda3\lib\site-packages\ykdl\compact.py", line 9, in
<module>
    from urllib.request import Request, urlopen, HTTPSHandler, build_opener, HTT
PCookieProcessor, install_opener, ProxyHandler
ImportError: cannot import name 'HTTPSHandler' from 'urllib.request' (c:\program
data\anaconda3\lib\urllib\request.py)

**Comment by SeaHOH** [comment]
https://github.com/zhangn1985/ykdl/issues/388#issuecomment-472836310
