### ISSUE TITLE
不能下载爱奇艺视频?

### ISSUE THREAD

**Issue by yxyxyxyxyx** [zhangn1985/ykdl#395]
在提交前，请确保您已经检查了以下内容!

- [x] 你确实可以在浏览器或移动端中观看视频，但不能使用`ykdl`下载。
- [x] 您的`ykdl`为最新版。
- [x] 您已经阅读并按 <https://github.com/zhangn1985/ykdl/wiki> 中的指引进行了操作。
- [x] 您的问题没有在 <https://github.com/zhangn1985/ykdl/issues> 报告，否则请在原有 issue 下报告。
- [x] 本问题确实关于`ykdl`，而不是其他项目。

请将错误输出粘贴在下面:

``
C:\Users\Bz>ykdl https://www.iqiyi.com/v_19rsi8wwkk.html
Traceback (most recent call last):
  File "C:\Users\Bz\AppData\Local\Programs\Python\Python35-32\Scripts\ykdl-script.py", line 11, in <module>
    load_entry_point('ykdl==1.6.2', 'console_scripts', 'ykdl')()
  File "c:\users\bz\appdata\local\programs\python\python35-32\lib\site-packages\cykdl\__main__.py", line 173, in main
    info = parser(u)
  File "c:\users\bz\appdata\local\programs\python\python35-32\lib\site-packages\ykdl\extractor.py", line 24, in parser
    info = self.prepare()
  File "c:\users\bz\appdata\local\programs\python\python35-32\lib\site-packages\ykdl\extractors\iqiyi.py", line 85, in prepare
    vps_data = getvps(tvid, vid)
  File "c:\users\bz\appdata\local\programs\python\python35-32\lib\site-packages\ykdl\extractors\iqiyi.py", line 46, in getvps
    html = get_content(req_url)
  File "c:\users\bz\appdata\local\programs\python\python35-32\lib\site-packages\ykdl\util\html.py", line 67, in get_content
    response = urlopen(req)
  File "c:\users\bz\appdata\local\programs\python\python35-32\lib\urllib\request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "c:\users\bz\appdata\local\programs\python\python35-32\lib\urllib\request.py", line 472, in open
    response = meth(req, response)
  File "c:\users\bz\appdata\local\programs\python\python35-32\lib\urllib\request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "c:\users\bz\appdata\local\programs\python\python35-32\lib\urllib\request.py", line 510, in error
    return self._call_chain(*args)
  File "c:\users\bz\appdata\local\programs\python\python35-32\lib\urllib\request.py", line 444, in _call_chain
    result = func(*args)
  File "c:\users\bz\appdata\local\programs\python\python35-32\lib\urllib\request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400: Bad Request

```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加:

> 想要下载这个视频 https://www.iqiyi.com/v_19rsi8wwkk.html

**Comment by coslyk** [comment]
更新到最新版
```
pip install -U git+https://github.com/zhangn1985/ykdl@master
```

**Comment by yxyxyxyxyx** [comment]
出现这个怎么办呢

C:\Users\Bz>pip install -U git+https://github.com/zhangn1985/ykdl@master
Collecting git+https://github.com/zhangn1985/ykdl@master
  Cloning https://github.com/zhangn1985/ykdl (to revision master) to c:\users\bz\appdata\local\temp\pip-req-build-m5de57zq
  Error [WinError 2] The system cannot find the file specified while executing command git clone -q https://github.com/zhangn1985/ykdl C:\Users\Bz\AppData\Local\Temp\pip-req-build-m5de57zq
Cannot find command 'git' - do you have 'git' installed and in your PATH?

需要pip install -git?

**Comment by coslyk** [comment]
那就
```
pip install -U https://github.com/zhangn1985/ykdl/archive/master.zip
```

**Comment by yxyxyxyxyx** [comment]
啊! 好像可以了! 

但是为什么不能直接 pip install --upgrade ykdl 呢?

**Comment by BigMangos** [comment]
> 啊! 好像可以了!
> 
> 但是为什么不能直接 pip install --upgrade ykdl 呢?

pypi没有提交最新的wheel
