### ISSUE TITLE
無法下載愛奇藝

### ISSUE THREAD

**Issue by hlc67** [zhangn1985/ykdl#398]
在提交前，请确保您已经检查了以下内容!

- [v] 你确实可以在浏览器或移动端中观看视频，但不能使用`ykdl`下载。
- [v] 您的`ykdl`为最新版。
- [v] 您已经阅读并按 <https://github.com/zhangn1985/ykdl/wiki> 中的指引进行了操作。
- [v] 您的问题没有在 <https://github.com/zhangn1985/ykdl/issues> 报告，否则请在原有 issue 下报告。
- [v] 本问题确实关于`ykdl`，而不是其他项目。

请将错误输出粘贴在下面:
C:\Users\flora>ykdl --proxy 123.117.169.1:8060 https://tw.iqiyi.com/v_19rr8yispg
.html
Traceback (most recent call last):
  File "C:\Users\flora\AppData\Local\Programs\Python\Python37-32\Scripts\ykdl-sc
ript.py", line 11, in <module>
    load_entry_point('ykdl==1.6.3', 'console_scripts', 'ykdl')()
  File "c:\users\flora\appdata\local\programs\python\python37-32\lib\site-packag
es\cykdl\__main__.py", line 173, in main
    info = parser(u)
  File "c:\users\flora\appdata\local\programs\python\python37-32\lib\site-packag
es\ykdl\extractor.py", line 24, in parser
    info = self.prepare()
  File "c:\users\flora\appdata\local\programs\python\python37-32\lib\site-packag
es\ykdl\extractors\iqiyi\video.py", line 150, in prepare
    get_vid()
  File "c:\users\flora\appdata\local\programs\python\python37-32\lib\site-packag
es\ykdl\extractors\iqiyi\video.py", line 122, in get_vid
    html = get_content(self.url)
  File "c:\users\flora\appdata\local\programs\python\python37-32\lib\site-packag
es\ykdl\util\html.py", line 67, in get_content
    response = urlopen(req)
  File "c:\users\flora\appdata\local\programs\python\python37-32\lib\urllib\requ
est.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "c:\users\flora\appdata\local\programs\python\python37-32\lib\urllib\requ
est.py", line 525, in open
    response = self._open(req, data)
  File "c:\users\flora\appdata\local\programs\python\python37-32\lib\urllib\requ
est.py", line 543, in _open
    '_open', req)
  File "c:\users\flora\appdata\local\programs\python\python37-32\lib\urllib\requ
est.py", line 503, in _call_chain
    result = func(*args)
  File "c:\users\flora\appdata\local\programs\python\python37-32\lib\urllib\requ
est.py", line 1360, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "c:\users\flora\appdata\local\programs\python\python37-32\lib\urllib\requ
est.py", line 1317, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "c:\users\flora\appdata\local\programs\python\python37-32\lib\http\client
.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "c:\users\flora\appdata\local\programs\python\python37-32\lib\http\client
.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "c:\users\flora\appdata\local\programs\python\python37-32\lib\http\client
.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "c:\users\flora\appdata\local\programs\python\python37-32\lib\http\client
.py", line 1016, in _send_output
    self.send(msg)
  File "c:\users\flora\appdata\local\programs\python\python37-32\lib\http\client
.py", line 956, in send
    self.connect()
  File "c:\users\flora\appdata\local\programs\python\python37-32\lib\http\client
.py", line 1384, in connect
    super().connect()
  File "c:\users\flora\appdata\local\programs\python\python37-32\lib\http\client
.py", line 932, in connect
    self._tunnel()
  File "c:\users\flora\appdata\local\programs\python\python37-32\lib\http\client
.py", line 906, in _tunnel
    (version, code, message) = response._read_status()
  File "c:\users\flora\appdata\local\programs\python\python37-32\lib\http\client
.py", line 278, in _read_status
    raise BadStatusLine(line)
http.client.BadStatusLine: <html>

```
[在这里粘贴完整日志]
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加: 

> 因在台灣，有使用代理，還是無法下載。想要下载这个视频 https://tw.iqiyi.com/v_19rr8yispg.html

**Comment by SeaHOH** [comment]
像是你的代理有特殊状况，换一个代理或者直连试试。

**Comment by hlc67** [comment]
> 
> 
> 像是你的代理有特殊状况，换一个代理或者直连试试。

換了個代理，可以了，謝謝!

**Comment by hlc67** [comment]
> 
> 
> 像是你的代理有特殊状况，换一个代理或者直连试试。
最後還是下載失敗。雖然換了代理有連上，但跑出This is a slow video!
很像是被限速了，下載進度一直停留在1%，之後就下載失敗了。直連也無法下。

**Comment by SeaHOH** [comment]
> 但跑出This is a slow video!

这是腾讯视频 #368 ，老问题了。

**Comment by hlc67** [comment]
> 
> 
> > 但跑出This is a slow video!
> 
> 这是腾讯视频 #368 ，老问题了。

請問沒有其他方法可以順利下載嗎? 謝謝。

**Comment by coolroach** [comment]
Traceback (most recent call last):
  File "yk_dl.py", line 195, in <module>
  File "yk_dl.py", line 173, in main
  File "site-packages\ykdl\extractor.py", line 24, in parser
  File "site-packages\ykdl\extractors\iqiyi.py", line 96, in prep
  File "site-packages\ykdl\util\html.py", line 67, in get_content
  File "urllib\request.py", line 161, in urlopen
  File "urllib\request.py", line 469, in open
  File "urllib\request.py", line 579, in http_response
  File "urllib\request.py", line 507, in error
  File "urllib\request.py", line 441, in _call_chain
  File "urllib\request.py", line 587, in http_error_default
urllib.error.HTTPError: HTTP Error 405: Not Allowed
[10132] Failed to execute script yk_dl

我想請問一下 若要使用VIP的視頻 , 我改了 uid 及 authkey 還是無法

**Comment by SeaHOH** [comment]
没有研究，这个工具也不会添加此类功能。

**Comment by coolroach** [comment]
Traceback (most recent call last):
  File "yk_dl.py", line 195, in <module>
  File "yk_dl.py", line 173, in main
  File "site-packages\ykdl\extractor.py", line 24, in pa
  File "site-packages\ykdl\extractors\iqiyi.py", line 85
  File "site-packages\ykdl\extractors\iqiyi.py", line 46
  File "site-packages\ykdl\util\html.py", line 67, in ge
  File "urllib\request.py", line 161, in urlopen
  File "urllib\request.py", line 469, in open
  File "urllib\request.py", line 579, in http_response
  File "urllib\request.py", line 507, in error
  File "urllib\request.py", line 441, in _call_chain
  File "urllib\request.py", line 587, in http_error_defa
urllib.error.HTTPError: HTTP Error 400: Bad Request
[6800] Failed to execute script yk_dl


似乎台版 出現問題
請問有無解決方案

**Comment by SeaHOH** [comment]
注意你的版本

**Comment by coolroach** [comment]
thanks to help
謝謝你的幫忙

**Comment by coolroach** [comment]
Traceback (most recent call last):
  File "yk_dl.py", line 195, in <module>
  File "yk_dl.py", line 173, in main
  File "site-packages\ykdl\extractor.py", line 24, in parser
  File "site-packages\ykdl\extractors\iqiyi.py", line 85, in prepare
  File "site-packages\ykdl\extractors\iqiyi.py", line 46, in getvps
  File "site-packages\ykdl\util\html.py", line 67, in get_content
  File "urllib\request.py", line 161, in urlopen
  File "urllib\request.py", line 469, in open
  File "urllib\request.py", line 579, in http_response
  File "urllib\request.py", line 507, in error
  File "urllib\request.py", line 441, in _call_chain
  File "urllib\request.py", line 587, in http_error_default
urllib.error.HTTPError: HTTP Error 400: Bad Request
[7976] Failed to execute script yk_dl



似乎又出現問題~ 台服

**Comment by coslyk** [comment]
你没更新到最新版

**Comment by coolroach** [comment]
回樓上 , 之前有更新了

**Comment by danny740211** [comment]
已經更新到最新版還是無法下載愛奇藝
F:\ykdl>pip install -U https://github.com/zhangn1985/ykdl/archive/mas
ter.zip
DEPRECATION: Python 3.4 support has been deprecated. pip 19.1 will be the last one supporting it. Please upgrade your Python as Python 3.4 won't be maintained after March 2019 (cf PEP 429).
Collecting https://github.com/zhangn1985/ykdl/archive/master.zip
  Downloading https://github.com/zhangn1985/ykdl/archive/master.zip
     - 2.5MB 20.5MB/s
Requirement already satisfied, skipping upgrade: m3u8 in c:\python34\lib\site-packages (from ykdl==1.6.3) (0.3.8)
Requirement already satisfied, skipping upgrade: pycryptodome in c:\python34\lib\site-packages (from ykdl==1.6.3) (3.8.1)
Requirement already satisfied, skipping upgrade: urllib3 in c:\python34\lib\site-packages (from ykdl==1.6.3) (1.25.2)
Requirement already satisfied, skipping upgrade: iso8601 in c:\python34\lib\site-packages (from m3u8->ykdl==1.6.3) (0.1.12)
Installing collected packages: ykdl
  Found existing installation: ykdl 1.6.2
    Uninstalling ykdl-1.6.2:
      Successfully uninstalled ykdl-1.6.2
  Running setup.py install for ykdl ... done
Successfully installed ykdl-1.6.3

F:\ykdl>ykdl https://tw.iqiyi.com/v_19rsguegno.html
Traceback (most recent call last):
  File "yk_dl.py", line 195, in <module>
  File "yk_dl.py", line 173, in main
  File "site-packages\ykdl\extractor.py", line 24, in parser
  File "site-packages\ykdl\extractors\iqiyi.py", line 85, in prepare
  File "site-packages\ykdl\extractors\iqiyi.py", line 46, in getvps
  File "site-packages\ykdl\util\html.py", line 67, in get_content
  File "urllib\request.py", line 161, in urlopen
  File "urllib\request.py", line 469, in open
  File "urllib\request.py", line 579, in http_response
  File "urllib\request.py", line 507, in error
  File "urllib\request.py", line 441, in _call_chain
  File "urllib\request.py", line 587, in http_error_default
urllib.error.HTTPError: HTTP Error 400: Bad Request
[10160] Failed to execute script yk_dl

**Comment by mengmo** [comment]
@danny740211
先检查一下`…\Python\Scripts`是否在系统环境变量的`Path`中
确保`F:\ykdl`不在系统环境变量的`Path`中
或者`F:\ykdl`在系统环境变量的`Path`中但是没在`…\Python\Scripts`前边

直接打开系统的`命令提示符`使用`ykdl`

要切换下载文件的保存位置，示例：`cd /d F:\Downloads`

最好不要再在`F:\ykdl`目录下使用`ykdl`
如果必须在`F:\ykdl`目录下使用`ykdl`，那就把`F:\ykdl`目录下的`ykdl.exe`重命名未`ykdl.exe.bak`或者直接删掉

@coolroach 你的情况估计与 @danny740211 的一样

**Comment by mengmo** [comment]
@danny740211
其实还有一个方案：研究一下 [PyInstaller](https://www.pyinstaller.org/)
用这儿 https://github.com/zhangn1985/ykdl/wiki/windows-release-script 的方法重新打包一个`ykdl.exe`
替换掉`F:\ykdl`下的`ykdl.exe`
然后就可以按照你以前的习惯来了

**Comment by coolroach** [comment]
@danny740211 
我原本就有更新過了 , 是過了幾天 又不行的~
應該跟設定沒太大關係

**Comment by mengmo** [comment]
> 
> 
> Traceback (most recent call last):
> File "yk_dl.py", line 195, in
> File "yk_dl.py", line 173, in main
> File "site-packages\ykdl\extractor.py", line 24, in parser
> File "site-packages\ykdl\extractors\iqiyi.py", line 85, in prepare
> File "site-packages\ykdl\extractors\iqiyi.py", line 46, in getvps
> File "site-packages\ykdl\util\html.py", line 67, in get_content
> File "urllib\request.py", line 161, in urlopen
> File "urllib\request.py", line 469, in open
> File "urllib\request.py", line 579, in http_response
> File "urllib\request.py", line 507, in error
> File "urllib\request.py", line 441, in _call_chain
> File "urllib\request.py", line 587, in http_error_default
> urllib.error.HTTPError: HTTP Error 400: Bad Request
> [7976] Failed to execute script yk_dl
> 
> 似乎又出現問題~ 台服

@coolroach 这是你贴上来的，注意最后一行
只要出现`yk_dl`就证明你运行的是打包好的可执行文件`ykdl.exe`
只要你没有自行打包可执行文件进行替换，那就肯定不是最新的开发版

**Comment by coslyk** [comment]
通俗的说，你运行的仍然是之前自己下载的旧版ykdl，不是用pip安装的最新版

**Comment by danny740211** [comment]
@mengmo  你說用這個https://github.com/zhangn1985/ykdl/wiki/windows-release-script  製作出來的是yk_dl.exe
測試了一樣不能下載

**Comment by mengmo** [comment]
@danny740211 请先这样测试
`python -m cykdl https://tw.iqiyi.com/v_19rsguegno.html`

网页显示貌似只有台湾地区能看
如果你不在台湾，请挂代理

这个视频好像是 VIP 视频，本项目最多只能下载 5分钟的预览

本项目不支持也没有计划支持 VIP 视频完整下载的功能

**Comment by danny740211** [comment]
@mengmo 謝謝您 
這個指令是只能在python的安裝目錄執行嗎
我的是在台灣地區

**Comment by mengmo** [comment]
@danny740211
如果你在安装 Python 时安装目录没有添加到系统环境变量的 Path 中，那就只能在 Python 的安裝目录中执行

我这儿测试没问题啊
```
python -m cykdl --proxy http://host:port -i https://tw.iqiyi.com/v_19rsguegno.html
site:                爱奇艺 (Iqiyi)
title:               航海王 One piece 第882集
artist:              None
streams:
    - format:        BD
      container:     m3u8
      video-profile: 1080p
    # download-with: ykdl --format=BD [URL]
Real urls:
https://cache.m.iqiyi.com/mus/text/206989601/1467031a2d927e259bcd5c2cb0f30880/afbe8fd3d73448c9/1023108576/20190504/5c/9c/d65aded138c8fcfb9615215076a5a1e9.m3u8?qd_originate=tmts_py&tvid=2349436600&bossStatus=2&qd_vip=0&px=&src=3_31_312&prv=1&previewType=1&previewTime=6&from=&qd_time=1557131863332&qd_p=3b7fa82b&qd_asc=42b6097c311002c43c36dcbe939ea859&qypid=2349436600_04022000001000000000_18&qd_k=42c48c90f1670bd74ce4546ae3211bd0&isdol=0&code=1&ff=265ts&iswb=0&qd_s=otv&vf=f07234dae850e927e3ed04e10bc47d15&np_tag=nginx_part_tag
    - format:        TD
      container:     m3u8
      video-profile: 720p
    # download-with: ykdl --format=TD [URL]
Real urls:
https://cache.m.iqiyi.com/mus/text/206989601/ae232a8496c37e46ac20538a2dc58268/afbe8fd3d73448c9/1023108576/20190504/52/f4/12d8e4c6c6d495640722d3ec9ac2cef5.m3u8?qd_originate=tmts_py&tvid=2349436600&bossStatus=2&qd_vip=0&px=&src=3_31_312&prv=1&previewType=1&previewTime=6&from=&qd_time=1557131862140&qd_p=3b7fa82b&qd_asc=5e9b5b31eaed7da69126c663344e861e&qypid=2349436600_04022000001000000000_17&qd_k=dfc6a511168801f381af5979e8fc8f04&isdol=0&code=1&ff=265ts&iswb=0&qd_s=otv&vf=04290ecf86d2f01f4f61b5f2803bd1b5&np_tag=nginx_part_tag
    - format:        HD
      container:     m3u8
      video-profile: 540p
    # download-with: ykdl --format=HD [URL]
Real urls:
https://cache.m.iqiyi.com/mus/text/206989601/74d8e2d814552b95b4416126c3f49ab9/afbe8fd3d73448c9/1023108576/20190504/93/4a/96ba37cb3373e35dd6f5c0df335dde82.m3u8?qd_originate=tmts_py&tvid=2349436600&bossStatus=2&qd_vip=0&px=&src=3_31_312&prv=1&previewType=1&previewTime=6&from=&qd_time=1557131862141&qd_p=3b7fa82b&qd_asc=e7e70527006c19b26d3eb4a2a6314408&qypid=2349436600_04022000001000000000_14&qd_k=dfc6a511168801f381af5979e8fc8f04&isdol=1&code=2&ff=dbts&iswb=0&qd_s=otv&vf=637878f44627d0c1187f6b6af5f1c889&np_tag=nginx_part_tag
    - format:        SD
      container:     m3u8
      video-profile: 360p
    # download-with: ykdl --format=SD [URL]
Real urls:
https://cache.m.iqiyi.com/mus/text/206989601/5af60268d6329e3b727b40530922933c/afbe8fd3d73448c9/1023108576/20190504/a0/73/028fb1f2adb8828bb677d1e8c5d6fd3e.m3u8?qd_originate=tmts_py&tvid=2349436600&bossStatus=2&qd_vip=0&px=&src=3_31_312&prv=1&previewType=1&previewTime=6&from=&qd_time=1557131862140&qd_p=3b7fa82b&qd_asc=d49a1f14417b31fe696f576eb8acb0af&qypid=2349436600_04022000001000000000_1&qd_k=dfc6a511168801f381af5979e8fc8f04&isdol=0&code=2&ff=f4v&iswb=0&qd_s=otv&vf=aa8a07411e2f0c094742f8b18fb7babe&np_tag=nginx_part_tag
    - format:        LD
      container:     m3u8
      video-profile: 210p
    # download-with: ykdl --format=LD [URL]
Real urls:
https://cache.m.iqiyi.com/mus/text/206989601/3813053fdbc381b24891bffb0ca519a8/afbe8fd3d73448c9/1023108576/20190504/23/31/c4445fcfed0a43effee4e75aa6a523b8.m3u8?qd_originate=tmts_py&tvid=2349436600&bossStatus=2&qd_vip=0&px=&src=3_31_312&prv=1&previewType=1&previewTime=6&from=&qd_time=1557131862141&qd_p=3b7fa82b&qd_asc=df79b438d7b8c0c12698942bb7d2c0c6&qypid=2349436600_04022000001000000000_96&qd_k=dfc6a511168801f381af5979e8fc8f04&isdol=0&code=2&ff=f4v&iswb=0&qd_s=otv&vf=549fe11907368cf84f04a49eee7cded1&np_tag=nginx_part_tag
```

你是不是改过东西？
要不多试几次？

真不行的话，试试这个吧
[ykdl-1.6.3-e47c5a5.zip](https://github.com/zhangn1985/ykdl/files/3147145/ykdl-1.6.3-e47c5a5.zip)

**Comment by danny740211** [comment]
@mengmo 請問你python是裝哪一版
我懷疑是我的python導致的真的都會出錯

**Comment by coslyk** [comment]
和python版本没关系，从你的出错提示就看得出来你运行的仍然是旧版ykdl-------- Ursprüngliche Nachricht --------Betreff: Re: [zhangn1985/ykdl] 無法下載愛奇藝 (#398)Von: danny740211 An: zhangn1985/ykdl Cc: coslyk ,Comment @mengmo 請問你python是裝哪一版

我懷疑是我的python導致的真的都會出錯

**Comment by mengmo** [comment]
@danny740211
Python 3.7.3 和 Python 3.4.4 都没有问题

**Comment by danny740211** [comment]
測試兩台電腦都是一樣的問題都用python 3.4.4
不知道甚麼問題
C:\Users\user>python -m cykdl -i https://tw.iqiyi.com/v_19rsguegno.html
ERROR:YKDL:maximum recursion depth exceeded while calling a Python object

**Comment by mengmo** [comment]
@danny740211
应该与 Python 的版本无关
刚才找了一台电脑，系统为 Windows XP SP3
[ykdl-1.6.3-e47c5a5.zip](https://github.com/zhangn1985/ykdl/files/3147145/ykdl-1.6.3-e47c5a5.zip) 仍然可以正常解析

[ykdl-1.6.3-e47c5a5.zip](https://github.com/zhangn1985/ykdl/files/3147145/ykdl-1.6.3-e47c5a5.zip) 是在 Windows 10 上基于 Python 3.4.4 打的包

你检查一下自己的环境，看看到底是哪儿的配置有问题吧

**Comment by coolroach** [comment]
已經可正常執行 ,但出現了 200多個分段 問題在於?

**Comment by coolroach** [comment]
> 注意你的版本

請問您方便更新一下 新版的EXE嗎

**Comment by mengmo** [comment]
> 
> > 注意你的版本
> 
> 請問您方便更新一下 新版的EXE嗎

最近的几个修改对解析没有影响

另外
https://github.com/zhangn1985/ykdl/wiki/Windows-Build-script 已更新
目前只要 ykdl , PyInstaller 安装好，同时确保 Python 安装位置正确
可以直接运行完成打包

**Comment by coolroach** [comment]
> > > 注意你的版本
> > 
> > 
> > 請問您方便更新一下 新版的EXE嗎
> 
> 最近的几个修改对解析没有影响
> 
> 另外
> https://github.com/zhangn1985/ykdl/wiki/Windows-Build-script 已更新
> 目前只要 ykdl , PyInstaller 安装好，同时确保 Python 安装位置正确
> 可以直接运行完成打包


Traceback (most recent call last):
  File "__main__.py", line 195, in <module>
  File "__main__.py", line 173, in main
  File "site-packages\ykdl\extractor.py", line 24, in parser
  File "site-packages\ykdl\extractors\iqiyi.py", line 83, in prepare
  File "site-packages\ykdl\extractors\iqiyi.py", line 46, in getvps
  File "site-packages\ykdl\util\html.py", line 67, in get_content
  File "urllib\request.py", line 222, in urlopen
  File "urllib\request.py", line 525, in open
  File "urllib\request.py", line 543, in _open
  File "urllib\request.py", line 503, in _call_chain
  File "urllib\request.py", line 1345, in http_open
  File "urllib\request.py", line 1317, in do_open
  File "http\client.py", line 1229, in request
  File "http\client.py", line 1240, in _send_request
  File "http\client.py", line 1107, in putrequest
UnicodeEncodeError: 'ascii' codec can't encode character '\u7b2c' in position 65
2: ordinal not in range(128)
[5288] Failed to execute script __main__


EXE 已經重新設定好打包 , 請問這個問題是?

**Comment by coslyk** [comment]
@coolroach 你仍然是基于旧版打的包，请基于最新版打包

**Comment by coslyk** [comment]
先把你自己手动下载解压的ykdl删掉
然后更新最新版：
```
pip install -U https://github.com/zhangn1985/ykdl/archive/master.zip
```
再执行打包脚本

**Comment by coolroach** [comment]
我已經正確打包了 , 不過目前出現另外兩個問題 , 

可以下載的 卻 切割成 200-300個小碎段

某些出現  無法播放

**Comment by Justsoos** [comment]
@coslyk 
```
pip install -U https://github.com/zhangn1985/ykdl/archive/master.zip
```
这个不写到wiki，或首页Readme里，这是故意「小白退散」的么？

今天发现macos上的ykdl任何版本都无法正常运行douyu，而ubuntu上没问题，并发现，douyu目录copy到早已经过期的 pip 旧安装版下，反而能正常运行。
……
