### ISSUE TITLE
乐视视频无法输出json

### ISSUE THREAD

**Issue by wwqgtxx** [zhangn1985/ykdl#4]
错误如下

**Comment by wwqgtxx** [comment]
`D:\PYTHON\ykdl>@"C:\Program Files (x86)\LieYing\Plugin\PyRun.exe" --normal ykdl -i --json http://www.le.com/ptv/vplay/25047584.html
{'url': 'http://www.le.com/ptv/vplay/25047584.html', 'title': '绝命卦师01', 'vid': '25047584', 'site': '乐视 (Letv)', 'streams': {'720p': {'container': 'm3u8', 'tmp': <tempfile._TemporaryFileWrapper object at 0x02FB18B0>, 'size': 0, 'video_profile': '720p', 'src': ['C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\tmpedu3y43p.m3u8']}, '1300': {'container': 'm3u8', 'tmp': <tempfile._TemporaryFileWrapper object at 0x02FB1A70>, 'size': 0, 'video_profile': '1300', 'src': ['C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\tmpitjzzrvt.m3u8']}, '1080p': {'container': 'm3u8', 'tmp': <tempfile._TemporaryFileWrapper object at 0x02FB1C70>, 'size': 0, 'video_profile': '1080p', 'src': ['C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\tmpj7kj6eom.m3u8']}, '1000': {'container': 'm3u8', 'tmp': <tempfile._TemporaryFileWrapper object at 0x02FB1F90>, 'size': 0, 'video_profile': '1000', 'src': ['C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\tmpqojbw16p.m3u8']}, '350': {'container': 'm3u8', 'tmp': <tempfile._TemporaryFileWrapper object at 0x02FB17F0>, 'size': 0, 'video_profile': '350', 'src': ['C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\tmpy1rgooa0.m3u8']}}}
Traceback (most recent call last):
  File "C:\Program Files (x86)\LieYing\Plugin\Lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Program Files (x86)\LieYing\Plugin\Lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "ykdl\__main__.py", line 6, in <module>
    main()
  File "D:\PYTHON\ykdl\ykdl\__init__.py", line 47, in main
    m.download(u, args)
  File "D:\PYTHON\ykdl\ykdl\extractor.py", line 95, in download
    self.download_normal()
  File "D:\PYTHON\ykdl\ykdl\extractor.py", line 118, in download_normal
    print(json.dumps(self.jsonlize(), indent=4, sort_keys=True, ensure_ascii=False))
  File "C:\Program Files (x86)\LieYing\Plugin\Lib\json\__init__.py", line 237, in dumps
    **kw).encode(obj)
  File "C:\Program Files (x86)\LieYing\Plugin\Lib\json\encoder.py", line 201, in encode
    chunks = list(chunks)
  File "C:\Program Files (x86)\LieYing\Plugin\Lib\json\encoder.py", line 429, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "C:\Program Files (x86)\LieYing\Plugin\Lib\json\encoder.py", line 403, in _iterencode_dict
    yield from chunks
  File "C:\Program Files (x86)\LieYing\Plugin\Lib\json\encoder.py", line 403, in _iterencode_dict
    yield from chunks
  File "C:\Program Files (x86)\LieYing\Plugin\Lib\json\encoder.py", line 403, in _iterencode_dict
    yield from chunks
  File "C:\Program Files (x86)\LieYing\Plugin\Lib\json\encoder.py", line 436, in _iterencode
    o = _default(o)
  File "C:\Program Files (x86)\LieYing\Plugin\Lib\json\encoder.py", line 180, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <tempfile._TemporaryFileWrapper object at 0x02FB1F90> is not JSON serializable`

**Comment by zhangn1985** [comment]
@wwqgtxx 修复这个问题比较简单，只是-json是为了做什么？

**Comment by zhangn1985** [comment]
追加一个fix： https://github.com/zhangn1985/ykdl/commit/5a9faad0107242ea5cb4011eb14d1ae98711183e

**Comment by wwqgtxx** [comment]
为了我的这个项目
https://github.com/wwqgtxx/wwqLyParse

**Comment by zhangn1985** [comment]
希望能帮到你，如果你在使用ykdl时有任何需求，请不要客气。

**Comment by wwqgtxx** [comment]
大家一起共同努力，尽量方便大家下载视频

**Comment by wwqgtxx** [comment]
对了，这个1300 1000 350 是什么清晰度呀，能不能用用户能看得懂的方式显示一下

**Comment by zhangn1985** [comment]
乐视的flash player就这么写的， 你有什么建议吗？

另外，需要在json输出中把m3u8解析出来吗？

**Comment by zhangn1985** [comment]
解析m3u8，json会很长，因为m3u8的分段ts都差不多是3s一个。

**Comment by wwqgtxx** [comment]
要是能解析出来m3u8应该会稳定很多，要不然还要读取一次m3u8文件，增加不确定因素，那三个清晰度估计就是所谓的“极速”“标清”“高清”吧
