### ISSUE TITLE
芒果TV无法解析

### ISSUE THREAD

**Issue by mikejing506** [zhangn1985/ykdl#405]
在提交前，请确保您已经检查了以下内容!

- [x] 你确实可以在浏览器或移动端中观看视频，但不能使用`ykdl`下载。
- [x] 您的`ykdl`为最新版。
- [x] 您已经阅读并按 <https://github.com/zhangn1985/ykdl/wiki> 中的指引进行了操作。
- [x] 您的问题没有在 <https://github.com/zhangn1985/ykdl/issues> 报告，否则请在原有 issue 下报告。
- [x] 本问题确实关于`ykdl`，而不是其他项目。

请将错误输出粘贴在下面:

```
ykdl https://www.mgtv.com/b/309238/3761310.html -i --debug
DEBUG:common:video_host> www.mgtv.com
DEBUG:common:short_name> mgtv
DEBUG:html:get_content> URL: https://pcweb.api.mgtv.com/player/video?video_id=3761310&did=71320e41-255c-41c6-a051-60395348c6fa&tk2=2gTM2MDN2UTNx0Ddpx2Y8FmZ2MGO0MTN5MDM20SM1ATYtYzYxQTLjVTNy0SM0UGMyMTM30DZpRGfxADMw4yMuATPyVmd8BDMwETPv5Gc
DEBUG:html:get_content> Charset: utf8
DEBUG:html:get_content> URL: https://pcweb.api.mgtv.com/player/getSource?video_id=3761310&did=71320e41-255c-41c6-a051-60395348c6fa&pm2=~QnPYr~0Et~XUMvFfI2xtNZSlV2b9JJrxbtZqV0tft3ZHBtntiCBQeEtlavpEvcrzpWyOJK8A4QHzR_TOeXcxIa1dMWgmBqaAQq1Z8sQ6eFVC6eHmRuldVWA2Ep_XYyPjcVT3G0w8VVyVpUxxJuE3hsKwBanECQ_8xJ5VcRxk2EsVCxXYngiqBv5Hsg52CGAJnfXRoRV_8wltoCHIeiiLg7EP08rVvrGdPl~t89n2itxyIXs7OWxA96pgVU~3C1Z&tk2=2gTM2MDN2UTNx0Ddpx2Y8FmZ2MGO0MTN5MDM20SM1ATYtYzYxQTLjVTNy0SM0UGMyMTM30DZpRGfxADMw4yMuATPyVmd8BDMwETPv5Gc
DEBUG:html:get_content> Charset: utf8
Traceback (most recent call last):
  File "C:\Users\mikej\AppData\Local\Programs\Python\Python37\Scripts\ykdl-script.py", line 11, in <module>
    load_entry_point('ykdl==1.6.2', 'console_scripts', 'ykdl')()
  File "c:\users\mikej\appdata\local\programs\python\python37\lib\site-packages\cykdl\__main__.py", line 183, in main
    handle_videoinfo(info)
  File "c:\users\mikej\appdata\local\programs\python\python37\lib\site-packages\cykdl\__main__.py", line 92, in handle_videoinfo
    stream_id = info.stream_types[i]
IndexError: list index out of range
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加:

**Comment by SeaHOH** [comment]
> 在提交前，请确保您已经检查了以下内容!
> 
>     * [x]  你确实可以在浏览器或移动端中观看视频，但不能使用`ykdl`下载。

想下载付费视频请使用其它工具。
