### ISSUE TITLE
遇到了一个BUG

### ISSUE THREAD

**Issue by BruceLu** [zhangn1985/ykdl#412]
在提交前，请确保您已经检查了以下内容!

- [ ] 你确实可以在浏览器或移动端中观看视频，但不能使用`ykdl`下载。
- [ ] 您的`ykdl`为最新版。
- [ ] 您已经阅读并按 <https://github.com/zhangn1985/ykdl/wiki> 中的指引进行了操作。
- [ ] 您的问题没有在 <https://github.com/zhangn1985/ykdl/issues> 报告，否则请在原有 issue 下报告。
- [ ] 本问题确实关于`ykdl`，而不是其他项目。

请将错误输出粘贴在下面:

```
BrucedeMBP:Video brucelu$ ykdl https://v.youku.com/v_show/id_XNDA4NzE0MDM3Ng==.html
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1317, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1016, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 956, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1392, in connect
    server_hostname=server_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 412, in wrap_socket
    session=session
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 853, in _create
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 1117, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/bin/ykdl", line 11, in <module>
    load_entry_point('ykdl==1.6.2', 'console_scripts', 'ykdl')()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/cykdl/__main__.py", line 173, in main
    info = parser(u)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ykdl/extractor.py", line 24, in parser
    info = self.prepare()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ykdl/extractors/youku.py", line 63, in prepare
    api_url = 'https://ups.youku.com/ups/get.json?vid={}&ccode={}&client_ip=192.168.1.1&utid={}&client_ts={}&ckey={}'.format(self.vid, ccode, quote(fetch_cna()), int(time.time()), ckey)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ykdl/extractors/youku.py", line 20, in fetch_cna
    req = urlopen(url)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1360, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1319, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)>
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加:

> [您的内容]

**Comment by coslyk** [comment]
运行`/Applications/Python\ 3.7/Install\ Certificates.command`

**Comment by BruceLu** [comment]
可以使用了。
不过下载下来的文件是flv的，不是很方便，最好能下mp4。

**Comment by mengmo** [comment]
> 不过下载下来的文件是flv的，不是很方便，最好能下mp4。

@BruceLu
如确有需要，可以将这几行里的`flv`改为`mp4`，当然更安全的做法是改为`mkv`
https://github.com/zhangn1985/ykdl/blob/master/ykdl/extractors/youkujs.py#L32
https://github.com/zhangn1985/ykdl/blob/master/ykdl/extractors/youkujs.py#L33
https://github.com/zhangn1985/ykdl/blob/master/ykdl/extractors/youkujs.py#L35

如果觉得比如B站也不想用`flv`，可以在这一行上边
https://github.com/zhangn1985/ykdl/blob/master/ykdl/util/wrap.py#L113
添上这两行
```
        if ext == 'flv':
            ext = 'mp4'
```
同样，更安全的做法是改成`mkv`
```
        if ext == 'flv':
            ext = 'mkv'
```

**Comment by SeaHOH** [comment]
youkujs.py 内的格式最好不要修改，因为直接播放时它不会被转换。
wrap.py 这里可以改，这就是最终要输出的格式。

**Comment by mengmo** [comment]
> youkujs.py 内的格式最好不要修改，因为直接播放时它不会被转换。

@SeaHOH
有个疑问：改`youkujs.py`对直接播放有什么实际影响吗？正常情况下没有哪个播放器是只靠扩展名确定文件类型的吧？
还有就是目前优酷新上传的视频好像都是`mp4`的了，而老的视频还是原样没变，这才是最🥚疼的地方

**Comment by mengmo** [comment]
> wrap.py 这里可以改，这就是最终要输出的格式。

好吧！确实是只改`wrap.py`就行，当时没仔细测试

不过
> 还有就是目前优酷新上传的视频好像都是`mp4`的了，而老的视频还是原样没变，这才是最🥚疼的地方

我还是觉得可🥚疼

**Comment by airdge** [comment]
直接播放输出M3U8就好了  现在播放器都能支持吧

如果都要下载MP4,可以先对stream_type进行排序,再找到最清晰分段mp4的stream_type

**Comment by SeaHOH** [comment]
> > youkujs.py 内的格式最好不要修改，因为直接播放时它不会被转换。
> 
> @SeaHOH
> 有个疑问：改`youkujs.py`对直接播放有什么实际影响吗？正常情况下没有哪个播放器是只靠扩展名判断文件类型的吧？

其实没影响，先前顺手举的例子不太合适，应该是：
不直接使用本工具下载时，格式不会被转换，输出内容应尽量保证正确。

> 还有就是目前优酷新上传的视频好像都是`mp4`的了，而老的视频还是原样没变，这才是最:egg:疼的地方

不过优酷算法搞不定，我也就凑合着用，细节也不在意，反正直接播放。。。

> 直接播放输出M3U8就好了 现在播放器都能支持吧

现在的代码没法直接往 extractors 模块传参数，需要由 extractors 来主动获取参数。
但是各人的需求都不同，这就需要增加参数配置。

现在网络带宽越来越大，基本上没有下载视频到本地播放的需求，直播也能正常下载保存。
所以关于视频格式的细节如果没人提 PR，我是不太在意的，bug 除外。

**Comment by mengmo** [comment]
> > > youkujs.py 内的格式最好不要修改，因为直接播放时它不会被转换。
> >
> > @SeaHOH
> > 有个疑问：改`youkujs.py`对直接播放有什么实际影响吗？正常情况下没有哪个播放器是只靠扩展名判断文件类型的吧？
> 
> 其实没影响，先前顺手举的例子不太合适，应该是：
> 不直接使用本工具下载时，格式不会被转换，输出内容应尽量保证正确。

然而实际上当前的情况是优酷新上传的视频输出结果是错的
而如果改了`youkujs.py`原来的视频输出结果又不对了
> > 还有就是目前优酷新上传的视频好像都是`mp4`的了，而老的视频还是原样没变，这才是最🥚疼的地方
> 
> 不过优酷算法搞不定，我也就凑合着用，细节也不在意，反正直接播放。。。

个人也赞同「在没有搞定优酷算法的情况下修改这些没必要」

从开始到这儿写了这么多主要是想尽可能地不产生误导
