### ISSUE TITLE
不明原因報錯 , 無法使用

### ISSUE THREAD

**Issue by yoyosnart** [zhangn1985/ykdl#413]
在提交前，请确保您已经检查了以下内容!

- [x] 你确实可以在浏览器或移动端中观看视频，但不能使用`ykdl`下载。
- [x] 您的`ykdl`为最新版。
- [x] 您已经阅读并按 <https://github.com/zhangn1985/ykdl/wiki> 中的指引进行了操作。
- [x] 您的问题没有在 <https://github.com/zhangn1985/ykdl/issues> 报告，否则请在原有 issue 下报告。
- [x] 本问题确实关于`ykdl`，而不是其他项目。

请将错误输出粘贴在下面:

```
C:\Users\Pig>ykdl https://www.douyu.com/600290
Traceback (most recent call last):
  File "D:\Python\Python37\Scripts\ykdl-script.py", line 11, in <module>
    load_entry_point('ykdl==1.6.2', 'console_scripts', 'ykdl')()
  File "d:\python\python37\lib\site-packages\cykdl\__main__.py", line 173, in main
    info = parser(u)
  File "d:\python\python37\lib\site-packages\ykdl\extractor.py", line 24, in parser
    info = self.prepare()
  File "d:\python\python37\lib\site-packages\ykdl\extractors\douyu\live.py", line 39, in prepare
    html_content = get_content(api_url)
  File "d:\python\python37\lib\site-packages\ykdl\util\html.py", line 67, in get_content
    response = urlopen(req)
  File "d:\python\python37\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "d:\python\python37\lib\urllib\request.py", line 531, in open
    response = meth(req, response)
  File "d:\python\python37\lib\urllib\request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "d:\python\python37\lib\urllib\request.py", line 569, in error
    return self._call_chain(*args)
  File "d:\python\python37\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "d:\python\python37\lib\urllib\request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加:

> [您的内容]

**Comment by yoyosnart** [comment]
應該是我沒安裝依賴庫 , 我再試試
