### ISSUE TITLE
斗鱼个别房间出错

### ISSUE THREAD

**Issue by Miloxing** [zhangn1985/ykdl#414]
在提交前，请确保您已经检查了以下内容!

- [x] 你确实可以在浏览器或移动端中观看视频，但不能使用`ykdl`下载。
- [x] 您的`ykdl`为最新版。
- [x] 您已经阅读并按 <https://github.com/zhangn1985/ykdl/wiki> 中的指引进行了操作。
- [x] 您的问题没有在 <https://github.com/zhangn1985/ykdl/issues> 报告，否则请在原有 issue 下报告。
- [x] 本问题确实关于`ykdl`，而不是其他项目。

请将错误输出粘贴在下面:

```
ykdl --debug www.douyu.com/290935
WARNING:common:> url not starts with http(s) www.douyu.com/290935
WARNING:common:> assume http connection!
DEBUG:common:video_host> www.douyu.com
DEBUG:common:short_name> douyu
DEBUG:html:get_content> URL: http://www.douyu.com/290935
DEBUG:html:get_content> Charset: UTF-8
DEBUG:html:get_content> URL: https://www.douyu.com/swf_api/homeH5Enc?rids=290935
DEBUG:html:get_content> Charset: UTF-8
Gjs-Message: JS WARNING: [/tmp/execjsnh3p0rqd.js 5]: variable n redeclares argument
Gjs-Message: JS WARNING: [/tmp/execjsnh3p0rqd.js 9]: function ub98484234 does not always return a value
Gjs-Message: JS WARNING: [/tmp/execjsnh3p0rqd.js 10]: assignment to undeclared variable result
Gjs-Message: JS WARNING: [/tmp/execjsr884c6hi.js 5]: variable n redeclares argument
Gjs-Message: JS WARNING: [/tmp/execjsr884c6hi.js 9]: function ub98484234 does not always return a value
Traceback (most recent call last):
  File "/usr/local/bin/ykdl", line 11, in <module>
    load_entry_point('ykdl==1.6.3', 'console_scripts', 'ykdl')()
  File "/usr/local/lib/python3.5/dist-packages/ykdl-1.6.3-py3.5.egg/cykdl/__main__.py", line 178, in main
  File "/usr/local/lib/python3.5/dist-packages/ykdl-1.6.3-py3.5.egg/ykdl/extractor.py", line 24, in parser
  File "/usr/local/lib/python3.5/dist-packages/ykdl-1.6.3-py3.5.egg/ykdl/extractors/douyu/live.py", line 78, in prepare
  File "/usr/local/lib/python3.5/dist-packages/ykdl-1.6.3-py3.5.egg/ykdl/util/jsengine.py", line 132, in call
  File "/usr/local/lib/python3.5/dist-packages/ykdl-1.6.3-py3.5.egg/ykdl/util/jsengine.py", line 171, in _eval
  File "/usr/local/lib/python3.5/dist-packages/ykdl-1.6.3-py3.5.egg/ykdl/util/jsengine.py", line 187, in _exec
ykdl.util.jsengine.ProgramError: ReferenceError: document is not defined
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加:

> 只有个别房间出错，而且是特定的房间，不知道是什么原因，比如周淑怡的直播间290935，斗鱼靓号22222，难道和靓号有关吗

**Comment by SeaHOH** [comment]
`ub98484234` 函数强制返回了一个 `undefined` 值，网页调试也没看出来是怎么回事，应该没有调用 `ub98484234`。

**Comment by BigMangos** [comment]
和靓号有关，直接传入真实room_id才行

**Comment by SeaHOH** [comment]
room_id 是对的，但是现在参数没法验证，不知道是用那个函数进行签名的。

**Comment by BigMangos** [comment]
`var sck=RegExp,ros=document,tsg=window;`
js执行时需要document和window对象，其他id就不需要，真实奇怪

**Comment by airdge** [comment]
```
     var k = [0x29cdabf1, 0x4ac282f3, 0x119208be, 0x67aabb84];
     var rs;
     var wea = 251;
     var nc = 105; 
     while ((nc < 405) && (wea < 371)) {
```
在浏览器打印nc和nodejs打印nc
`105,2,256,387,59,327,161,386,179,99,36,376,294,229,107,13,282,329,330,182,118,95,290,372,98,122,69,86,73,354,259,222,193,323,55,341,366,114,142,336,205,150,43,230,6,219,312,140,248,233,331,128,177,3,79,134,389,181,93,37,369,350,310,29,241,160,4,75,301,385,156,28,325,211,180,268,138,347,123,0,260,87,289,393,378,14,58,304,173,353,7,172,103,283,166,145,72,313,34,27,306,108,115,246,286,148,249,360,89,238,9,239,185,203,137,262,71,5,270,297,266,154,159,377,68,398,227,365,144,308,243,183,39,23,106,263,363,235,317,215,47,141,315,204,97,133,8,401,348,395,188,326,382,321,338,228,242,175,187,76,151,220,209,276,381,337,339,126,362,240,379,287,207,357,92,74,184,70,49,397,80,305,279,202,51,303,402,66,264,52,212,280,221,274,232,35,277,139,53,78,267,396,25,394,400,24,223,31,355,117,373,26,41,218,155,15,162,278,62,388,250,170,342,311,251,11,1,104,361,265,112,324,195,136,375,399,101,21,225,124,302,50,261,174,143,171,237,374,127,288,245,255,272,383,163,380,352,349,335,226,332,273,109,65,213,30,343,404,192,390,210,269,102,224,384,85,199,391,81,149,17,358,77,328,333,19,320,113,12,318,253,125,100,10,56,247,130,299,57,334,119,359,293,64,88,368,135,236,164,351,307,271,168,284,45,16,295,147,300,345,234,18,94,346,206,217,356,258,252,90,214,200,364,178,186,38,176,33,322,116,120,285,63,189,54,257,403,32,110,132,275,296,121,201,146,165,111,129,190,244,216,67,291,198,292,84,20,83,61,131,158,370,191,319,60,46,91,196,314,392,340,153,157,22,281,254,208,48,42,169,371,316,344,167,298,152,96,309,231,40,194,44,197,367`

```
105,2,256,387,59,327,161,386,179,99,36,376,294,229,107,13,282,329,330,182,118,95,290,372,98,122,69,86,73,354,259,222,193,323,55,341,366,114,142,336,205,150,43,230,6,219,312,140,248,233,331,128,177,3,79,134,389,181,93,37,369,350,310,29,241,160,4,75,301,385,156,28,325,211,180,268,138,347,123,0,260,87,289,393,378,14,58,304,173,353,7,172,103,283,166,145,72,313,34,27,306,108,115,246,286,148,249,360,89,238,9,239,185,203,137,262,71,5,270,297,266,154,159,377,68,398,227,365,144,308,243,183,39,23,106,263,363,235,317,215,47,141,315,204,97,133,8,401,348,395,188,326,382,321,338,228,242,175,187,76,151,220,209,276,381,337,339,126,362,240,379,287,207,357,92,74,184,70,49,397,80,305,279,202,51,303,402,66,264,52,212,280,221,274,232,35,277,139,53,78,267,396,25,394,400,24,223,31,355,117,373,26,41,218,155,15,162,278,62,388,250,170,342,311,251,11,1,104,361,265,112,324,195

105,2,256,387,59,327,161,386,179,99,36,376,294,229,107,13,282,329,330,182,118,95,290,372,98,122,69,86,73,354,259,222,193,323,55,341,366,114,142,336,205,150,43,230,6,219,312,140,248,233,331,128,177,3,79,134,389,181,93,37,369,350,310,29,241,160,4,75,301,385,156,28,325,211,180,268,138,347,123,0,260,87,289,393,378,14,58,304,173,353,7,172,103,283,166,145,72,313,34,27,306,108,115,246,286,148,249,360,89,238,9,239,185,203,137,262,71,5,270,297,266,154,159,377,68,398,227,365,144,308,243,183,39,23,106,263,363,235,317,215,47,141,315,204,97,133,8,401,348,395,188,326,382,321,338,228,242,175,187,76,151,220,209,276,381,337,339,126,362,240,379,287,207,357,92,74,184,70,49,397,80,305,279,202,51,303,402,66,264,52,212,280,221,274,232,35,277,139,53,78,267,396,25,394,400,24,223,31,355,117,373,26,41,218,155,15,162,278,62,388,250,170,342,311,251,11,1,104,361,265,112,324,195,136,375,399,101,21,225,124,302,50,261,174,143,171,237,374,127,288,245,255,272,383,163,380,352,349,335,226,332,273,109,65,213,30,343,404,192,390,210,269,102,224,384,85,199,391,81,149,17,358,77,328,333,19,320,113,12,318,253,125,100,10,56,247,130,299,57,334,119,359,293,64,88,368,135,236,164,351,307,271,168,284,45,16,295,147,300,345,234,18,94,346,206,217,356,258,252,90,214,200,364,178,186,38,176,33,322,116,120,285,63,189,54,257,403,32,110,132,275,296,121,201,146,165,111,129,190,244,216,67,291,198,292,84,20,83,61,131,158,370,191,319,60,46,91,196,314,392,340,153,157,22,281,254,208,48,42,169,371,316,344,167,298,152,96,309,231,40,194
```
在 case 195 和 case 194 处中断了,可以获取到
```
var re=oog[otc](tsg[wtf]);v[230]+=lk[0];!re && (function(){ wea=400;})();
var re=tog[cns](ros[dtf]);v[398]-=lk[0];!re && (function(){ wea=400;})();
```
其中tsg[wtf]和ros[dtf]指向window.close和document.close
如果没有实体DOM,re为false,wea赋值400,中断switch流程 (re为true,wea=251;)
理论是可以在这两个case的break前添加wea=251;
但不确定是不是每个ub98484234都在case 195 和case 194处中断

所以好一点的做法应该是看有没有库能将eval还原
```
(function(xx0, xx1, xx2) {
	var cb = xx0 + xx1 + xx2 + "220520190530";
	var rb = CryptoJS.MD5(cb).toString();
	var re = [];
	for (var i = 0; i < rb.length / 8; i++) re[i] = (parseInt(rb.substr(i * 8, 2), 16) & 0xff) | ((parseInt(rb.substr(i * 8 + 2, 2), 16) << 8) & 0xff00) | ((parseInt(rb.substr(i * 8 + 4, 2), 16) << 24) >>> 8) | (parseInt(rb.substr(i * 8 + 6, 2), 16) << 24);
	var k2 = [0x60bacceb, 0x15f6f3fa, 0x7a4080, 0x33349a08];
	for (var I = 0; I < 2; I++) {
		var v0 = re[I * 2],
			v1 = re[I * 2 + 1],
			sum = 0,
			i = 0;
		var delta = 0x9e3779b9;
		for (i = 0; i < 32; i++) {
			sum += delta;
			v0 += ((v1 << 4) + k2[0]) ^ (v1 + sum) ^ ((v1 >>> 5) + k2[1]);
			v1 += ((v0 << 4) + k2[2]) ^ (v0 + sum) ^ ((v0 >>> 5) + k2[3]);
		}
		re[I * 2] = v0;
		re[I * 2 + 1] = v1;
	}
	re[0] += k2[0];
	re[0] = (re[0] << (k2[2] % 16)) | (re[0] >>> (32 - (k2[2] % 16)));
	re[0] += k2[2];
	re[0] ^= k2[2];
	re[1] += k2[1];
	re[1] = (re[1] << (k2[3] % 16)) | (re[1] >>> (32 - (k2[3] % 16)));
	re[1] = (re[1] >>> (k2[3] % 16)) | (re[1] << (32 - (k2[3] % 16)));
	re[2] = (re[2] >>> (k2[0] % 16)) | (re[2] << (32 - (k2[0] % 16)));
	re[2] ^= k2[2];
	re[2] ^= k2[0];
	re[2] = (re[2] >>> (k2[2] % 16)) | (re[2] << (32 - (k2[2] % 16)));
	re[2] ^= k2[2];
	re[3] -= k2[1];
	re[3] ^= k2[3];
	re[3] -= k2[3];
	re[3] += k2[3];
	re[0] = (re[0] << (k2[0] % 16)) | (re[0] >>> (32 - (k2[0] % 16)));
	re[0] += k2[2];
	re[0] = (re[0] << (k2[2] % 16)) | (re[0] >>> (32 - (k2[2] % 16)));
	re[0] ^= k2[2];
	re[1] = (re[1] >>> (k2[1] % 16)) | (re[1] << (32 - (k2[1] % 16)));
	re[1] = (re[1] << (k2[3] % 16)) | (re[1] >>> (32 - (k2[3] % 16)));
	re[1] -= k2[3];
	re[2] ^= k2[0];
	re[2] -= k2[2];
	re[2] -= k2[2];
	re[3] -= k2[1];
	re[3] += k2[3];
	re[3] += k2[1];
	re[3] = (re[3] >>> (k2[3] % 16)) | (re[3] << (32 - (k2[3] % 16))); {
		var hc = '0123456789abcdef'.split('');
		for (var i = 0; i < re.length; i++) {
			var j = 0,
				s = '';
			for (; j < 4; j++) s += hc[(re[i] >> (j * 8 + 4)) & 15] + hc[(re[i] >> (j * 8)) & 15];
			re[i] = s;
		}
		re = re.join('');
	}
	var rt = "v=220520190530" + "&did=" + xx1 + "&tt=" + xx2 + "&sign=" + re;
	return rt;
});
```

**Comment by BigMangos** [comment]
@airdge case编号每个房间都不一样，得到的最终的rt计算函数也不一样，只是其他房间没有使用window.close和document.close

**Comment by SeaHOH** [comment]
> 所以好一点的做法应该是看有没有库能将eval还原

javascript 太难搞了，没法像 python 一样 path eval。

**Comment by airdge** [comment]
@SeaHOH 
如果各房间的代码段都差不多,
可以做eval(xxx)的全部替换 
本地测试差不多可行,但还有小问题得处理 

![图片](https://user-images.githubusercontent.com/7813960/58748950-3f25d580-84b2-11e9-81b6-3291746f05df.png)

**Comment by BigMangos** [comment]
目前还有其他房间需要document和window对象吗，好像只有那一个，特殊处理一下即可

**Comment by SeaHOH** [comment]
直接替换源码有点麻烦，可能会处理不完全，我再考虑下。

**Comment by airdge** [comment]
替换源码应该不影响,不会影响之前的Py执行
只要判断下 ub98484234是不是正常的字符串就行了
如果没生成ub98484234,就执行替换过的js
![图片](https://user-images.githubusercontent.com/7813960/58755711-df641480-851b-11e9-8691-9e88f361bbea.png)
![图片](https://user-images.githubusercontent.com/7813960/58755715-e8ed7c80-851b-11e9-93f8-ad66b5aad158.png)

**Comment by airdge** [comment]
![图片](https://user-images.githubusercontent.com/7813960/58794258-5b4c8280-862a-11e9-815a-afe5a006dac2.png)


代码中差不多有三种混淆形式
只能针对性的还原两种形式,还是有一种有问题
如果有需求,还是IDA反编译so库比较好,看下app的算法

**Comment by DayChan** [comment]
> 替换源码应该不影响,不会影响之前的Py执行
> 只要判断下 ub98484234是不是正常的字符串就行了
> 如果没生成ub98484234,就执行替换过的js
> ![图片](https://user-images.githubusercontent.com/7813960/58755711-df641480-851b-11e9-8691-9e88f361bbea.png)
> ![图片](https://user-images.githubusercontent.com/7813960/58755715-e8ed7c80-851b-11e9-93f8-ad66b5aad158.png)

这个是如何做到的？我目前正好想要获取22222的流地址，有没有临时的解决方法，Thanks！
