### ISSUE TITLE
爱奇艺下载VIP报错

### ISSUE THREAD

**Issue by toorich** [zhangn1985/ykdl#415]
在提交前，请确保您已经检查了以下内容!

- [x] 你确实可以在浏览器或移动端中观看视频，但不能使用`ykdl`下载。
- [x] 您的`ykdl`为最新版。
- [x] 您已经阅读并按 <https://github.com/zhangn1985/ykdl/wiki> 中的指引进行了操作。
- [x] 您的问题没有在 <https://github.com/zhangn1985/ykdl/issues> 报告，否则请在原有 issue 下报告。
- [x] 本问题确实关于`ykdl`，而不是其他项目。

请将错误输出粘贴在下面:
PS C:\Windows\system32> ykdl -i https://www.iqiyi.com/v_19rrfnx3s4.html
Traceback (most recent call last):
  File "E:\Program Files\Python37\Scripts\ykdl-script.py", line 11, in <module>
    load_entry_point('ykdl==1.6.2', 'console_scripts', 'ykdl')()
  File "e:\program files\python37\lib\site-packages\cykdl\__main__.py", line 173, in main
    info = parser(u)
  File "e:\program files\python37\lib\site-packages\ykdl\extractor.py", line 24, in parser
    info = self.prepare()
  File "e:\program files\python37\lib\site-packages\ykdl\extractors\iqiyi.py", line 94, in prepare
    json_data=json.loads(get_content(url))
  File "e:\program files\python37\lib\site-packages\ykdl\util\html.py", line 67, in get_content
    response = urlopen(req)
  File "e:\program files\python37\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "e:\program files\python37\lib\urllib\request.py", line 531, in open
    response = meth(req, response)
  File "e:\program files\python37\lib\urllib\request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "e:\program files\python37\lib\urllib\request.py", line 569, in error
    return self._call_chain(*args)
  File "e:\program files\python37\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "e:\program files\python37\lib\urllib\request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 405: Not Allowed
[在这里粘贴完整日志]
PS C:\Windows\system32> ykdl -i https://www.iqiyi.com/v_19rrfnx3s4.html --debug
DEBUG:common:video_host> www.iqiyi.com
DEBUG:common:short_name> iqiyi
DEBUG:html:get_content> URL: https://www.iqiyi.com/v_19rrfnx3s4.html
DEBUG:html:get_content> Charset: UTF-8
DEBUG:html:get_content> URL: http://cache.video.qiyi.com/vps?tvid=906523400&vid=28b0c2ea3bfc5d4efdd5da5a6e5ec884&v=0&qypid=906523400_12&src=01012001010000000000&t=1558968187351&k_tag=1&k_uid=yw470iw2lans5ae2ua8a224qxq19g2y5&rs=1&vf=66d10d66f3e4e8b29cdd93a7f6939250
DEBUG:html:get_content> Charset: utf-8
DEBUG:html:get_content> URL: http://data.video.iqiyi.com/videos/v0/20190419/86/f8/29b1bf36d6e63bac7ab9fa5ff13f0502.f4v?qd_tvid=906523400&qd_vipres=2&qd_index=1&qd_aid=218214801&qd_stert=0&qd_scc=69402e193bfc109ee9a719fed28448cd&qd_sc=247a72240d3478eb489edc6108967311&qd_p=7509bea8&qd_ip=7509bea8&qd_k=66d10d66f3e4e8b29cdd93a7f6939250&qd_src=01012001010000000000&qd_vipdyn=2&qd_uid=0&qd_tm=1558968187514&qd_vip=0
Traceback (most recent call last):
  File "E:\Program Files\Python37\Scripts\ykdl-script.py", line 11, in <module>
    load_entry_point('ykdl==1.6.2', 'console_scripts', 'ykdl')()
  File "e:\program files\python37\lib\site-packages\cykdl\__main__.py", line 173, in main
    info = parser(u)
  File "e:\program files\python37\lib\site-packages\ykdl\extractor.py", line 24, in parser
    info = self.prepare()
  File "e:\program files\python37\lib\site-packages\ykdl\extractors\iqiyi.py", line 94, in prepare
    json_data=json.loads(get_content(url))
  File "e:\program files\python37\lib\site-packages\ykdl\util\html.py", line 67, in get_content
    response = urlopen(req)
  File "e:\program files\python37\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "e:\program files\python37\lib\urllib\request.py", line 531, in open
    response = meth(req, response)
  File "e:\program files\python37\lib\urllib\request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "e:\program files\python37\lib\urllib\request.py", line 569, in error
    return self._call_chain(*args)
  File "e:\program files\python37\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "e:\program files\python37\lib\urllib\request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 405: Not Allowed
如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加:
如题，试看部分也无法下载（话说原本fork的项目you-get甚至能解析出试看部分的4K m3u8……）

**Comment by mengmo** [comment]
> * [x]  您已经阅读并按 https://github.com/zhangn1985/ykdl/wiki 中的指引进行了操作。

更新 `pip install -U https://github.com/zhangn1985/ykdl/archive/master.zip`
```
ykdl -i https://www.iqiyi.com/v_19rrfnx3s4.html
site:                爱奇艺 (Iqiyi)
title:               偶像练习生之张艺兴升级严厉制作人 范冰冰弟弟首秀哽咽泪目
artist:              None
streams:
    - format:        4k
      container:     m3u8
      video-profile: 4k
    # download-with: ykdl --format=4k [URL]
Real urls:
https://cache.m.iqiyi.com/mus/text/218214801/bc7d23283845930f993b524d432923d6/afbe8fd3d73448c9/1023108576/20190419/3c/55/1665d3e55a2d194262261efacb675a33.m3u8?qd_originate=tmts_py&tvid=906523400&bossStatus=2&qd_vip=0&px=&src=3_31_312&prv=1&previewType=1&previewTime=6&from=&qd_time=1558970173696&qd_p=2aecd648&qd_asc=c2f8947769341f0924b5f8bf9acae79e&qypid=906523400_04022000001000000000_10&qd_k=fc47389c0820f2cf29e5d0d5002e811e&isdol=0&code=2&ff=f4v&iswb=0&qd_s=otv&vf=d0894f0ecf6204d43d3e8baebdde26f7&np_tag=nginx_part_tag
```
```
ykdl -h
usage: ykdl [-h] [-l] [-i] [-J] [-F FORMAT] [-o OUTPUT_DIR] [-O OUTPUT_NAME]
            [-p PLAYER] [--proxy PROXY] [-t TIMEOUT] [--no-merge] [-s START]
            [-j JOBS] [--debug]
            video_urls [video_urls ...]

YouKuDownLoader(ykdl 1.6.3), a video downloader. Forked form you-get
0.3.34@soimort
```

**Comment by toorich** [comment]
> > * [x]   您的`ykdl`为最新版。
> > * [x]   您已经阅读并按 https://github.com/zhangn1985/ykdl/wiki 中的指引进行了操作。
> 
> 更新 `pip install -U https://github.com/zhangn1985/ykdl/archive/master.zip`
> 
> ```
> ykdl -i https://www.iqiyi.com/v_19rrfnx3s4.html
> site:                爱奇艺 (Iqiyi)
> title:               偶像练习生之张艺兴升级严厉制作人 范冰冰弟弟首秀哽咽泪目
> artist:              None
> streams:
>     - format:        4k
>       container:     m3u8
>       video-profile: 4k
>     # download-with: ykdl --format=4k [URL]
> Real urls:
> https://cache.m.iqiyi.com/mus/text/218214801/bc7d23283845930f993b524d432923d6/afbe8fd3d73448c9/1023108576/20190419/3c/55/1665d3e55a2d194262261efacb675a33.m3u8?qd_originate=tmts_py&tvid=906523400&bossStatus=2&qd_vip=0&px=&src=3_31_312&prv=1&previewType=1&previewTime=6&from=&qd_time=1558970173696&qd_p=2aecd648&qd_asc=c2f8947769341f0924b5f8bf9acae79e&qypid=906523400_04022000001000000000_10&qd_k=fc47389c0820f2cf29e5d0d5002e811e&isdol=0&code=2&ff=f4v&iswb=0&qd_s=otv&vf=d0894f0ecf6204d43d3e8baebdde26f7&np_tag=nginx_part_tag
> ```
> 
> ```
> ykdl -h
> usage: ykdl [-h] [-l] [-i] [-J] [-F FORMAT] [-o OUTPUT_DIR] [-O OUTPUT_NAME]
>             [-p PLAYER] [--proxy PROXY] [-t TIMEOUT] [--no-merge] [-s START]
>             [-j JOBS] [--debug]
>             video_urls [video_urls ...]
> 
> YouKuDownLoader(ykdl 1.6.3), a video downloader. Forked form you-get
> 0.3.34@soimort
> ```

emmm……之前我一直用的是`pip install --upgrade ykdl`……
