### ISSUE TITLE
acfun的视频解析失败

### ISSUE THREAD

**Issue by Jaqen00** [zhangn1985/ykdl#430]
在提交前，请确保您已经检查了以下内容!

- [ ] 你确实可以在浏览器或移动端中观看视频，但不能使用`ykdl`下载。
- [ ] 您的`ykdl`为最新版。
- [ ] 您已经阅读并按 <https://github.com/zhangn1985/ykdl/wiki> 中的指引进行了操作。
- [ ] 您的问题没有在 <https://github.com/zhangn1985/ykdl/issues> 报告，否则请在原有 issue 下报告。
- [ ] 本问题确实关于`ykdl`，而不是其他项目。

请将错误输出粘贴在下面:
C:\Users\Yan>ykdl --debug https://www.acfun.cn/v/ac10358404
DEBUG:common:video_host> www.acfun.cn
DEBUG:common:short_name> acfun
DEBUG:html:get_content> URL: https://www.acfun.cn/v/ac10358404
DEBUG:html:get_content> Charset: utf-8
DEBUG:html:get_content> URL: http://www.acfun.cn/video/getVideo.aspx?id=None
Traceback (most recent call last):
  File "C:\Users\Yan\AppData\Local\Programs\Python\Python36\Scripts\ykdl-script.py", line 11, in <module>
    load_entry_point('ykdl==1.6.2', 'console_scripts', 'ykdl')()
  File "c:\users\yan\appdata\local\programs\python\python36\lib\site-packages\cykdl\__main__.py", line 173, in main
    info = parser(u)
  File "c:\users\yan\appdata\local\programs\python\python36\lib\site-packages\ykdl\embedextractor.py", line 43, in parser
    self.prepare()
  File "c:\users\yan\appdata\local\programs\python\python36\lib\site-packages\ykdl\extractors\acfun.py", line 20, in prepare
    data = json.loads(get_content('http://www.acfun.cn/video/getVideo.aspx?id={}'.format(sourceVid)))
  File "c:\users\yan\appdata\local\programs\python\python36\lib\site-packages\ykdl\util\html.py", line 67, in get_content
    response = urlopen(req)
  File "c:\users\yan\appdata\local\programs\python\python36\lib\urllib\request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "c:\users\yan\appdata\local\programs\python\python36\lib\urllib\request.py", line 532, in open
    response = meth(req, response)
  File "c:\users\yan\appdata\local\programs\python\python36\lib\urllib\request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "c:\users\yan\appdata\local\programs\python\python36\lib\urllib\request.py", line 564, in error
    result = self._call_chain(*args)
  File "c:\users\yan\appdata\local\programs\python\python36\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "c:\users\yan\appdata\local\programs\python\python36\lib\urllib\request.py", line 756, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "c:\users\yan\appdata\local\programs\python\python36\lib\urllib\request.py", line 532, in open
    response = meth(req, response)
  File "c:\users\yan\appdata\local\programs\python\python36\lib\urllib\request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "c:\users\yan\appdata\local\programs\python\python36\lib\urllib\request.py", line 570, in error
    return self._call_chain(*args)
  File "c:\users\yan\appdata\local\programs\python\python36\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "c:\users\yan\appdata\local\programs\python\python36\lib\urllib\request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```

**Comment by SeaHOH** [comment]
你需要更新，方法参考上方 wiki。

**Comment by Jaqen00** [comment]
非常感谢！更新之后可以用了 @SeaHOH
