### ISSUE TITLE
虎牙直播能解析，但是下载时候出现403

### ISSUE THREAD

**Issue by jn32707** [zhangn1985/ykdl#433]
在提交前，请确保您已经检查了以下内容!

- [是] 你确实可以在浏览器或移动端中观看视频，但不能使用`ykdl`下载。
- [是] 您的`ykdl`为最新版。
- [是] 您已经阅读并按 <https://github.com/zhangn1985/ykdl/wiki> 中的指引进行了操作。
- [是] 您的问题没有在 <https://github.com/zhangn1985/ykdl/issues> 报告，否则请在原有 issue 下报告。
- [是] 本问题确实关于`ykdl`，而不是其他项目。

请将错误输出粘贴在下面:
site:                Huya Live (虎牙直播)
title:               None
artist:              None
streams:
    - format:        current
      container:     flv
      video-profile: current
    # download-with: ykdl --format=current [URL]
Download: Huya Live (虎牙直播)6422
Traceback (most recent call last):
  File "D:\Python\Python37-32\Scripts\ykdl-script.py", line 11, in <module>
    load_entry_point('ykdl==1.6.2', 'console_scripts', 'ykdl')()
  File "d:\python\python37-32\lib\site-packages\cykdl\__main__.py", line 183, in main
    handle_videoinfo(info)
  File "d:\python\python37-32\lib\site-packages\cykdl\__main__.py", line 127, in handle_videoinfo
    download(urls, name, ext, live)
  File "d:\python\python37-32\lib\site-packages\cykdl\__main__.py", line 78, in download
    if save_urls(urls, name, ext, jobs = args.jobs):
  File "d:\python\python37-32\lib\site-packages\ykdl\util\download.py", line 82, in save_urls
    save_url(urls[0], name, ext, status)
  File "d:\python\python37-32\lib\site-packages\ykdl\util\download.py", line 47, in save_url
    response = urlopen(req, None)
  File "d:\python\python37-32\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "d:\python\python37-32\lib\urllib\request.py", line 531, in open
    response = meth(req, response)
  File "d:\python\python37-32\lib\urllib\request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "d:\python\python37-32\lib\urllib\request.py", line 569, in error
    return self._call_chain(*args)
  File "d:\python\python37-32\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "d:\python\python37-32\lib\urllib\request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
[y,n]?y
site:                Huya Live (虎牙直播)
title:               None
artist:              None
streams:
    - format:        current
      container:     flv
      video-profile: current
    # download-with: ykdl --format=current [URL]
Download: Huya Live (虎牙直播)9271
Traceback (most recent call last):
  File "D:\Python\Python37-32\Scripts\ykdl-script.py", line 11, in <module>
    load_entry_point('ykdl==1.6.2', 'console_scripts', 'ykdl')()
  File "d:\python\python37-32\lib\site-packages\cykdl\__main__.py", line 183, in main
    handle_videoinfo(info)
  File "d:\python\python37-32\lib\site-packages\cykdl\__main__.py", line 127, in handle_videoinfo
    download(urls, name, ext, live)
  File "d:\python\python37-32\lib\site-packages\cykdl\__main__.py", line 78, in download
    if save_urls(urls, name, ext, jobs = args.jobs):
  File "d:\python\python37-32\lib\site-packages\ykdl\util\download.py", line 82, in save_urls
    save_url(urls[0], name, ext, status)
  File "d:\python\python37-32\lib\site-packages\ykdl\util\download.py", line 47, in save_url
    response = urlopen(req, None)
  File "d:\python\python37-32\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "d:\python\python37-32\lib\urllib\request.py", line 531, in open
    response = meth(req, response)
  File "d:\python\python37-32\lib\urllib\request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "d:\python\python37-32\lib\urllib\request.py", line 569, in error
    return self._call_chain(*args)
  File "d:\python\python37-32\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "d:\python\python37-32\lib\urllib\request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
[y,n]?y
site:                Huya Live (虎牙直播)
title:               None
artist:              None
streams:
    - format:        current
      container:     flv
      video-profile: current
    # download-with: ykdl --format=current [URL]
Download: Huya Live (虎牙直播)9376
0.1MB[y,n]?y
site:                Huya Live (虎牙直播)
title:               None
artist:              None
streams:
    - format:        current
      container:     flv
      video-profile: current
    # download-with: ykdl --format=current [URL]
Download: Huya Live (虎牙直播)3007
0.0MB[y,n]?y
```
[在这里粘贴完整日志]
```
site:                Huya Live (虎牙直播)
title:               None
artist:              None
streams:
    - format:        current
      container:     flv
      video-profile: current
    # download-with: ykdl --format=current [URL]
Now downloading: Huya Live (虎牙直播)3818_2019-07-14T13-59-53.977281.flv
stop downloading by press 'q'
[flv @ 00000000010865a0] audio stream discovered after head already parsed
[flv @ 00000000010865a0] video stream discovered after head already parsed
Input #0, flv, from 'http://txdirect.flv.huya.com/huyalive/78941969-2696454368-11581183325716348928-3232674102-10057-A-0-1.flv?wsSecret=8c33c5671fc1a18e652c328a54b42820&amp;wsTime=5d2ac4cb':
  Metadata:
    level           :
    displayWidth    : 1920
    displayHeight   : 1080
    fps             : 59
    profile         :
    server          : SRS/2.0.234(ZhouGuowen)
    srs_primary     : SRS/1.0release
    srs_authors     : winlin,wenjie.zhao
    server_version  : 2.0.234
    encoder         : Lavf56.40.101
  Duration: 00:00:00.00, start: 143624.371000, bitrate: N/A
    Stream #0:0: Subtitle: text
    Stream #0:1: Audio: aac (HE-AACv2), 44100 Hz, stereo, fltp
    Stream #0:2: Video: h264 (Main), yuv420p, 1920x1080 [SAR 1:1 DAR 16:9], 62.50 fps, 59.94 tbr, 1k tbn, 119.88 tbc
[flv @ 00000000032ff020] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.
    Last message repeated 1 times
Output #0, flv, to 'Huya Live (铏庣墮鐩存挱)3818_2019-07-14T13-59-53.977281.flv':
  Metadata:
    level           :
    displayWidth    : 1920
    displayHeight   : 1080
    fps             : 59
    profile         :
    server          : SRS/2.0.234(ZhouGuowen)
    srs_primary     : SRS/1.0release
    srs_authors     : winlin,wenjie.zhao
    server_version  : 2.0.234
    encoder         : Lavf57.40.101
    Stream #0:0: Video: h264 ([7][0][0][0] / 0x0007), yuv420p, 1920x1080 [SAR 1:1 DAR 16:9], q=2-31, 62.50 fps, 59.94 tbr, 1k tbn, 1k tbc
    Stream #0:1: Audio: aac (HE-AACv2) ([10][0][0][0] / 0x000A), 44100 Hz, stereo
Stream mapping:
  Stream #0:2 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
frame=  118 fps=0.0 q=-1.0 Lsize=    1957kB time=00:00:02.11 bitrate=7575.1kbits/s speed=100x
video:1947kB audio:6kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.186061%
[y,n]?y
site:                Huya Live (虎牙直播)
title:               None
artist:              None
streams:
    - format:        current
      container:     flv
      video-profile: current
    # download-with: ykdl --format=current [URL]
Now downloading: Huya Live (虎牙直播)5_2019-07-14T13-59-56.239284.flv
stop downloading by press 'q'
[http @ 0000000000da6d20] HTTP error 403 Forbidden
http://al.flv.huya.com/backsrc/78941969-2558924260-10990496009641000960-3143878788-10057-A-0-1.flv?wsSecret=f5076aaf33c2e5d6d244dfff49bbb83a&amp;wsTime=5d2ac4cb: Server returned 403 Forbidden (access denied)
如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加:

> [您的内容]
这几天开始出现这个问题，比如在下载https://www.huya.com/kpl 频道时候，下载一秒就会断开，保存的文件可播放，时间只有2秒

**Comment by SeaHOH** [comment]
#431 已修复，自己更新。
