### ISSUE TITLE
通过代理执行 ykdl 报错 

### ISSUE THREAD

**Issue by yoyosnart** [zhangn1985/ykdl#444]
在提交前，请确保您已经检查了以下内容!

- [V ] 你确实可以在浏览器或移动端中观看视频，但不能使用`ykdl`下载。
- [ V] 您的`ykdl`为最新版。
- [ V] 您已经阅读并按 <https://github.com/zhangn1985/ykdl/wiki> 中的指引进行了操作。
- [V ] 您的问题没有在 <https://github.com/zhangn1985/ykdl/issues> 报告，否则请在原有 issue 下报告。
- [ V] 本问题确实关于`ykdl`，而不是其他项目。

请将错误输出粘贴在下面:

```
Microsoft Windows [版本 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Windows\System32>ykdl https://www.douyu.com/101 --debug
[0x77B59000] ANOMALY: meaningless REX prefix used
[0x77B59000] ANOMALY: meaningless REX prefix used
DEBUG:common:video_host> www.douyu.com
DEBUG:common:short_name> douyu
DEBUG:html:get_content> URL: https://www.douyu.com/101
DEBUG:html:get_content> Charset: UTF-8
DEBUG:html:get_content> URL: https://www.douyu.com/swf_api/homeH5Enc?rids=101
DEBUG:html:get_content> Charset: UTF-8
Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\runpy.py", line 193, in _run_module_as_main

    "__main__", mod_spec)
  File "c:\programdata\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\Scripts\ykdl.exe\__main__.py", line 9, in <modu
le>
  File "c:\programdata\anaconda3\lib\site-packages\cykdl\__main__.py", line 178,
 in main
    info = parser(u)
  File "c:\programdata\anaconda3\lib\site-packages\ykdl\extractor.py", line 23,
in parser
    info = self.prepare()
  File "c:\programdata\anaconda3\lib\site-packages\ykdl\extractors\douyu\live.py
", line 132, in prepare
    ub98484234 = js_ctx.call('ub98484234', self.vid, did, tt)
  File "c:\programdata\anaconda3\lib\site-packages\ykdl\util\jsengine.py", line
173, in call
    return self._eval(code)
  File "c:\programdata\anaconda3\lib\site-packages\ykdl\util\jsengine.py", line
232, in _eval
    ret = json.loads(last_line)
  File "c:\programdata\anaconda3\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "c:\programdata\anaconda3\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "c:\programdata\anaconda3\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 3 (char 2)

C:\Windows\System32>
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加:

> 使用了 sockscap 讓 CMD 執行於代理網路下 , 另一台電腦可以正常使用 , 某些電腦則會出現如上面的報錯

**Comment by SeaHOH** [comment]
>   File "c:\programdata\anaconda3\lib\site-packages\ykdl\util\jsengine.py", line
> 232, in _eval
>     ret = json.loads(last_line)

要找到原因，你可以打印 `last_line` 看是什么结果。

**Comment by yoyosnart** [comment]
> > File "c:\programdata\anaconda3\lib\site-packages\ykdl\util\jsengine.py", line
> > 232, in _eval
> > ret = json.loads(last_line)
> 
> 要找到原因，你可以打印 `last_line` 看是什么结果。

该怎么打印 last_line 呢

**Comment by coslyk** [comment]
> > > File "c:\programdata\anaconda3\lib\site-packages\ykdl\util\jsengine.py", line
> > > 232, in _eval
> > > ret = json.loads(last_line)
> > 
> > 
> > 要找到原因，你可以打印 `last_line` 看是什么结果。
> 
> 该怎么打印 last_line 呢

在
```
ret = json.loads(last_line)
```
前面加一行（注意缩进要对齐）：
```
print(last_line)
```

**Comment by yoyosnart** [comment]
谢谢 , print 出来 是显示 这个错误
[0x7FEB4EA2AE0] ANOMALY: meaningless REX prefix used

**Comment by SeaHOH** [comment]
搜了下，这里有篇相关的文章 https://blog.csdn.net/hillseas/article/details/80974006 。
可能和你使用的 sockscap 注入有关，也可能像文章中写的是其它软件替换了系统文件。
