### ISSUE TITLE
突然無法使用 , 不明原因

### ISSUE THREAD

**Issue by yoyosnart** [zhangn1985/ykdl#445]
在提交前，请确保您已经检查了以下内容!

- [V ] 你确实可以在浏览器或移动端中观看视频，但不能使用`ykdl`下载。
- [V ] 您的`ykdl`为最新版。
- [V ] 您已经阅读并按 <https://github.com/zhangn1985/ykdl/wiki> 中的指引进行了操作。
- [ V] 您的问题没有在 <https://github.com/zhangn1985/ykdl/issues> 报告，否则请在原有 issue 下报告。
- [V ] 本问题确实关于`ykdl`，而不是其他项目。

请将错误输出粘贴在下面:

```
Microsoft Windows [版本 10.0.17763.437]
(c) 2018 Microsoft Corporation. 著作權所有，並保留一切權利。

C:\Users\Wayne>ykdl https://www.douyu.com/96291 --debug
DEBUG:common:video_host> www.douyu.com
DEBUG:common:short_name> douyu
DEBUG:html:get_content> URL: https://www.douyu.com/96291
DEBUG:html:get_content> Charset: UTF-8
DEBUG:html:get_content> URL: https://www.douyu.com/swf_api/homeH5Enc?rids=96291
DEBUG:html:get_content> Charset: UTF-8
Traceback (most recent call last):
  File "C:\Users\Wayne\AppData\Local\Programs\Python\Python37-32\Scripts\ykdl-script.py", line 11, in <module>
    load_entry_point('ykdl==1.6.3', 'console_scripts', 'ykdl')()
  File "c:\users\wayne\appdata\local\programs\python\python37-32\lib\site-packages\cykdl\__main__.py", line 178, in main
    info = parser(u)
  File "c:\users\wayne\appdata\local\programs\python\python37-32\lib\site-packages\ykdl\extractor.py", line 23, in parser
    info = self.prepare()
  File "c:\users\wayne\appdata\local\programs\python\python37-32\lib\site-packages\ykdl\extractors\douyu\live.py", line 125, in prepare
    js_ctx = JSEngine()
  File "c:\users\wayne\appdata\local\programs\python\python37-32\lib\site-packages\ykdl\util\jsengine.py", line 184, in __init__
    self.chakra = ChakraHandle()
  File "c:\users\wayne\appdata\local\programs\python\python37-32\lib\site-packages\ykdl\util\jsengine_chakra.py", line 38, in __init__
    stringify = self.eval_js("JSON.stringify;", raw=True)[1]
AttributeError: 'ChakraHandle' object has no attribute 'eval_js
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加:

> [您的内容]

**Comment by SeaHOH** [comment]
先前修改兼容时漏掉了，现已修复。

**Comment by yoyosnart** [comment]
> 先前修改兼容时漏掉了，现已修复。

再更新一次就可以了是嗎
