### ISSUE TITLE
b站解析经常性403错误 you-get没问题

### ISSUE THREAD

**Issue by andysendo** [zhangn1985/ykdl#452]
请将错误输出粘贴在下面:

```
https://www.bilibili.com/video/av49673221/?spm_id_from=333.788.videocard.1

Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/jiangyd/wine/opt/ykdl-master/cykdl/__main__.py", line 200, in <module>
    main()
  File "/home/jiangyd/wine/opt/ykdl-master/cykdl/__main__.py", line 173, in main
    m,u = url_to_module(url)
  File "/home/jiangyd/wine/opt/ykdl-master/ykdl/common.py", line 40, in url_to_module
    site, url = m.get_extractor(url)
  File "/home/jiangyd/wine/opt/ykdl-master/ykdl/extractors/bilibili/__init__.py", line 28, in get_extractor
    url = get_location(url)
  File "/home/jiangyd/wine/opt/ykdl-master/ykdl/util/html.py", line 63, in get_location
    response = get_head_response(url, headers=headers)
  File "/home/jiangyd/wine/opt/ykdl-master/ykdl/util/html.py", line 49, in get_head_response
    response = urlopen(req)
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 563, in error
    result = self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 755, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 563, in error
    result = self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 755, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

you-get解析、下载没问题，但mpv播放必须添加--referrer='xxx'(baidu.com, bibil.com都无所谓)，否则也会403错误。

所以bilibili/__init__.py或util/html.py或什么地方对所有网站解析加上referrer参数？至少b站解析加个referrer参数应该能避免403错，其它网站像iqiyi acfun cntv youku还没遇到403错不需要。

**Comment by andysendo** [comment]
还是有403 
https://www.bilibili.com/video/av62102939/?spm_id_from=333.788.videocard.3

Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/jiangyd/wine/opt/ykdl-master/cykdl/__main__.py", line 216, in <module>
    main()
  File "/home/jiangyd/wine/opt/ykdl-master/cykdl/__main__.py", line 194, in main
    info = parser(u)
  File "/home/jiangyd/wine/opt/ykdl-master/ykdl/extractor.py", line 23, in parser
    info = self.prepare()
  File "/home/jiangyd/wine/opt/ykdl-master/ykdl/extractors/bilibili/bilibase.py", line 48, in prepare
    self.vid, info.title, info.artist = self.get_page_info()
  File "/home/jiangyd/wine/opt/ykdl-master/ykdl/extractors/bilibili/video.py", line 20, in get_page_info
    html = get_content(self.url)
  File "/home/jiangyd/wine/opt/ykdl-master/ykdl/util/html.py", line 86, in get_content
    response = urlopen(req)
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

bilibili/bilibase.py bilibili/video.py

**Comment by SeaHOH** [comment]
能重复吗？you-get 呢？

先执行的 get_location 都通过了，同样的 URL，get_content 就返回 403？
不能理解这个机制，我这里无法重现。

**Comment by andysendo** [comment]
you-get没问题 
ykdl重复3次以上必然403

**Comment by andysendo** [comment]
是不是 get_content 在短时间调用太多 导致连续请求页面 被后台判定强制断开

**Comment by andysendo** [comment]
you-get偶尔/很少也会403，估计原因是一样的，但是"偶尔"

**Comment by SeaHOH** [comment]
> 是不是 get_content 在短时间调用太多 导致连续请求页面 被后台判定强制断开

反复不间断测试几十次，还是无法复现。
也许你可以试试 you-get 使用的 User-Agent。

**Comment by andysendo** [comment]
怎么改呢

**Comment by SeaHOH** [comment]
`fake_headers['User-Agent'] = '***'`

**Comment by andysendo** [comment]
#  info.extra['ua'] = fake_headers['User-Agent']
info.extra['ua'] = 'Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.9 Safari/537.36'

改了以后好像改善了些 但还是比you-get频繁

**Comment by airdge** [comment]
![图片](https://user-images.githubusercontent.com/7813960/65947424-d99b2300-e46a-11e9-87d8-aee836173822.png)

按ykdl的算法  测试好几次 状态码都是200  
`测试默认ua:Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:67.0) Gecko/20100101 Firefox/67.0`

**Comment by andysendo** [comment]
https://www.bilibili.com/video/av62102939/?spm_id_from=333.788.videocard.3
我这里解析地址是  https://upos-hz-mirrorcosu.acgvideo.com/upgcxcode/...

**Comment by SeaHOH** [comment]
> 
> # info.extra['ua'] = fake_headers['User-Agent']
> 
> info.extra['ua'] = 'Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.9 Safari/537.36'
> 
> 改了以后好像改善了些 但还是比you-get频繁

你改错了，按我写的格式添加一行就行。

@airdge 
403 的是 `html = get_content(self.url)` 这里，请求 API 好像没啥限制。
只是怀疑和 UA 有关，我这里复现不了，也许和 CDN 有关呢。

**Comment by airdge** [comment]
![图片](https://user-images.githubusercontent.com/7813960/65949842-89728f80-e46f-11e9-8838-e046dd7e36dc.png)

@SeaHOH 判断的是flv的状态码,并没有判断api
ua和referer设置没有问题

**Comment by SeaHOH** [comment]
对，是结果的状态，刚才没注意看。。。不过报告的是播放页面 403。

**Comment by andysendo** [comment]
这样改？
 def prepare(self):
        ...
        fake_headers['User-Agent'] = '***'
        info.extra['ua'] = fake_headers['User-Agent']

这个时间段只要是搜索的页面  ykdl you-get在我这里全都解析失败了 但白天you-get解析没问题

但是电影首页随便选个页面 https://www.bilibili.com/bangumi/play/ss12642/  ykdl不用改什么解析没任何问题，再频繁都可以

我这里解析地址都是 https://upos-hz-mirrorcosu.acgvideo.com/upgcxcode/...

难道是b站后端有啥过滤算法？

不过，ykdl解析b站算法实现和you-get不同？我这里确实很容易403

**Comment by airdge** [comment]
@andysendo  --debug打印错误的结果看看

**Comment by andysendo** [comment]
[DEBUG] get_content: https://www.bilibili.com/video/av62102939/?spm_id_from=333.788.videocard.3
[DEBUG] HTTP Error with code403
[DEBUG] HTTP Error with code403
[DEBUG] HTTP Error with code403
you-get: version 0.4.1347, a tiny downloader that scrapes the web.
you-get: Namespace(URL=['https://www.bilibili.com/video/av62102939/?spm_id_from=333.788.videocard.3'], auto_rename=False, cookies=None, debug=True, extractor_proxy=None, force=False, format=None, help=False, http_proxy=None, info=False, input_file=None, insecure=False, itag=None, json=False, no_caption=False, no_merge=False, no_proxy=False, output_dir='.', output_filename=None, password=None, player="mpv --referrer='https://www.baidu.com' --merge-files", playlist=False, skip_existing_file_size_check=False, socks_proxy=None, stream=None, timeout=600, url=False, version=False)
Traceback (most recent call last):
  File "/home/jiangyd/wine/opt/you-get/you-get", line 11, in <module>
    you_get.main(repo_path=_filepath)
  File "/mnt/dat/wine/opt/you-get/src/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/mnt/dat/wine/opt/you-get/src/you_get/common.py", line 1758, in main
    script_main(any_download, any_download_playlist, **kwargs)
  File "/mnt/dat/wine/opt/you-get/src/you_get/common.py", line 1646, in script_main
    **extra
  File "/mnt/dat/wine/opt/you-get/src/you_get/common.py", line 1302, in download_main
    download(url, **kwargs)
  File "/mnt/dat/wine/opt/you-get/src/you_get/common.py", line 1749, in any_download
    m.download(url, **kwargs)
  File "/mnt/dat/wine/opt/you-get/src/you_get/extractor.py", line 48, in download_by_url
    self.prepare(**kwargs)
  File "/mnt/dat/wine/opt/you-get/src/you_get/extractors/bilibili.py", line 169, in prepare
    initial_state = json.loads(initial_state_text)
  File "/usr/lib/python3.7/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType

白天是没问题的

**Comment by andysendo** [comment]
可能就是b占后端过滤算法给强制断了。我这里
上午：ykdl you-get偶尔403
下午：ykdl频繁  you-get偶尔
晚上：ykdl频繁  you-get不好说
如果真是 代码好像也没啥好改的

**Comment by mozbugbox** [comment]
好像 Python urllib 的 `urlopen()` 不能处理 bilibili 返回的 302 重定向结果，可以考虑使用 `requests` 库或者 override urllib 的 `HTTPRedirectHandler`:

```
$ wget --debug https://www.bilibili.com/video/av49673221
...
...
HTTP/1.1 302 Found
Date: Fri, 07 Feb 2020 14:00:33 GMT
Content-Type: text/html; charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
Set-Cookie: main_confirmation=7x2ewxjona4IgoWaprsRPXQBZTsde7dsGduh1Bhtags=; path=/; expires=Fri, 07 Feb 2020 14:01:03 GMT; httponly
Location: //www.bilibili.com/video/av49673221?rt=V%2FymTlOu4ow%2Fy4xxNWPUZ%2B2v5EAElHFKpKCAJQ%2BTelo%3D
Vary: Origin,Accept-Encoding
X-Cache-Webcdn: BYPASS from u-s-hk-webcdn-01
...
...
```

Location 给出的位置不是完整的 URL ，结果出错。

```python
>>> from urllib import request
>>> req = request.urlopen("https://www.bilibili.com/video/av49673221")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 563, in error
    result = self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 755, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

如果使用 `requests` library:
```python
>>> import requests
>>> req = requests.get("https://www.bilibili.com/video/av49673221")
>>> req.text
'<!DOCTYPE html><html><head itemprop="video" itemscope itemtype="http://schema.org/VideoObject"><title data-vue-meta="true">这么奶凶的国宝，谁还敢欺负！_哔哩哔哩 (゜-゜)つロ 干杯~-bilibili</title> <meta data-vue-meta="true" http-equiv="Content-Type" content="text/html" charset="utf-8"><meta data-vue-meta="true" name="renderer" content="webkit"> 
......
....
```

**Comment by mozbugbox** [comment]
实际上不是 Location 的问题，而是bilibili返回的 302 设定了 Cookie ，而 Python urllib 的 `redirect_request` 在处理 302 的时候没有保留相应的 cookie 信息，所以会收到 403 的结果。

**Comment by mozbugbox** [comment]
Opener 里增加一个 `HTTPCookieProcessor` 就可以解决问题。

```python
>>> from urllib import request
>>> url = "https://www.bilibili.com/video/av49673221"
>>> opener = request.build_opener(request.HTTPCookieProcessor())
>>> req = opener.open(url)
>>> content = req.read()
>>> print(content)
b'\x1f\x8b\x08\x00\x00..............................
...
```

**Comment by SeaHOH** [comment]
谢谢，已添加修改。
