### ISSUE TITLE
Python3.8无法安装

### ISSUE THREAD

**Issue by wind-cool** [zhangn1985/ykdl#463]
> windows10专业版上安装了python3.8，也把Python38的系统环境变量配置好了，执行命令  pip install --upgrade ykdl  就报错

错误日志:

```
C:\Users\admin>pip install --upgrade ykdl
Traceback (most recent call last):
  File "d:\admin\python38\lib\runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "d:\admin\python38\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\admin\Python38\Scripts\pip.exe\__main__.py", line 5, in <module>
  File "d:\admin\python38\lib\site-packages\pip\_internal\main.py", line 13, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "d:\admin\python38\lib\site-packages\pip\_internal\cli\autocompletion.py", line 11, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "d:\admin\python38\lib\site-packages\pip\_internal\cli\main_parser.py", line 7, in <module>
    from pip._internal.cli import cmdoptions
  File "d:\admin\python38\lib\site-packages\pip\_internal\cli\cmdoptions.py", line 25, in <module>
    from pip._internal.locations import USER_CACHE_DIR, get_src_prefix
  File "d:\admin\python38\lib\site-packages\pip\_internal\locations.py", line 28, in <module>
    USER_CACHE_DIR = appdirs.user_cache_dir("pip")
  File "d:\admin\python38\lib\site-packages\pip\_internal\utils\appdirs.py", line 47, in user_cache_dir
    path = os.path.normpath(_get_win_folder("CSIDL_LOCAL_APPDATA"))
  File "d:\admin\python38\lib\site-packages\pip\_internal\utils\appdirs.py", line 207, in _get_win_folder_from_registry
    import _winreg
ModuleNotFoundError: No module named '_winreg'
```

**Comment by SeaHOH** [comment]
你的配置可能有问题，请先验证是否能正常安装其它包。

**Comment by mengmo** [comment]
[35.3. _winreg — Windows registry access](https://docs.python.org/2/library/_winreg.html)
> **Note:** The `_winreg` module has been renamed to `winreg` in Python 3.

@wind-cool 看起来你 Python 3.8 的`pip`不像是全新安装的

**Comment by SeaHOH** [comment]
从源码来看他的 pip 版本是最新版，而不是 3.8 附带的 19.2.3。问题出在这个 ImportError：
https://github.com/pypa/pip/blob/c21fd4a70cde95ee32d4228bcf392438a7019a2b/src/pip/_internal/utils/appdirs.py#L253-L258
```py
if WINDOWS:
    try:
        import ctypes
        _get_win_folder = _get_win_folder_with_ctypes
    except ImportError:
        _get_win_folder = _get_win_folder_from_registry
```
不过，这 `import _winreg` 也算是个 bug。
