### ISSUE TITLE
B站部分视频下载报错403: Forbidden

### ISSUE THREAD

**Issue by karma-sun** [zhangn1985/ykdl#466]
ykdl https://www.bilibili.com/bangumi/play/ep284176

site:                哔哩哔哩 番剧 (Bilibili Bangumi)
title:               万国志：第1话 异邦人
artist:              哔哩哔哩国创
streams:
    - format:        BD
      container:     flv
      video-profile: 高清 1080P
      size:          345.4 MiB (362187214 bytes)
    # download-with: ykdl --format=BD [URL]
Download: 万国志：第1话 异邦人_BD
Traceback (most recent call last):
  File "C:\Python37\Scripts\ykdl-script.py", line 11, in <module>
    load_entry_point('ykdl==1.6.3', 'console_scripts', 'ykdl')()
  File "C:\Python37\lib\site-packages\ykdl-1.6.3-py3.7.egg\cykdl\__main__.py", line 212, in main
  File "C:\Python37\lib\site-packages\ykdl-1.6.3-py3.7.egg\cykdl\__main__.py", line 137, in handle_videoinfo
  File "C:\Python37\lib\site-packages\ykdl-1.6.3-py3.7.egg\cykdl\__main__.py", line 88, in download
  File "C:\Python37\lib\site-packages\ykdl-1.6.3-py3.7.egg\ykdl\util\download.py", line 91, in save_urls
  File "C:\Python37\lib\site-packages\ykdl-1.6.3-py3.7.egg\ykdl\util\download.py", line 50, in save_url
  File "C:\Python37\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Python37\lib\urllib\request.py", line 531, in open
    response = meth(req, response)
  File "C:\Python37\lib\urllib\request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Python37\lib\urllib\request.py", line 569, in error
    return self._call_chain(*args)
  File "C:\Python37\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "C:\Python37\lib\urllib\request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

**Comment by karma-sun** [comment]
前几天还是正常的，B站最近又改什么了？

**Comment by SeaHOH** [comment]
更新到 master

**Comment by mengmo** [comment]
```
ykdl -i https://www.bilibili.com/bangumi/play/ep284176
Traceback (most recent call last):
  File "d:\portableapps\python\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\portableapps\python\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\PortableApps\Python\Scripts\ykdl.exe\__main__.py", line 7, in <module>
  File "d:\portableapps\python\lib\site-packages\cykdl\__main__.py", line 194, in main
    info = parser(u)
  File "d:\portableapps\python\lib\site-packages\ykdl\extractor.py", line 23, in parser
    info = self.prepare()
  File "d:\portableapps\python\lib\site-packages\ykdl\extractors\bilibili\bilibase.py", line 48, in prepare
    self.vid, info.title, info.artist = self.get_page_info()
  File "d:\portableapps\python\lib\site-packages\ykdl\extractors\bilibili\bangumi.py", line 29, in get_page_info
    self.seasonType = mediaInfo['season_type']
KeyError: 'season_type'
```

**Comment by SeaHOH** [comment]
这抽风呢。。。

**Comment by airdge** [comment]
platform=pc经常限制refere和ua
不想麻烦就直接改platform
```
    def get_api_url(self, qn):
        # params_str = 'appkey={}&cid={}&module=bangumi&player=1&qn={}&season_type={}'.format(APPKEY, self.vid, qn, self.seasonType)
        params_str = 'appkey={}&cid={}&module=bangumi&platform=html5&player=1&qn={}&season_type={}'.format(APPKEY, self.vid, qn, self.seasonType)
        return sign_api_url(api_url, params_str, SECRETKEY)
```
![图片](https://user-images.githubusercontent.com/7813960/69700027-65a49080-1124-11ea-92f4-3a9f6ddafb9f.png)
