### ISSUE TITLE
斗鱼直播

### ISSUE THREAD

**Issue by wordlesswind** [zhangn1985/ykdl#477]
在提交前，请确保您已经检查了以下内容!

- [x] 你确实可以在浏览器或移动端中观看视频，但不能使用`ykdl`下载。
- [x] 您的`ykdl`为最新版。
- [x] 您已经阅读并按 <https://github.com/zhangn1985/ykdl/wiki> 中的指引进行了操作。
- [x] 您的问题没有在 <https://github.com/zhangn1985/ykdl/issues> 报告，否则请在原有 issue 下报告。
- [x] 本问题确实关于`ykdl`，而不是其他项目。

请将错误输出粘贴在下面:

```
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\Scripts\ykdl-script.py", line 11, in <module>
    load_entry_point('ykdl==1.6.2', 'console_scripts', 'ykdl')()
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\cykdl\__main__.py", line 173, in main
    info = parser(u)
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\ykdl\extractor.py", line 24, in parser
    info = self.prepare()
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\ykdl\extractors\douyu\live.py", line 39, in prepare
    html_content = get_content(api_url)
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\ykdl\util\html.py", line 67, in get_content
    response = urlopen(req)
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\urllib\request.py", line 531, in open
    response = meth(req, response)
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\urllib\request.py", line 640, in http_response
    response = self.parent.error(
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\urllib\request.py", line 569, in error
    return self._call_chain(*args)
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\urllib\request.py", line 502, in _call_chain
    result = func(*args)
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\urllib\request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加:

> Pyrhon
>> Python 3.8.1

> ffmpeg
>> ffmpeg version 4.2.1 Copyright (c) 2000-2019 the FFmpeg developers
built with gcc 9.1.1 (GCC) 20190807
configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt
libavutil      56. 31.100 / 56. 31.100
libavcodec     58. 54.100 / 58. 54.100
libavformat    58. 29.100 / 58. 29.100
libavdevice    58.  8.100 / 58.  8.100
libavfilter     7. 57.100 /  7. 57.100
libswscale      5.  5.100 /  5.  5.100
libswresample   3.  5.100 /  3.  5.100
libpostproc    55.  5.100 / 55.  5.100

> mpv
>> mpv 0.31.0 Copyright © 2000-2019 mpv/MPlayer/mplayer2 projects
 built on Sun Dec 29 09:37:25 +08 2019
ffmpeg library versions:
   libavutil       56.38.100
   libavcodec      58.65.100
   libavformat     58.35.101
   libswscale      5.6.100
   libavfilter     7.69.101
   libswresample   3.6.100
ffmpeg version: git-2019-12-28-6399eed4

> 均为 x86_64 ，另外 mpv 新的 Windows builds : https://sourceforge.net/projects/mpv-player-windows/files

> ykdl
>> Looking in indexes: https://pypi.python.org/pypi
Requirement already up-to-date: ykdl in c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages (1.6.2)
Requirement already satisfied, skipping upgrade: m3u8 in c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages (from ykdl) (0.5.3)
Requirement already satisfied, skipping upgrade: pycryptodome in c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages (from ykdl) (3.9.4)
Requirement already satisfied, skipping upgrade: urllib3 in c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages (from ykdl) (1.25.7)
Requirement already satisfied, skipping upgrade: iso8601 in c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages (from m3u8->ykdl) (0.1.12)

> Update#2020-01-06 14:40 GMT+8
>> 看起来似乎是我本地的问题？测试了 AcFun 也是上述错误，而 Bilibili 则是 CRITICAL:YKDL:can't play this video!! ， 虎牙直播正常录制。

**Comment by mengmo** [comment]
`pip install https://github.com/zhangn1985/ykdl/archive/master.zip`

**Comment by wordlesswind** [comment]
> `pip install --upgrade https://github.com/zhangn1985/ykdl/archive/master.zip`

喔好的谢谢，用惯了 you-get 以为会同步更新至 Pypl 。
