### ISSUE TITLE
央视网4K专区视频无法下载

### ISSUE THREAD

**Issue by toorich** [zhangn1985/ykdl#483]
在提交前，请确保您已经检查了以下内容!

- [x] 你确实可以在浏览器或移动端中观看视频，但不能使用`ykdl`下载。
- [x] 您的`ykdl`为最新版。
- [x] 您已经阅读并按 <https://github.com/zhangn1985/ykdl/wiki> 中的指引进行了操作。
- [x] 您的问题没有在 <https://github.com/zhangn1985/ykdl/issues> 报告，否则请在原有 issue 下报告。
- [x] 本问题确实关于`ykdl`，而不是其他项目。

请将错误输出粘贴在下面:

```
ykdl -i http://tv.cctv.com/2019/07/02/VIDEl9MVMY8OnJdHIS1YQtU1190702.shtml --debug
DEBUG:common:video_host> tv.cctv.com
DEBUG:common:short_name> cctv
DEBUG:html:get_content> URL: http://tv.cctv.com/2019/07/02/VIDEl9MVMY8OnJdHIS1YQtU1190702.shtml
DEBUG:html:get_content> Charset: UTF-8
DEBUG:html:get_content> URL: http://vdn.apps.cntv.cn/api/getHttpVideoInfo.do?pid=594babe9d2654fc1a6d49dbf44b154ef
DEBUG:html:get_content> Charset: UTF-8
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/ykdl", line 11, in <module>
    load_entry_point('ykdl==1.6.2', 'console_scripts', 'ykdl')()
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/cykdl/__main__.py", line 183, in main
    handle_videoinfo(info)
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/cykdl/__main__.py", line 92, in handle_videoinfo
    stream_id = info.stream_types[i]
IndexError: list index out of range
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加:

> 看了一下，能解析出内容，但是ykdl不认，已提交PR（#484）

**Comment by toorich** [comment]
@SeaHOH 感谢！
