### ISSUE TITLE
爱奇艺 'utf-8' codec can't decode byte 0x8b in position

### ISSUE THREAD

**Issue by ssswang** [zhangn1985/ykdl#508]
```
ykdl https://www.iqiyi.com/v_19ryhzbaqs.html
site:                爱奇艺 (Iqiyi)
title:               《青春有你2》练习室版直拍
artist:              None
streams:
    - format:        BD
      container:     m3u8
      video-profile: 1080p
    # download-with: ykdl --format=BD [URL]
Traceback (most recent call last):
  File "C:\software\Python\Python38\Scripts\ykdl-script.py", line 11, in <module>
    load_entry_point('ykdl==1.6.3', 'console_scripts', 'ykdl')()
  File "C:\Users\yes\AppData\Roaming\Python\Python38\site-packages\cykdl\__main__.py", line 203, in main
    handle_videoinfo(info)
  File "C:\Users\yes\AppData\Roaming\Python\Python38\site-packages\cykdl\__main__.py", line 131, in handle_videoinfo
    download(urls, name, ext, live)
  File "C:\Users\yes\AppData\Roaming\Python\Python38\site-packages\cykdl\__main__.py", line 72, in download
    urls = load_m3u8(urls[0])
  File "C:\Users\yes\AppData\Roaming\Python\Python38\site-packages\ykdl\util\m3u8_wrap.py", line 36, in load_m3u8
    m =  m3u8.load(url, headers=fake_headers)
  File "c:\software\python\python38\lib\site-packages\m3u8\__init__.py", line 56, in load
    return _load_from_uri(uri, timeout, headers, custom_tags_parser, verify_ssl)
  File "c:\software\python\python38\lib\site-packages\m3u8\__init__.py", line 73, in _load_from_uri
    content = _read_python3x(resource)
  File "c:\software\python\python38\lib\site-packages\m3u8\__init__.py", line 89, in _read_python3x
    return resource.read().decode(
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
```

**Comment by SeaHOH** [comment]
未能复现，偶发的网络错误？
