### ISSUE TITLE
下载优酷视频，无法合并，提示FileNotFoundError: [WinError 2] 系统找不到指定的文件。

### ISSUE THREAD

**Issue by axushilong** [zhangn1985/ykdl#526]
在提交前，请确保您已经检查了以下内容!

- [ ] 你确实可以在浏览器或移动端中观看视频，但不能使用`ykdl`下载。
- [ ] 您的`ykdl`为最新版。
- [ ] 您已经阅读并按 <https://github.com/zhangn1985/ykdl/wiki> 中的指引进行了操作。
- [ ] 您的问题没有在 <https://github.com/zhangn1985/ykdl/issues> 报告，否则请在原有 issue 下报告。
- [x] 本问题确实关于`ykdl`，而不是其他项目。

请将错误输出粘贴在下面:

下载了一个视频，但是无法合并，都是很多*.flv格式。
[在这里粘贴完整日志]
C:\Users\Administrator>ykdl -o L:\Download https://v.youku.com/v_show/id_XODQxMDI3MzUy.html?spm=a2hzp.8253869.0.0
site:                优酷 (Youku)
title:               [UHD·技术培训]Cortex-M内核系列和STM32-讲座3
artist:              None
streams:
    - format:        TD
      container:     flv
      video-profile: 超清
      size:          238.8 MiB (250394429 bytes)
    # download-with: ykdl --format=TD [URL]

Download: [UHD·技术培训]Cortex-M内核系列和STM32-讲座3_TD part 0

Download: [UHD·技术培训]Cortex-M内核系列和STM32-讲座3_TD part 1

Download: [UHD·技术培训]Cortex-M内核系列和STM32-讲座3_TD part 2

Download: [UHD·技术培训]Cortex-M内核系列和STM32-讲座3_TD part 3

Download: [UHD·技术培训]Cortex-M内核系列和STM32-讲座3_TD part 6

Download: [UHD·技术培训]Cortex-M内核系列和STM32-讲座3_TD part 7

Download: [UHD·技术培训]Cortex-M内核系列和STM32-讲座3_TD part 5

Download: [UHD·技术培训]Cortex-M内核系列和STM32-讲座3_TD part 4
  73%
Download: [UHD·技术培训]Cortex-M内核系列和STM32-讲座3_TD part 8
 100%Merging video [UHD·技术培训]Cortex-M内核系列和STM32-讲座3_TD using FFmpeg:
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\Scripts\ykdl-script.py", line 11, in <module>
    load_entry_point('ykdl==1.6.3', 'console_scripts', 'ykdl')()
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\cykdl\__main__.py", line 203, in
 main
    handle_videoinfo(info)
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\cykdl\__main__.py", line 131, in
 handle_videoinfo
    download(urls, name, ext, live)
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\cykdl\__main__.py", line 86, in
download
    launch_ffmpeg(name, ext,lenth)
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\ykdl\util\wrap.py", line 164, in
 launch_ffmpeg
    subprocess.call(cmd)
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\subprocess.py", line 340, in call
    with Popen(*popenargs, **kwargs) as p:
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加:

> [您的内容]

**Comment by SeaHOH** [comment]
安装 FFmpeg

**Comment by axushilong** [comment]
非常感谢，我是安装FFmpeg的方法不对，没安装成功，同时将FFmpeg的路径加到了用户环境变量，和系统环境变量了，只要加入系统环境变量就可以。



在 2020-08-28 21:51:48，"SeaHOH" <notifications@github.com> 写道：

安装 FFmpeg
