### ISSUE TITLE
panda tv，解析有问题

### ISSUE THREAD

**Issue by mengmo** [zhangn1985/ykdl#53]
我就随手试了下，发现就这个有问题
```
ykdl -i http://www.panda.tv/13653
site:                熊猫TV (Panda)
Traceback (most recent call last):
  File "D:\PortableApps\Python\lib\runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\PortableApps\Python\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\PortableApps\Python\lib\site-packages\ykdl\__main__.py", line 148, in <module>
    main()
  File "D:\PortableApps\Python\lib\site-packages\ykdl\__main__.py", line 136, in main
    handle_videoinfo(info)
  File "D:\PortableApps\Python\lib\site-packages\ykdl\__main__.py", line 77, in handle_videoinfo
    info.print_info(args.format, args.info)
  File "D:\PortableApps\Python\lib\site-packages\ykdl\videoinfo.py", line 47, in print_info
    print("title:               %s" % self.title)
UnicodeEncodeError: 'gbk' codec can't encode character '\u265b' in position 22: illegal multibyte sequence
```

**Comment by mengmo** [comment]
chcp 65001 可解，关了
