### ISSUE TITLE
部分爱奇艺直播不能解析

### ISSUE THREAD

**Issue by TaoziDB** [zhangn1985/ykdl#550]
在提交前，请确保您已经检查了以下内容!

- [x] 你确实可以在浏览器或移动端中观看视频，但不能使用`ykdl`下载。
- [x] 您的`ykdl`为最新版。
- [x] 您已经阅读并按 <https://github.com/zhangn1985/ykdl/wiki> 中的指引进行了操作。
- [x] 您的问题没有在 <https://github.com/zhangn1985/ykdl/issues> 报告，否则请在原有 issue 下报告。
- [x] 本问题确实关于`ykdl`，而不是其他项目。

请将错误输出粘贴在下面:

```
real-url>ykdl -i https://gamelive.iqiyi.com/w/67658
Traceback (most recent call last):
  File "c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\Scripts\ykdl.exe\__main__.py", line 7, in <module>
  File "c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\site-packages\cykdl\__main__.py", line 197, in main
    info = parser(u)
  File "c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\site-packages\ykdl\extractor.py", line 23, in parser
    info = self.prepare()
  File "c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\site-packages\ykdl\extractors\iqiyi\live.py", line 65, in prepare
    data = getlive(self.vid)
  File "c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\site-packages\ykdl\extractors\iqiyi\live.py", line 41, in getlive
    return json.loads(html)
  File "c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 1)
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加:

> 在直播的html中，如果"playStatus":2，解析没问题，如果"playStatus":1，解析就出问题

**Comment by wordlesswind** [comment]
访问你提供的链接会跳转至 https://x.pps.tv/room/261686
```
PS C:\Users\i> curl -I https://gamelive.iqiyi.com/w/67658
HTTP/1.1 200 Connection established

HTTP/2 302
server: nginx
date: Wed, 03 Feb 2021 08:03:16 GMT
content-type: text/html; charset=utf-8
content-length: 80399
location: https://x.pps.tv/room/261686
cache-control: no-cache
set-cookie: QC005=b467b6f6bd504a74b443af6108716cfd; path=/; expires=Sat, 29 Jan 2022 08:03:16 GMT; domain=iqiyi.com
strict-transport-security: max-age=2592000; includeSubdomains; preload
x-cache: from 116.211.201.223
x-cache:  from 59.36.206.1
alt-svc: quic=":443"; ma=2592000; v="46,43",h3-Q048=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000
```

找了一个同样会跳转的直播间：https://gamelive.iqiyi.com/w/34603

```
PS C:\Users\i> ykdl -i --debug https://gamelive.iqiyi.com/w/34603
DEBUG:html:Add <urllib.request.ProxyHandler object at 0x000001547F882A30> to default handlers
DEBUG:common:video_host> gamelive.iqiyi.com
DEBUG:common:short_name> iqiyi
DEBUG:html:get_content> URL: https://gamelive.iqiyi.com/w/34603
DEBUG:html:get_content> Charset: utf-8
DEBUG:html:get_content> URL: https://live.video.iqiyi.com/live?lp=None&src=01010031010000000000&uid=&rateVers=PC_QIYI_3&k_uid=edwovt9vhgmvqnz1v7lcfy92&qdx=n&qdv=3&qd_v=1&dfp=xfozqg9hwhon86xuhujcb6hp76fh3dgw0nyw6ickknuwekbzfsgiuxgrytppt0gjle&v=1&k_err_retries=0&tm=1612339466&vf=f24948111639c875919b2cf6af7d02fa
DEBUG:html:get_content> Charset: utf-8
DEBUG:爱奇艺直播 (IqiyiLive):data:
{'ctl': {'msg': 'server return err-data.'}, 'code': 'A00001'}
CRITICAL:YKDL:can't play this live video!!

PS C:\Users\i> curl -I https://gamelive.iqiyi.com/w/34603
HTTP/1.1 200 Connection established

HTTP/2 302
server: nginx
date: Wed, 03 Feb 2021 08:07:46 GMT
content-type: text/html; charset=utf-8
content-length: 79821
location: https://x.pps.tv/room/255765
cache-control: no-cache
set-cookie: QC005=eb4365bebe353342f5d8fbfb7f631af5; path=/; expires=Sat, 29 Jan 2022 08:07:46 GMT; domain=iqiyi.com
strict-transport-security: max-age=2592000; includeSubdomains; preload
x-cache: from 116.211.201.224
x-cache:  from 59.36.206.2
alt-svc: quic=":443"; ma=2592000; v="46,43",h3-Q048=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000

PS C:\Users\i> ykdl -i --debug https://x.pps.tv/room/255765
DEBUG:html:Add <urllib.request.ProxyHandler object at 0x00000261DBC62A30> to default handlers
DEBUG:common:video_host> x.pps.tv
DEBUG:common:short_name> pps
DEBUG:html:get_content> URL: https://x.pps.tv/room/255765
DEBUG:html:get_content> Charset: utf-8
DEBUG:html:get_content> URL: https://m-glider-xiu.pps.tv/v2/stream/get.json
DEBUG:html:get_content> Charset: utf-8
DEBUG:奇秀（Qixiu):data:
{'code': 'A00000', 'msg': '正常', 'data': {'rtmp': 'rtmp://175.6.224.77:1935/liveshow/rqq_0seifzhy?play_track_id=26498339', 'version': '1.0.0', 'platform': 1, 'channel': '25', 'https_flv': 'https://v-3b24ce25.71edge.com:444/liveshow/rqq_0seifzhy.flv?ssl=1&ip=113.64.93.169&play_track_id=26498339', 'stream_mode': 'RTMP', 'aspect_ratio': '16:9', 'rate_list': ['source', 'high', 'smooth'], 'live_mode': 1, 'is_fullscreen': '0'}, 'trace_id': '31568c4bd7704201932684f66a968c5b'}
DEBUG:html:get_content> URL: https://m-glider-xiu.pps.tv/v2/stream/get.json
DEBUG:html:get_content> Charset: utf-8
DEBUG:奇秀（Qixiu):data:
{'code': 'A00000', 'msg': '正常', 'data': {'rtmp': 'rtmp://59.36.206.38:1935/liveshow/rqq_0seifzhy_500?play_track_id=26498339', 'version': '1.0.0', 'platform': 1, 'channel': '25', 'https_flv': 'https://flv-bdplay.inter.71edge.com/liveshow/rqq_0seifzhy_500.flv?ssl=1&ip=113.64.93.169&play_track_id=26498339', 'stream_mode': 'RTMP', 'aspect_ratio': '16:9', 'rate_list': ['source', 'high', 'smooth'], 'live_mode': 1, 'is_fullscreen': '0'}, 'trace_id': 'e8f53e3160c92bbcb56db129b847c1cb'}
DEBUG:html:get_content> URL: https://m-glider-xiu.pps.tv/v2/stream/get.json
DEBUG:html:get_content> Charset: utf-8
DEBUG:奇秀（Qixiu):data:
{'code': 'A00000', 'msg': '正常', 'data': {'rtmp': 'rtmp://59.36.206.36:1935/liveshow/rqq_0seifzhy_300?play_track_id=26498339', 'version': '1.0.0', 'platform': 1, 'channel': '25', 'https_flv': 'https://flv-bdplay.inter.71edge.com/liveshow/rqq_0seifzhy_300.flv?ssl=1&ip=113.64.93.169&play_track_id=26498339', 'stream_mode': 'RTMP', 'aspect_ratio': '16:9', 'rate_list': ['source', 'high', 'smooth'], 'live_mode': 1, 'is_fullscreen': '0'}, 'trace_id': 'c915204e9bff6de6be80eb5f872df55e'}
site:                奇秀（Qixiu)
title:               狗子：本来可以靠颜值吃饭，可我非要靠技术 - GZ_GOD
artist:              GZ_GOD
streams:
    - format:        TD
      container:     flv
      video-profile: 超清
    # download-with: ykdl --format=TD [URL]
Real urls:
https://v-3b24ce25.71edge.com:444/liveshow/rqq_0seifzhy.flv?ssl=1&ip=113.64.93.169&play_track_id=26498339&ran=1116
    - format:        HD
      container:     flv
      video-profile: 高清
    # download-with: ykdl --format=HD [URL]
Real urls:
https://flv-bdplay.inter.71edge.com/liveshow/rqq_0seifzhy_500.flv?ssl=1&ip=113.64.93.169&play_track_id=26498339&ran=7920
    - format:        SD
      container:     flv
      video-profile: 标清
    # download-with: ykdl --format=SD [URL]
Real urls:
https://flv-bdplay.inter.71edge.com/liveshow/rqq_0seifzhy_300.flv?ssl=1&ip=113.64.93.169&play_track_id=26498339&ran=4024
```
你之后试试直接抓取 https://x.pps.tv 的直播流？
