### ISSUE TITLE
QQLive empty info.stream_types

### ISSUE THREAD

**Issue by pa-panda** [zhangn1985/ykdl#556]
在提交前，请确保您已经检查了以下内容!

- [x] 你确实可以在浏览器或移动端中观看视频，但不能使用`ykdl`下载。
- [x] 您的`ykdl`为最新版。
- [x] 您已经阅读并按 <https://github.com/zhangn1985/ykdl/wiki> 中的指引进行了操作。
- [x] 您的问题没有在 <https://github.com/zhangn1985/ykdl/issues> 报告，否则请在原有 issue 下报告。
- [x] 本问题确实关于`ykdl`，而不是其他项目。

请将错误输出粘贴在下面:

```
$ ykdl https://live.qq.com/10098570 -i --debug
DEBUG:common:video_host> live.qq.com
DEBUG:common:short_name> qq
DEBUG:html:get_content> URL: http://www.qie.tv/api/v1/room/10098570
DEBUG:html:get_content> Charset: utf-8
Traceback (most recent call last):
  File "/home/pa/.local/bin/ykdl", line 8, in <module>
    sys.exit(main())
  File "/home/pa/.local/lib/python3.8/site-packages/cykdl/__main__.py", line 183, in main
    handle_videoinfo(info)
  File "/home/pa/.local/lib/python3.8/site-packages/cykdl/__main__.py", line 92, in handle_videoinfo
    stream_id = info.stream_types[i]
IndexError: list index out of range
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加:

> Looks like same error output as #483 but with different plugin.

**Comment by SeaHOH** [comment]
估计近期还会有变化。
