### ISSUE TITLE
从python代码里无法引入ykdl     No module named 'ykdl.common'; 

### ISSUE THREAD

**Issue by redstoneleo** [zhangn1985/ykdl#60]
```
>>> from ykdl.commom import url_to_module
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\i\Downloads\ykdl-master\bin\ykdl.py", line 17, in <module>
    from ykdl.common import url_to_module
ImportError: No module named 'ykdl.common'; 'ykdl' is not a package
>>>
```
只能通过命令行调用吗？

**Comment by zhangn1985** [comment]
这里有点古怪。
如果你在ykdl-master\bin\ 目录下执行python。那么python会把ykdl.py当作ykdl模块的源码。
所以就会出现你这个问题。

如果你仔细看我发布的windows prebuild版本。ykdl.py都被我重命名了。


如果你需要这么做的话，你应该在ykdl-master\这个目录下运行python。

**Comment by redstoneleo** [comment]
我是pip3 install ykdl后进行上面的引入出问题的
哪里可以看到 windows prebuild版本？

**Comment by zhangn1985** [comment]
https://github.com/zhangn1985/ykdl/releases

**Comment by zhangn1985** [comment]
我自己在windows机器上也通过pip安装了ykdl，但并没有直接在github下载源代码。
没有出现你的问题。

从你给的log来看，的确是python 把 C:\Users\i\Downloads\ykdl-master\bin\ykdl.py 当成了ykdl module了。

还有可能是你的PYTHONPATH环境变量包含了C:\Users\i\Downloads\ykdl-master\bin\ 这个目录，而且靠前。

**Comment by zhangn1985** [comment]
另外你可以在Python环境下
import ykdl
ykdl
看看是ykdl指的是哪个位置。

或者：
import sys
print(sys.path) 

这个可以帮助你查看PYTHONPATH

**Comment by redstoneleo** [comment]
谢谢大哥！之前可能是在ykdl-master\bin\ 目录下执行python了，现在我运行就没问题

```
D:\BaiduYunDownload\>python
Python 3.5.2 (v3.5.2:4def2a2901a5, Jun 25 2016, 22:01:18) [MSC v.1900 32 bit (In
tel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import ykdl
>>> help(ykdl)
Help on package ykdl:

NAME
    ykdl - # -*- coding: utf-8 -*

PACKAGE CONTENTS
    common
    compact
    embedextractor
    extractor
    extractors (package)
    simpleextractor
    util (package)
    version
    videoinfo

FILE
    c:\users\i\appdata\local\programs\python\python35-32\lib\site-packages\ykdl\
__init__.py


>>>

```
但是当
```
>>> from ykdl.commom import url_to_module
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'ykdl.commom'
>>>
>>> import ykdl.commom
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'ykdl.commom'
>>>
>>> from ykdl import commom
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'commom'
>>>

```
其实我就想问问能否从python代码里以module的形式使用ykdl

**Comment by zhangn1985** [comment]
这个原因是你直接使用
from ykdl.commom import url_to_module
会导致ykdl没法解析。

你需要先
import ykdl
具体请参考bin/ykdl.py

**Comment by zhangn1985** [comment]
```
import sys
import os
try:
    import ykdl
except(ImportError):
    _base_len = len('bin/ykdl.py')
    _filepath = os.path.abspath(sys.argv[0])[:-_base_len]
    sys.path[0] = _filepath
    import ykdl

from argparse import ArgumentParser
import socket
import json

from ykdl.common import url_to_module
from ykdl.compact import ProxyHandler, build_opener, install_opener, compact_str
from ykdl.util import log
from ykdl.util.wrap import launch_player, launch_ffmpeg, launch_ffmpeg_download
from ykdl.util.m3u8_wrap import load_m3u8
from ykdl.util.download import save_urls
from ykdl.version import __version__
```

**Comment by zhangn1985** [comment]
上面两个说的是错的，其实仔细一看是你写错了，

ImportError: No module named 'ykdl.commom'
ykdl.common 这个才是正确的。

的确是可以直接
from ykdl.common import url_to_module
不需要预先import ykdl的

**Comment by redstoneleo** [comment]
哎呀，犯了个低级错误，浪费老大时间了，罪过~
