### ISSUE TITLE
乐视的解析有点儿问题

### ISSUE THREAD

**Issue by mengmo** [zhangn1985/ykdl#63]
```
ykdl -i http://www.le.com/ptv/vplay/1224362.html
site:                乐视 (Letv)
title:               日式面包王27
artist:              None
streams:
    - format:        TD
      container:     m3u8
      video-profile: 超清
    # download-with: ykdl --format=TD [URL]
Real urls:
C:\Users\user\AppData\Local\Temp\tmpxvf01x59.m3u8
    - format:        HD
      container:     m3u8
      video-profile: 高清
    # download-with: ykdl --format=HD [URL]
Real urls:
C:\Users\user\AppData\Local\Temp\tmptfu6c_0h.m3u8
    - format:        LD
      container:     m3u8
      video-profile: 流畅
    # download-with: ykdl --format=LD [URL]
Real urls:
C:\Users\user\AppData\Local\Temp\tmpa9spe6ux.m3u8
```
Real urls 居然是本机上的路径，请问这是 feature 吗？
另外
```
ykdl -i http://www.letv.com/ptv/vplay/1224362.html
Traceback (most recent call last):
  File "D:\PortableApps\Python\lib\runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\PortableApps\Python\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\PortableApps\Python\lib\site-packages\ykdl\__main__.py", line 148, in
 <module>
    main()
  File "D:\PortableApps\Python\lib\site-packages\ykdl\__main__.py", line 127, in
 main
    info = parser(u)
  File "D:\PortableApps\Python\lib\site-packages\ykdl\extractor.py", line 19, in
 parser
    info = self.prepare()
  File "D:\PortableApps\Python\lib\site-packages\ykdl\extractors\le\le.py", line
 67, in prepare
    info.title = data['playurl']['title']
KeyError: 'playurl'
```

**Comment by zhangn1985** [comment]
这不是feature, 这是一个Workaround。
因为乐视的视频解析下来是4秒一个片段
如果直接播放很影响体验，所以就fake了一个m3u8。
另一个我回去看一下。

**Comment by zhangn1985** [comment]
要获得乐视不分片的视频地址，比较困难。那段JS我看不懂。

**Comment by zhangn1985** [comment]
不过这个WR还取决于FFMPEG如何编译的，是不是支持这种本地m3u8，所以既然你提出我就把这个WR去掉好了。

**Comment by mengmo** [comment]
我这里测试的情况是除了 mplayer 能流畅播放外，其他播放器都是在播放时会出现卡一下的情况，至于卡多长时间，那得看网络情况。貌似大部分播放器处理这种保存在本地的视频列表文件时默认都不会自动缓存下一段。至于自己编译 ffmpeg ，以前试过一次，反正很长时间段内我是不想再试第二次了。

**Comment by mengmo** [comment]
不过，直接把几十多行的 url 打印出来也不是太好。因为就碰到过好几次，直接打印出 url ，结果一屏显示不全，只能看到后边的一部分，又不能向前翻页，也就不知道具体解析出来了多少种清晰度格式。能不能也像现在 you-get 一样，在用参数 -u 的时候才打印出 url 呢？

**Comment by zhangn1985** [comment]
那就不改了。

**Comment by zhangn1985** [comment]
https://github.com/zhangn1985/ykdl/commit/1eee551aca86ea7b3bd65326ca4680e24eb4487a

你反应的另一个问题已经修复了。

**Comment by redstoneleo** [comment]
乐视不分片的视频地址youtube-dl可以搞定，亲测可行！
https://github.com/yan12125/iqiyi-hack/issues/5#issuecomment-236437564

**Comment by mengmo** [comment]
刚看了一下，这儿 https://github.com/yan12125/iqiyi-hack/issues/5 提供的 URL 最高清晰度有不分片的
```
ytdl -F http://www.le.com/ptv/vplay/1847799.html
[Le] 1847799: Downloading webpage
[Le] 1847799: Downloading html5 playJson data
[Le] 1847799: Downloading flash playJson data
[Le] 1847799: Download JSON metadata for format 1000
[Le] 1847799: Download JSON metadata for format 720p
[Le] 1847799: Download JSON metadata for format 350
[Le] 1847799: Download JSON metadata for format mp4
[Le] 1847799: Download JSON metadata for format 1300
[Le] 1847799: Download JSON metadata for format 1080p
[Le] 1847799: Downloading m3u8 information for format 1080p
[info] Available formats for 1847799:
format code  extension  resolution note
hls-mp4      mp4        unknown
http-mp4     mp4        unknown
hls-350      mp4        unknown
http-350     mp4        unknown
hls-1000     mp4        unknown
http-1000    mp4        unknown
hls-1300     mp4        unknown
http-1300    mp4        unknown
hls-720p     mp4        720p
http-720p    mp4        720p
hls-1080p    mp4        1080p      (best)
```
但是 youtube-dl 最高清晰度只解析出来了 HLS的，其他都没问题

**Comment by zhangn1985** [comment]
很抱歉，我看不懂youtube-dl的代码逻辑。

**Comment by redstoneleo** [comment]
就不能保持m3u8 url 吗？
https://github.com/zhangn1985/ykdl/issues/84#event-996862252

**Comment by zhangn1985** [comment]
加密的m3u8 url没有任何意义，没有软件能读取。
解密后才保存到本地的。
