### ISSUE TITLE
acfun和youku合作的视频解析方法失效

### ISSUE THREAD

**Issue by DayNYQ** [zhangn1985/ykdl#66]
对加密后的地址进行解密的为乱码

**Comment by jindaxia** [comment]
详细一点，举个例子呢

**Comment by mengmo** [comment]
```
ykdl -i http://www.acfun.cn/v/ac3410471
Traceback (most recent call last):
  File "D:\PortableApps\Python\lib\runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\PortableApps\Python\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\PortableApps\Python\lib\site-packages\ykdl\__main__.py", line 148, in <module>
    main()
  File "D:\PortableApps\Python\lib\site-packages\ykdl\__main__.py", line 127, in main
    info = parser(u)
  File "D:\PortableApps\Python\lib\site-packages\ykdl\embedextractor.py", line 50, in parser
    return s.parser(vid)
  File "D:\PortableApps\Python\lib\site-packages\ykdl\extractor.py", line 19, in parser
    info = self.prepare()
  File "D:\PortableApps\Python\lib\site-packages\ykdl\extractors\acorig.py", line 26, in prepare
    stream_data = json.loads(data)
  File "D:\PortableApps\Python\lib\json\__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "D:\PortableApps\Python\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\PortableApps\Python\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by zhangn1985** [comment]
干，acfun 解密数据的key又变了。

**Comment by zhangn1985** [comment]
https://github.com/zhangn1985/ykdl/issues/61#issuecomment-281338847
这个是key的来源，但是我找不到这个人所说的地方。

**Comment by jindaxia** [comment]
应该说的是swf里面 反编译出来的方法

**Comment by freeleefly** [comment]
pip 更新到 1.4.3，还是上述问题。所以是现在还不能解决，对吧？

**Comment by zhangn1985** [comment]
1这个是新问题。
