### ISSUE TITLE
斗鱼的地址还是解析不了

### ISSUE THREAD

**Issue by kouzhao48** [zhangn1985/ykdl#67]
YKDL和YOU-GET都升级到了最新。斗鱼和ACFUN都解析不了...
Traceback (most recent call last):
  File "yk_dl.py", line 148, in <module>
  File "yk_dl.py", line 127, in main
  File "site-packages\ykdl\extractor.py", line 19, in parser
  File "site-packages\ykdl\extractors\douyu\live.py", line 46, in prepare
  File "site-packages\ykdl\util\html.py", line 62, in get_content
  File "urllib\request.py", line 161, in urlopen
  File "urllib\request.py", line 470, in open
  File "urllib\request.py", line 580, in http_response
  File "urllib\request.py", line 508, in error
  File "urllib\request.py", line 442, in _call_chain
  File "urllib\request.py", line 588, in http_error_default
urllib.error.HTTPError: HTTP Error 403: Forbidden
Failed to execute script yk_dl

**Comment by mengmo** [comment]
斗鱼的问题可以参考这儿 https://github.com/soimort/you-get/issues/1720
