### ISSUE TITLE
finish multi-thread download

### ISSUE THREAD

**Issue by zhangn1985** [zhangn1985/ykdl#69]
current multi-thread download has some issues
1, thread number is len(real urls), it's to big most of times, need to get number of thread from command line, and default to NR_CPUS.
2, bug in download process shown

so need to refine multi-thread download.

**Comment by zhangn1985** [comment]
```
Traceback (most recent call last):
  File "bin/ykdl.py", line 150, in <module>
    
  File "bin/ykdl.py", line 138, in main
    except AssertionError as e:
  File "bin/ykdl.py", line 92, in handle_videoinfo
    
  File "bin/ykdl.py", line 71, in download
    lenth = len(urls)
  File "/home/zhangn1985/source/ykdl/ykdl/util/download.py", line 77, in save_urls
    t = downloadThread(u, n)
  File "/home/zhangn1985/source/ykdl/ykdl/util/download.py", line 16, in __init__
    self.name = file_name
  File "/usr/lib/python2.7/threading.py", line 972, in name
    self.__name = str(name)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-12: ordinal not in range(128)
```
error when use python2

**Comment by zhangn1985** [comment]
https://github.com/soimort/you-get/pull/1682

**Comment by mengmo** [comment]
遇到了一个问题：
下载一个将近800MiB的视频，这个视频分了20多段，其中有一段出错没下载完，但是就直接合并了，没下完的那一段导致 ffmpeg 合并时只合并了前边的几段后出错退出，然后就把所有分段删除了。
目前没有应对下载出错的措施么？总是重下可不太好啊
另有疑问：目前不论视频有多少个分段都是同时下载么？

**Comment by zhangn1985** [comment]
1, 下载多个分段有错误，没加以判断就进行合并，似乎目前是这样的。
2, 现在的确是按照分段数开启多线程。
都会在这个issue中解决。

**Comment by zhangn1985** [comment]
部分的解决了第一个问题，只在合并成功后删除分片。
