### ISSUE TITLE
ValueError: No JSON object could be decoded 

### ISSUE THREAD

**Issue by fogmoon** [zhangn1985/ykdl#73]
> python: 2.7.12_2
> os: Mac OS

> python: 2.7.12_2
> os: Linux

when I run command after I installed ykdl use your wiki instruction, always `ValueError: No JSON object could be decoded` exception throws. 

So, may I missed something?

`ykdl.py -i http://www.acfun.tv/v/ac3101039`

Traceback (most recent call last):
  File "/usr/local/bin/ykdl.py", line 158, in <module>
    main()
  File "/usr/local/bin/ykdl.py", line 136, in main
    info = parser(u)
  File "/usr/local/lib/python2.7/site-packages/ykdl/embedextractor.py", line 50, in parser
    return s.parser(vid)
  File "/usr/local/lib/python2.7/site-packages/ykdl/extractor.py", line 21, in parser
    info = self.prepare()
  File "/usr/local/lib/python2.7/site-packages/ykdl/extractors/acorig.py", line 26, in prepare
    stream_data = json.loads(data)
  File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
**ValueError: No JSON object could be decoded**

**Comment by fogmoon** [comment]
@zhangn1985 

抱歉，我下载了您的更新，执行命令还是报
`No JSON object could be decoded`
异常。

是所有的 `url` 都报异常，所以我不清楚是不是只有我这里出现异常，谢谢

我使用`you-get` 命令可以正常运行。

**Comment by zhangn1985** [comment]
```
ykdl -i http://www.acfun.tv/v/ac3101039
site:                AcFun 优酷合作视频
title:               acfun_1473736947497
artist:              None
streams:
    - format:        BD
      container:     mp4
      video-profile: 1080p
    # download-with: ykdl --format=BD [URL]
Real urls:
http://60.205.15.71/cloudvideo/kservice-route/get.json?timestamp=1489145437&fid=030080080057D79A5AF8EB2D9B7D2F9F4C2A46-F865-7B27-358D-6C588A48ED3C.flv&ns=video.acfun.cn&vid=585f573c0cf2845db661b9de&customer_id=5859fdaee4b0eaf5dd325b91&sign=ct58c28e5d0cf2a952ed2dc4a8
http://60.205.15.71/cloudvideo/kservice-route/get.json?timestamp=1489145437&fid=030080080157D79A5AF8EB2D9B7D2F9F4C2A46-F865-7B27-358D-6C588A48ED3C.flv&ns=video.acfun.cn&vid=585f573c0cf2845db661b9de&customer_id=5859fdaee4b0eaf5dd325b91&sign=ct58c28e5d0cf2a952ed2dc4a8
http://60.205.15.71/cloudvideo/kservice-route/get.json?timestamp=1489145437&fid=030080080257D79A5AF8EB2D9B7D2F9F4C2A46-F865-7B27-358D-6C588A48ED3C.flv&ns=video.acfun.cn&vid=585f573c0cf2845db661b9de&customer_id=5859fdaee4b0eaf5dd325b91&sign=ct58c28e5d0cf2a952ed2dc4a8
http://60.205.15.71/cloudvideo/kservice-route/get.json?timestamp=1489145437&fid=030080080357D79A5AF8EB2D9B7D2F9F4C2A46-F865-7B27-358D-6C588A48ED3C.flv&ns=video.acfun.cn&vid=585f573c0cf2845db661b9de&customer_id=5859fdaee4b0eaf5dd325b91&sign=ct58c28e5d0cf2a952ed2dc4a8
http://60.205.15.71/cloudvideo/kservice-route/get.json?timestamp=1489145437&fid=030080080457D79A5AF8EB2D9B7D2F9F4C2A46-F865-7B27-358D-6C588A48ED3C.flv&ns=video.acfun.cn&vid=585f573c0cf2845db661b9de&customer_id=5859fdaee4b0eaf5dd325b91&sign=ct58c28e5d0cf2a952ed2dc4a8
http://60.205.15.71/cloudvideo/kservice-route/get.json?timestamp=1489145437&fid=030080080557D79A5AF8EB2D9B7D2F9F4C2A46-F865-7B27-358D-6C588A48ED3C.flv&ns=video.acfun.cn&vid=585f573c0cf2845db661b9de&customer_id=5859fdaee4b0eaf5dd325b91&sign=ct58c28e5d0cf2a952ed2dc4a8
http://60.205.15.71/cloudvideo/kservice-route/get.json?timestamp=1489145437&fid=030080080657D79A5AF8EB2D9B7D2F9F4C2A46-F865-7B27-358D-6C588A48ED3C.flv&ns=video.acfun.cn&vid=585f573c0cf2845db661b9de&customer_id=5859fdaee4b0eaf5dd325b91&sign=ct58c28e5d0cf2a952ed2dc4a8
http://60.205.15.71/cloudvideo/kservice-route/get.json?timestamp=1489145437&fid=030080080757D79A5AF8EB2D9B7D2F9F4C2A46-F865-7B27-358D-6C588A48ED3C.flv&ns=video.acfun.cn&vid=585f573c0cf2845db661b9de&customer_id=5859fdaee4b0eaf5dd325b91&sign=ct58c28e5d0cf2a952ed2dc4a8
    - format:        TD
      container:     mp4
      video-profile: 超清
    # download-with: ykdl --format=TD [URL]
Real urls:
http://60.205.15.71/cloudvideo/kservice-route/get.json?timestamp=1489145437&fid=030001050057D791F5F8EB2D9B7D2F9F4C2A46-F865-7B27-358D-6C588A48ED3C.flv&ns=video.acfun.cn&vid=585f573c0cf2845db661b9de&customer_id=5859fdaee4b0eaf5dd325b91&sign=ct58c28e5d0cf2a952ed2dc4a8
http://60.205.15.71/cloudvideo/kservice-route/get.json?timestamp=1489145437&fid=030001050157D791F5F8EB2D9B7D2F9F4C2A46-F865-7B27-358D-6C588A48ED3C.flv&ns=video.acfun.cn&vid=585f573c0cf2845db661b9de&customer_id=5859fdaee4b0eaf5dd325b91&sign=ct58c28e5d0cf2a952ed2dc4a8
http://60.205.15.71/cloudvideo/kservice-route/get.json?timestamp=1489145437&fid=030001050257D791F5F8EB2D9B7D2F9F4C2A46-F865-7B27-358D-6C588A48ED3C.flv&ns=video.acfun.cn&vid=585f573c0cf2845db661b9de&customer_id=5859fdaee4b0eaf5dd325b91&sign=ct58c28e5d0cf2a952ed2dc4a8
http://60.205.15.71/cloudvideo/kservice-route/get.json?timestamp=1489145437&fid=030001050357D791F5F8EB2D9B7D2F9F4C2A46-F865-7B27-358D-6C588A48ED3C.flv&ns=video.acfun.cn&vid=585f573c0cf2845db661b9de&customer_id=5859fdaee4b0eaf5dd325b91&sign=ct58c28e5d0cf2a952ed2dc4a8
http://60.205.15.71/cloudvideo/kservice-route/get.json?timestamp=1489145437&fid=030001050457D791F5F8EB2D9B7D2F9F4C2A46-F865-7B27-358D-6C588A48ED3C.flv&ns=video.acfun.cn&vid=585f573c0cf2845db661b9de&customer_id=5859fdaee4b0eaf5dd325b91&sign=ct58c28e5d0cf2a952ed2dc4a8
    - format:        HD
      container:     mp4
      video-profile: 高清
    # download-with: ykdl --format=HD [URL]
Real urls:
http://60.205.15.71/cloudvideo/kservice-route/get.json?timestamp=1489145437&fid=030008030057D78EA6F8EB2D9B7D2F9F4C2A46-F865-7B27-358D-6C588A48ED3C.mp4&ns=video.acfun.cn&vid=585f573c0cf2845db661b9de&customer_id=5859fdaee4b0eaf5dd325b91&sign=ct58c28e5d0cf2a952ed2dc4a8
http://60.205.15.71/cloudvideo/kservice-route/get.json?timestamp=1489145437&fid=030008030157D78EA6F8EB2D9B7D2F9F4C2A46-F865-7B27-358D-6C588A48ED3C.mp4&ns=video.acfun.cn&vid=585f573c0cf2845db661b9de&customer_id=5859fdaee4b0eaf5dd325b91&sign=ct58c28e5d0cf2a952ed2dc4a8
http://60.205.15.71/cloudvideo/kservice-route/get.json?timestamp=1489145437&fid=030008030257D78EA6F8EB2D9B7D2F9F4C2A46-F865-7B27-358D-6C588A48ED3C.mp4&ns=video.acfun.cn&vid=585f573c0cf2845db661b9de&customer_id=5859fdaee4b0eaf5dd325b91&sign=ct58c28e5d0cf2a952ed2dc4a8
    - format:        SD
      container:     mp4
      video-profile: 标清
    # download-with: ykdl --format=SD [URL]
Real urls:
http://60.205.15.71/cloudvideo/kservice-route/get.json?timestamp=1489145437&fid=030002030057D78845F8EB2D9B7D2F9F4C2A46-F865-7B27-358D-6C588A48ED3C.flv&ns=video.acfun.cn&vid=585f573c0cf2845db661b9de&customer_id=5859fdaee4b0eaf5dd325b91&sign=ct58c28e5d0cf2a952ed2dc4a8
http://60.205.15.71/cloudvideo/kservice-route/get.json?timestamp=1489145437&fid=030002030157D78845F8EB2D9B7D2F9F4C2A46-F865-7B27-358D-6C588A48ED3C.flv&ns=video.acfun.cn&vid=585f573c0cf2845db661b9de&customer_id=5859fdaee4b0eaf5dd325b91&sign=ct58c28e5d0cf2a952ed2dc4a8
http://60.205.15.71/cloudvideo/kservice-route/get.json?timestamp=1489145437&fid=030002030257D78845F8EB2D9B7D2F9F4C2A46-F865-7B27-358D-6C588A48ED3C.flv&ns=video.acfun.cn&vid=585f573c0cf2845db661b9de&customer_id=5859fdaee4b0eaf5dd325b91&sign=ct58c28e5d0cf2a952ed2dc4a8
```
你是怎么更新的？

**Comment by zhangn1985** [comment]
https://github.com/zhangn1985/ykdl/commit/c74848ea14175985aa30ecd6ea18e241a363e704
之前的一个改动，导致python2的修复并不完整，再加了一个补丁，请再试试看。
