### ISSUE TITLE
不能下载网易公开课？

### ISSUE THREAD

**Issue by missdeer** [zhangn1985/ykdl#77]
```
e:\Tools\Python36-32\Scripts>..\python.exe ykdl.py -p vlc http://open.163.com/movie/2010/12/E/1/M6UTT5U0I_M6V2UI5E1.html
ykdl: wrong charset for http://open.163.com/movie/2010/12/E/1/M6UTT5U0I_M6V2UI5E1.html
Traceback (most recent call last):
  File "ykdl.py", line 4, in <module>
    __import__('pkg_resources').run_script('ykdl==1.4.6', 'ykdl.py')
  File "e:\Tools\Python36-32\lib\site-packages\pkg_resources\__init__.py", line 743, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "e:\Tools\Python36-32\lib\site-packages\pkg_resources\__init__.py", line 1505, in run_script
    exec(script_code, namespace, namespace)
  File "e:\Tools\Python36-32\lib\site-packages\ykdl-1.4.6-py3.6.egg\EGG-INFO\scripts\ykdl.py", line 161, in <module>
  File "e:\Tools\Python36-32\lib\site-packages\ykdl-1.4.6-py3.6.egg\EGG-INFO\scripts\ykdl.py", line 139, in main
  File "e:\Tools\Python36-32\lib\site-packages\ykdl-1.4.6-py3.6.egg\ykdl\extractor.py", line 21, in parser
  File "e:\Tools\Python36-32\lib\site-packages\ykdl-1.4.6-py3.6.egg\ykdl\extractors\netease\video.py", line 24, in prepare
TypeError: 'NoneType' object is not subscriptable
```

**Comment by zhangn1985** [comment]
目前尚不支持。

**Comment by zhangn1985** [comment]
```
 curl http://live.ws.126.net/movie/E/1/2_M6UTT5U0I_M6V2UI5E1.xml
<?xml version="1.0" encoding="GBK"?>
<all><title>��ʡ����ѧԺ�����Σ��㷨����</title><pnumber>23</pnumber><encrypt>1</encrypt><flvUrl><hd default="true"><flv>E2BA84651E56C82C8CE97002DC1F7CAEA29180ACE8C6DADCA45104768872534AA5C214B0867E1462ED82A6D12127FFD96ABEBBECE4A9CF3A58BA76E368EAEF05751042FBA9140224EFDB9E5FC6EABE21</flv></hd></flvUrl><flvUrlOrigin><hd default="true"><flv>E2BA84651E56C82C8CE97002DC1F7CAEA29180ACE8C6DADCA45104768872534AA5C214B0867E1462ED82A6D12127FFD9CCB9CC7BB2523A56373433BAC12FF2842721F87F83F87CF029E9ADC54F590194</flv></hd></flvUrlOrigin><playurl><SD default="true"><mp4>E2BA84651E56C82C8CE97002DC1F7CAEA29180ACE8C6DADCA45104768872534AA5C214B0867E1462ED82A6D12127FFD96ABEBBECE4A9CF3A58BA76E368EAEF05751042FBA9140224EFDB9E5FC6EABE21</mp4><mp4>605CF28E9E16FC9350EF99E895DD166C6099596C18F1EE427C00BCF1E5942FD15C317D341FCFAB5B052EB73E2E59B2C6576086B4DDACECC421A1FDD18D02631D5A44E1D3805DBF31F3B8771728D4DEC0</mp4></SD></playurl><playurl_origin><SD default="true"><mp4>E2BA84651E56C82C8CE97002DC1F7CAEA29180ACE8C6DADCA45104768872534AA5C214B0867E1462ED82A6D12127FFD9CCB9CC7BB2523A56373433BAC12FF2842721F87F83F87CF029E9ADC54F590194</mp4><mp4>605CF28E9E16FC9350EF99E895DD166C6099596C18F1EE427C00BCF1E5942FD15C317D341FCFAB5B052EB73E2E59B2C6C215AA8813C570EBD0BCD5D1960033A16E50D30C0768C67016A9A4FF8E393B3D</mp4></SD></playurl_origin><protoVersion>2</protoVersion><useMp4>1</useMp4><subs><sub><name>����</name><url>http://oc-caption-srt.nos.netease.com/oc-srt-1417416602651.srt</url></sub><sub><name>Ӣ��</name><url>http://oc-caption-srt.nos.netease.com/oc-srt-1417416607342.srt</url></sub></subs><language current="Ӣ��"/><pageUrl>http://v.163.com/movie/2010/12/E/1/M6UTT5U0I_M6V2UI5E1.html</pageUrl><adv>http://img6.cache.netease.com/video/2012/9/29/20120929161746c8608.jpg</adv><frameTips/><pttime>0</pttime><pwtime>0</pwtime></a
```
不知如何解密。
