### ISSUE TITLE
ConnectionResetError: [Errno 54] Connection reset by peer

### ISSUE THREAD

**Issue by xmugenx** [zhangn1985/ykdl#79]
```
bin/ykdl.py -i http://v.youku.com/v_show/id_XMjUwMzg3MDk4MA==.html
Traceback (most recent call last):
  File "bin/ykdl.py", line 161, in <module>
    main()
  File "bin/ykdl.py", line 139, in main
    info = parser(u)
  File "/Users/wuser/Downloads/ykdl-master/ykdl/extractor.py", line 21, in parser
    info = self.prepare()
  File "/Users/wuser/Downloads/ykdl-master/ykdl/extractors/youkubase.py", line 35, in prepare
    self.extract_single(info, stream_id)
  File "/Users/wuser/Downloads/ykdl-master/ykdl/extractors/youkubase.py", line 76, in extract_single
    url = json.loads(get_content(u))[0]['server']
  File "/Users/wuser/Downloads/ykdl-master/ykdl/util/html.py", line 62, in get_content
    response = urlopen(req)
  File "/usr/local/Cellar/python3/3.6.0_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/Cellar/python3/3.6.0_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/local/Cellar/python3/3.6.0_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/local/Cellar/python3/3.6.0_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python3/3.6.0_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1346, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/local/Cellar/python3/3.6.0_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1321, in do_open
    r = h.getresponse()
  File "/usr/local/Cellar/python3/3.6.0_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/usr/local/Cellar/python3/3.6.0_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/local/Cellar/python3/3.6.0_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/Cellar/python3/3.6.0_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 54] Connection reset by peer
```

**Comment by mengmo** [comment]
```
ykdl -i "http://v.youku.com/v_show/id_XMjUwMzg3MDk4MA==.html"
site:                优酷 (Youku)
title:               大秦帝国之崛起 01
artist:              None
streams:
    - format:        BD
      container:     flv
      video-profile: 1080p
      size:          1010.0 MiB (1059043986 bytes)
    # download-with: ykdl --format=BD [URL]
Real urls:
http://27.221.18.142/youku/6775C5B0E6F4383A9F692C4307/030080150058A6E6657982011BA6A9B419EE21-C168-3E14-F422-7974CFAD96DD.flv?sid=048931348046212e76c7f_00&ctype=12
http://119.188.38.133/youku/6978A88889543832228EDA62A9/030080150158A6E6657982011BA6A9B419EE21-C168-3E14-F422-7974CFAD96DD.flv?sid=048931348046212e76c7f_01&ctype=12
http://27.221.99.138/youku/69799ED07183783007DF9264A0/030080150258A6E6657982011BA6A9B419EE21-C168-3E14-F422-7974CFAD96DD.flv?sid=048931348046212e76c7f_02&ctype=12
http://121.29.55.177/youku/6778A8886243276CCF94C4401/030080150358A6E6657982011BA6A9B419EE21-C168-3E14-F422-7974CFAD96DD.flv?sid=048931348046212e76c7f_03&ctype=12
http://182.118.58.42/youku/697B8B60F243781A45255249A9/030080150458A6E6657982011BA6A9B419EE21-C168-3E14-F422-7974CFAD96DD.flv?sid=048931348046212e76c7f_04&ctype=12
http://27.221.15.132/youku/6578A888DE23B83383A4664EDC/030080150558A6E6657982011BA6A9B419EE21-C168-3E14-F422-7974CFAD96DD.flv?sid=048931348046212e76c7f_05&ctype=12
http://119.188.38.145/youku/697D77F0BD53E82E564112368F/030080150658A6E6657982011BA6A9B419EE21-C168-3E14-F422-7974CFAD96DD.flv?sid=048931348046212e76c7f_06&ctype=12
http://61.182.133.108/youku/677C81A8B4F498351C06FD3C9C/030080150758A6E6657982011BA6A9B419EE21-C168-3E14-F422-7974CFAD96DD.flv?sid=048931348046212e76c7f_07&ctype=12
http://27.221.99.206/youku/697F6480C1D4883F26DEBD395C/030080150858A6E6657982011BA6A9B419EE21-C168-3E14-F422-7974CFAD96DD.flv?sid=048931348046212e76c7f_08&ctype=12
http://121.29.55.103/youku/657C81A87EA3A77E9266B42AF/030080150958A6E6657982011BA6A9B419EE21-C168-3E14-F422-7974CFAD96DD.flv?sid=048931348046212e76c7f_09&ctype=12
http://27.221.99.50/youku/657D77F0F504E8447CE6B2434A/030080150A58A6E6657982011BA6A9B419EE21-C168-3E14-F422-7974CFAD96DD.flv?sid=048931348046212e76c7f_0a&ctype=12
http://27.221.100.106/youku/678105AC872739831CF77AA6DD9/030080150B58A6E6657982011BA6A9B419EE21-C168-3E14-F422-7974CFAD96DD.flv?sid=048931348046212e76c7f_0b&ctype=12
http://121.29.55.13/youku/6781151107534078BE3CBC6C59/030080150C58A6E6657982011BA6A9B419EE21-C168-3E14-F422-7974CFAD96DD.flv?sid=048931348046212e76c7f_0c&ctype=12
http://27.221.15.140/youku/658105AC85454383A9EA2A8467D/030080150D58A6E6657982011BA6A9B419EE21-C168-3E14-F422-7974CFAD96DD.flv?sid=048931348046212e76c7f_0d&ctype=12
http://121.29.55.105/youku/678133DA09274C7A68AC676A0F/030080150E58A6E6657982011BA6A9B419EE21-C168-3E14-F422-7974CFAD96DD.flv?sid=048931348046212e76c7f_0e&ctype=12
http://27.221.99.74/youku/6781433E8B7B3182AB19E4958FD/030080150F58A6E6657982011BA6A9B419EE21-C168-3E14-F422-7974CFAD96DD.flv?sid=048931348046212e76c7f_0f&ctype=12
http://27.221.99.102/youku/658133DA04134B841D1DC1E32C9/030080151058A6E6657982011BA6A9B419EE21-C168-3E14-F422-7974CFAD96DD.flv?sid=048931348046212e76c7f_10&ctype=12
http://27.221.31.211/youku/698180D089BE3C8346AC6225AA2/030080151158A6E6657982011BA6A9B419EE21-C168-3E14-F422-7974CFAD96DD.flv?sid=048931348046212e76c7f_11&ctype=12
http://61.182.133.107/youku/658152A3040B36827182F9B438B/030080151258A6E6657982011BA6A9B419EE21-C168-3E14-F422-7974CFAD96DD.flv?sid=048931348046212e76c7f_12&ctype=12
http://27.221.99.111/youku/658162078B6B4783E4310F328CC/030080151358A6E6657982011BA6A9B419EE21-C168-3E14-F422-7974CFAD96DD.flv?sid=048931348046212e76c7f_13&ctype=12
http://182.118.58.53/youku/6581716C04063781A4527A4403E/030080151458A6E6657982011BA6A9B419EE21-C168-3E14-F422-7974CFAD96DD.flv?sid=048931348046212e76c7f_14&ctype=12
    - format:        TD
      container:     flv
      video-profile: 超清
      size:          527.0 MiB (552567322 bytes)
    # download-with: ykdl --format=TD [URL]
Real urls:
http://121.29.55.139/youku/6573D920EF437777E97C83F22/0300010E0058A6E39D7982011BA6A9B419EE21-C168-3E14-F422-7974CFAD96DD.flv?sid=048931348046212e76c7f_00&ctype=12
http://60.217.224.103/youku/6776BBF86853282AE94422356D/0300010E0158A6E39D7982011BA6A9B419EE21-C168-3E14-F422-7974CFAD96DD.flv?sid=048931348046212e76c7f_01&ctype=12
http://119.188.38.136/youku/6575C5B0F544E83A7DA7905E21/0300010E0258A6E39D7982011BA6A9B419EE21-C168-3E14-F422-7974CFAD96DD.flv?sid=048931348046212e76c7f_02&ctype=12
http://27.221.35.80/youku/697A95186B64A840DBE26F3844/0300010E0358A6E39D7982011BA6A9B419EE21-C168-3E14-F422-7974CFAD96DD.flv?sid=048931348046212e76c7f_03&ctype=12
http://119.188.38.107/youku/6577B2409813782904FB086E39/0300010E0458A6E39D7982011BA6A9B419EE21-C168-3E14-F422-7974CFAD96DD.flv?sid=048931348046212e76c7f_04&ctype=12
http://119.188.38.14/youku/677A95189E14E83A7D82DE5193/0300010E0558A6E39D7982011BA6A9B419EE21-C168-3E14-F422-7974CFAD96DD.flv?sid=048931348046212e76c7f_05&ctype=12
http://121.29.55.11/youku/677B8B609793D7853A7175AB5/0300010E0658A6E39D7982011BA6A9B419EE21-C168-3E14-F422-7974CFAD96DD.flv?sid=048931348046212e76c7f_06&ctype=12
http://27.221.100.55/youku/697E6E3882A4683D5F936A6F4F/0300010E0758A6E39D7982011BA6A9B419EE21-C168-3E14-F422-7974CFAD96DD.flv?sid=048931348046212e76c7f_07&ctype=12
http://123.6.0.102/youku/677D77F09F54D73A7DEEE51FD/0300010E0858A6E39D7982011BA6A9B419EE21-C168-3E14-F422-7974CFAD96DD.flv?sid=048931348046212e76c7f_08&ctype=12
http://27.221.99.183/youku/677E6E38F5130829CDFEFF3E3E/0300010E0958A6E39D7982011BA6A9B419EE21-C168-3E14-F422-7974CFAD96DD.flv?sid=048931348046212e76c7f_09&ctype=12
http://61.182.139.101/youku/657D77F0C86318236923592D92/0300010E0A58A6E39D7982011BA6A9B419EE21-C168-3E14-F422-7974CFAD96DD.flv?sid=048931348046212e76c7f_0a&ctype=12
http://123.6.0.14/youku/698124758D5B3F72FB63EB6BFC/0300010E0B58A6E39D7982011BA6A9B419EE21-C168-3E14-F422-7974CFAD96DD.flv?sid=048931348046212e76c7f_0b&ctype=12
http://121.29.55.184/youku/678115110F1F4E7AAFD30047BE/0300010E0C58A6E39D7982011BA6A9B419EE21-C168-3E14-F422-7974CFAD96DD.flv?sid=048931348046212e76c7f_0c&ctype=12
http://27.221.35.85/youku/658105AC8C803582E336DB533D8/0300010E0D58A6E39D7982011BA6A9B419EE21-C168-3E14-F422-7974CFAD96DD.flv?sid=048931348046212e76c7f_0d&ctype=12
    - format:        HD
      container:     mp4
      video-profile: 高清
      size:          278.9 MiB (292477301 bytes)
    # download-with: ykdl --format=HD [URL]
Real urls:
http://42.236.62.134/youku/6573D920C8D3E839CBF6734140/030008070058A6E2247982011BA6A9B419EE21-C168-3E14-F422-7974CFAD96DD.mp4?sid=048931348046212e76c7f_00&ctype=12
http://27.221.98.79/youku/6978A8886364683D5F0FE26ADA/030008070158A6E2247982011BA6A9B419EE21-C168-3E14-F422-7974CFAD96DD.mp4?sid=048931348046212e76c7f_01&ctype=12
http://123.6.0.173/youku/6777B24093534727412E661F7/030008070258A6E2247982011BA6A9B419EE21-C168-3E14-F422-7974CFAD96DD.mp4?sid=048931348046212e76c7f_02&ctype=12
http://27.221.99.239/youku/6778A88867939831CF5CC24F86/030008070358A6E2247982011BA6A9B419EE21-C168-3E14-F422-7974CFAD96DD.mp4?sid=048931348046212e76c7f_03&ctype=12
http://119.188.38.132/youku/67799ED0AEF3C82CD150ED6E3B/030008070458A6E2247982011BA6A9B419EE21-C168-3E14-F422-7974CFAD96DD.mp4?sid=048931348046212e76c7f_04&ctype=12
http://27.221.99.53/youku/677A951895D4D843993462267C/030008070558A6E2247982011BA6A9B419EE21-C168-3E14-F422-7974CFAD96DD.mp4?sid=048931348046212e76c7f_05&ctype=12
http://119.188.38.13/youku/677B8B60FA74D839BB0C822FE9/030008070658A6E2247982011BA6A9B419EE21-C168-3E14-F422-7974CFAD96DD.mp4?sid=048931348046212e76c7f_06&ctype=12
    - format:        SD
      container:     flv
      video-profile: 标清
      size:          135.0 MiB (141597580 bytes)
    # download-with: ykdl --format=SD [URL]
Real urls:
http://42.236.62.25/youku/6573D9205BF3082C8816FD4E77/030002070058A6DADB7982011BA6A9B419EE21-C168-3E14-F422-7974CFAD96DD.flv?sid=048931348046212e76c7f_00&ctype=12
http://27.221.98.138/youku/6574CF689673A832B2C13625A4/030002070158A6DADB7982011BA6A9B419EE21-C168-3E14-F422-7974CFAD96DD.flv?sid=048931348046212e76c7f_01&ctype=12
http://123.6.0.209/youku/69799ED07353A72BDFF0568E0/030002070258A6DADB7982011BA6A9B419EE21-C168-3E14-F422-7974CFAD96DD.flv?sid=048931348046212e76c7f_02&ctype=12
http://42.236.62.13/youku/6778A888CC748843456636271F/030002070358A6DADB7982011BA6A9B419EE21-C168-3E14-F422-7974CFAD96DD.flv?sid=048931348046212e76c7f_03&ctype=12
http://42.236.62.78/youku/6577B2409D23382F5FCBA928FE/030002070458A6DADB7982011BA6A9B419EE21-C168-3E14-F422-7974CFAD96DD.flv?sid=048931348046212e76c7f_04&ctype=12
http://27.221.98.15/youku/6578A888C4037830078FA0336C/030002070558A6DADB7982011BA6A9B419EE21-C168-3E14-F422-7974CFAD96DD.flv?sid=048931348046212e76c7f_05&ctype=12
http://61.182.139.114/youku/65799ED0E4B3A82A0CDCDE6E0E/030002070658A6DADB7982011BA6A9B419EE21-C168-3E14-F422-7974CFAD96DD.flv?sid=048931348046212e76c7f_06&ctype=12
```
